### ISSUE TITLE
Bug Report: Understand and fix TensorFlow scaling behavior

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#102]
When benchmarking the performance of the TensorFlow backend and optimizer, the performance decreases (run time of test increases) with the number of iterations performed. This should not be happening and needs to be understood and fixed.

This has been [noticed in Issue #77](https://github.com/diana-hep/pyhf/issues/77#issuecomment-379477976).

# Expected Behavior

The performance of the backend should be independent of the number of iterations, and should be distributed about some central value for a particular configuration of a fit.

# Actual Behavior

The performance is dependent on the number of iterations at a benchmark point

`n_runs=5`             |  `n_runs=8`
:-------------------------:|:-------------------------:
![benchmark_times_5_log](https://user-images.githubusercontent.com/5142394/38456508-9b8c0b32-3a85-11e8-8532-45597fb861d5.png)  |  ![benchmark_times_8_log](https://user-images.githubusercontent.com/5142394/38456509-9e6b9458-3a85-11e8-93b6-8ea66dd13fb2.png)

# Steps to Reproduce

Enable the TensorFlow backend in `tests/test_benchmark.py` and run
```
pytest --benchmark-sort=mean --benchmark-histogram=benchmark_tf tests/test_benchmark.py
```

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by matthewfeickert** [comment]
@lukasheinrich Still seeing it with this

```python
def benchmark_backend(n_bins, n_runs):
    times = [[time_runOnePoint(bins) for bins in n_bins]
             for _ in range(n_runs)]

    return summary_stats(times)
```
```python
def run_benchmark(n_bins, n_runs=5, file_name='times'):
    # following is slightly abridged as writing to dictionaries is taken out for space

    default_backend = pyhf.tensorlib

    pyhf.set_backend(numpy_backend())
    t_mean, t_min, t_max, t_std = benchmark_backend(n_bins, n_runs)

    pyhf.set_backend(tensorflow_backend(session=tf.Session()))
    t_mean, t_min, t_max, t_std = benchmark_backend(n_bins, n_runs)

    pyhf.set_backend(pytorch_backend())
    t_mean, t_min, t_max, t_std = benchmark_backend(n_bins, n_runs)

    # Reset backend
    pyhf.set_backend(default_backend)
```
![benchmark_times_alt_log](https://user-images.githubusercontent.com/5142394/38467842-0632ecb8-3b3e-11e8-96c1-941ee5843b00.png)

**Comment by lukasheinrich** [comment]
I think we might to reset the TF graph / session on each run. This might be related

https://github.com/tensorflow/tensorflow/issues/1439

but it does seem like TF is just slower even on the first iteration. this is the code i'm testing

```
import time
import tensorflow as tf
import pyhf.tensor
import pyhf.simplemodels

tfb = pyhf.tensor.tensorflow_backend.tensorflow_backend()
tfb.session = tf.Session()

p = pyhf.simplemodels.hepdata_like([7.],[50.],[7.])

pyhf.set_backend(tfb)

for i in range(10):
  now = time.time()
  pyhf.runOnePoint(1.0, [50.] + p.config.auxdata, p, p.config.suggested_init(), p.config.suggested_bounds())
  delta = time.time() - now
  print(delta)
```

**Comment by lukasheinrich** [comment]
this seems to have constant deltas @matthewfeickert 

```
import time
import tensorflow as tf
import pyhf.tensor
import pyhf.simplemodels


for i in range(10):
  tfb = pyhf.tensor.tensorflow_backend.tensorflow_backend()
  tfb.session = tf.Session()
  pyhf.set_backend(tfb)

  now = time.time()
  p = pyhf.simplemodels.hepdata_like([7.],[50.],[7.])
  pyhf.runOnePoint(1.0, [50.] + p.config.auxdata, p, p.config.suggested_init(), p.config.suggested_bounds())
  delta = time.time() - now
  print(delta)
  tf.reset_default_graph()
```

**Comment by matthewfeickert** [comment]
Indeed, pretty consistent. :+1: I'll implement this in the benchmarks later this evening.

**Comment by lukasheinrich** [comment]
so I think in order to reset cleanly only this is necessary
```
  tf.reset_default_graph()
  pyhf.tensorlib.session = tf.Session()
```

**Comment by matthewfeickert** [comment]
Yeah, that's what I just found too.

**Comment by lukasheinrich** [comment]
once we get more familiarity, it might be useful to implement a tensorlib.reset(), but for now it probably good to keep these things explicit, also if people want to use pyhf as part of a larger graph, we probably should mess with it or the session

**Comment by matthewfeickert** [comment]
Indeed, that's a good idea. Can you open up a `tensorlib.reset()` Issue (for future work)?
