### ISSUE TITLE
Deprecation warnings (due to missing raw strings?)

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/pyhf#1021]
# Description

I see the following deprecation warnings when using `pyhf.infer.mle.fit`:

```
/usr/local/lib/python3.8/site-packages/pyhf/infer/mle.py:22
  /usr/local/lib/python3.8/site-packages/pyhf/infer/mle.py:22: DeprecationWarning: invalid escape sequence \s
    """

/usr/local/lib/python3.8/site-packages/pyhf/infer/mle.py:65
  /usr/local/lib/python3.8/site-packages/pyhf/infer/mle.py:65: DeprecationWarning: invalid escape sequence \s
    """

/usr/local/lib/python3.8/site-packages/pyhf/infer/calculators.py:35
  /usr/local/lib/python3.8/site-packages/pyhf/infer/calculators.py:35: DeprecationWarning: invalid escape sequence \h
    """
```

They may be related to not using raw strings in some docstrings, but this is only a guess. They only seem to appear in a quite specific setup, see below. I cannot exclude that they are really an issue with `typeguard`.

# Expected Behavior

no `DeprecationWarning`

# Actual Behavior

multiple `DeprecationWarning`

# Steps to Reproduce

I can only see this happening when running `pytest` with `typeguard` active. Running in docker `python:3.8-slim`.

`pip install pyhf pytest typeguard`

Create the following structure:
```
root@0804a87b56d2:/pyhf-warning# tree
.
├── module
│   └── __init__.py
└── test.py

1 directory, 2 files
root@0804a87b56d2:/pyhf-warning# cat module/__init__.py
import pyhf

def run():
    model = pyhf.simplemodels.hepdata_like(
        signal_data=[12.0, 11.0], bkg_data=[50.0, 52.0], bkg_uncerts=[3.0, 7.0]
    )
    pyhf.infer.mle.fit([60, 50] + model.config.auxdata, model)
root@0804a87b56d2:/pyhf-warning# cat test.py
import typeguard
import module

def test():
    module.run()
```

Run `pytest --typeguard-packages=module test.py` to get the warnings. Run the same thing again and the warnings are gone. Even after deleting `.pytest_cache`, `__pycache__`, `module/__pycache__`, running the command again does not produce more warnings.

# Checklist

- [ ] Run `git fetch` to get the most up to date version of `master`
- [ ] Searched through existing Issues to confirm this is not a duplicate issue
- [ ] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by tirkarthi** [comment]
Some of it seems to have been fixed with https://github.com/scikit-hep/pyhf/commit/d4e329af7235b37159398522545100c80e3fa6df . calculators.py warning is fixed with https://github.com/scikit-hep/pyhf/pull/1047

**Comment by alexander-held** [comment]
I have not explicitly verified this, but #1191 probably took care of this issue.

**Comment by kratsg** [comment]
Confirmed this is fixed as I see no warnings now.
