### ISSUE TITLE
Class returned by pyhf.Workspace.combine

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/pyhf#1023]
# Question

Not a bug so I'm opening this as a question: The `pyhf.Workspace.combine` classmethod returns a `Workspace` explicitly instead of `cls`.

https://github.com/scikit-hep/pyhf/blob/e260626689f46414be185d834499cc65dce5a4b0/src/pyhf/workspace.py#L678

To work better with classes that want to inherit from `pyhf.Workspace`, I think it would be better to return the class as

```python
return cls(newspec) 
```

# Relevant Issues and Pull Requests

none I'm aware of

**Comment by kratsg** [comment]
Hah.. good point. I feel like a hypocrite for writing it this way when we had to fix this with iminuit :)
