### ISSUE TITLE
Data field in normfactor/shapefactor/lumi schemas

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/pyhf#1026]
# Question

Why do the `normfactor`, `shapefactor` and `lumi` specifications require a `data` field that has to be `null`?

https://github.com/scikit-hep/pyhf/blob/e260626689f46414be185d834499cc65dce5a4b0/src/pyhf/schemas/1.0.0/defs.json#L126-L134

Given that there is no freedom in the value to be specified, I'm curious what the purpose of this is. Is it a parsing issue (since other modifiers need `data`)?

# Relevant Issues and Pull Requests

none I'm aware of

**Comment by kratsg** [comment]
@alexander-held mostly uniformity. A little bit user-friendly as well. This was a design decision and partly technical (I think, depends on what 2-years-ago-Giordon thinks). Particularly, an empty `config.parameters` at least indicates the structure that one could add in parameter configurations, and that someone could edit the JSON to quickly add it in. Similarly, one could change a modifier type and fill in the data pretty quickly.

For json schema, it's tricky to have ask for a required option that *must* have a list of elements, while simultaneously not requiring it if the list is empty .JSON schema doesn't have that super nice configurability in draft-6, but it might in draft-8 (but that's not stable enough to me).

**Comment by alexander-held** [comment]
Thanks for the insight @kratsg! Feel free to close this.
