### ISSUE TITLE
Add CLI API to download likelihood patchset archives from HEPData

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1045]
# Description

At the moment to download a published likelihood archive from HEPData and extract the tarball into another directory you need to be a bit handy with `tar`. This is the most concise command I think you can do to download the archive for the likelihoods for [_Search for direct production of electroweakinos in final states with one lepton, missing transverse momentum and a Higgs boson decaying into two b-jets in (pp) collisions at s√=13 TeV with the ATLAS detector_](https://www.hepdata.net/record/ins1755298?version=3)

```
$ curl -sL https://www.hepdata.net/record/resource/1408476?view=true | tar -xzv --one-top-level=1Lbb-likelihoods
BkgOnly.json
patchset.json
README.md
$ cd 1Lbb-likelihoods
$ pyhf patchset verify BkgOnly.json patchset.json 
All good.
```

### Describe the solution you'd like

It might be worth considering adding a command to the CLI API to download and extract archives. Maybe something like

```
$ pyhf patchset download --help
Usage: pyhf patchset download [OPTIONS] [ARCHIVE_URL] [OUTPUT_DIRECTORY]

  Download the patchset archive from the remote URL
  and extract it in a directory at the path given.

  Returns:     None

Options:
  -h, --help  Show this message and exit.
$ pyhf patchset download https://www.hepdata.net/record/resource/1408476?view=true 1Lbb-likelihoods
$ ls 1Lbb-likelihoods/
BkgOnly.json  patchset.json  README.md
```

which would download and extract the archive at https://www.hepdata.net/record/resource/1408476?view=true to `1Lbb-likelihoods/`. The default would be silent, so similar to

```
$ curl -sL https://www.hepdata.net/record/resource/1408476?view=true | tar -xz --one-top-level=1Lbb-likelihoods
```

but if a `-v`, `--verbose` flag was passed it would similarly get passed to `tar` as

```
$ curl -sL https://www.hepdata.net/record/resource/1408476?view=true | tar -xzv --one-top-level=1Lbb-likelihoods
```

**Comment by lukasheinrich** [comment]
I was thinking along similar lines: do we want this to be in pyhf proper or maybe a separate tool (or for now in `pyhf contrib` ?)

**Comment by kratsg** [comment]
this part i'm not so sure about. my main concern is that if we support hepdata explicitly, or at least provided a local database of results, we start becoming opinionated about which patchset/bkgonly files we use.

**Comment by matthewfeickert** [comment]
> I was thinking along similar lines: do we want this to be in pyhf proper or maybe a separate tool (or for now in `pyhf.contrib` ?)

I think it is something that _belongs_ in another tool but would be nice to have. Are you and @kratsg comfertable with me moving it to `contrib` and then figuring out what the CLI looks like for that?

> my main concern is that if we support hepdata explicitly, or at least provided a local database of results, we start becoming opinionated about which patchset/bkgonly files we use.

Hm, I guess I don't see the issue with explicitly supporting HEPData in PR #1046, given that we already treat it as the only official source of likelihoods. I'm not sure what you mean RE: the local database though. PR #1046 doesn't do anything like that.

**Comment by matthewfeickert** [comment]
>  @lukasheinrich, are you and @kratsg comfortable with me moving it to contrib and then figuring out what the CLI looks like for that?

PR #1046 now has this migrated to the `contrib` group with a CLI API of

```
pyhf download
```

**Comment by kratsg** [comment]
> PR #1046 now has this migrated to the `contrib` group with a CLI API of

you mean `pyhf contrib download`? I prefer this as it's more clear that it might be removed/split off later.

**Comment by matthewfeickert** [comment]
> you mean `pyhf contrib download`? I prefer this as it's more clear that it might be removed/split off later.

Yes. I updated it after I posted that reply. The current CLI API is `pyhf contrib download` to make thins explicit and there is an example over on PR #1046

**Comment by matthewfeickert** [comment]
This should also be able to handle a URL that is just a tarball in a public area. That is

```
pyhf contrib download --force http://www.someplace.org/www/public/likelihoods.tar.gz example
```

should work.
