### ISSUE TITLE
Start Community announcement mailing list

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1062]
# Description

In addition to just having the core devs tweet about things using the [`#pyhf` hashtag](https://twitter.com/search?q=%23pyhf&src=typed_query&f=live) It would probably be good if we created a mailing list that people could subscribe to _but not send mail to_ to receive announcements. We should of course also suggest that they sign up to receive notifications from GitHub at least at the "Releases  Only" level, but I think a mailing list could be quite useful especially to notify people like @cranmer and @msneubauer (PIs who are going to be interested in the project but probably aren't checking GitHub emails), and Daniel Whiteson (PIs who want to be using `pyhf` but aren't on GitHub). I can also see a use case where people like @alexander-held might want to be able to forward such an email to users not on the mailing list to point something out.

It isn't a reasonable assumption that all of pyhf's users will have CERN email addresses now that theorists are starting to pick it up more and more, so this should probably not use CERN's e-groups (Also the [`e-groups`  search and add page](https://e-groups.cern.ch/e-groups/EgroupsSearchForm.do) is behind CERN sign on and people should be able to add themselves).

**Comment by matthewfeickert** [comment]
cc @story645 in case they have time to share their thoughts/experience here.

**Comment by story645** [comment]
I'm all for as many modalities as you have the bandwidth to support. 

You might want to have a dedicated @pyhf that the devs can all tweet as through tweet deck so folks can follow for announcements (and you can automate to tweet on new releases).

The matplotlib [ANN] mailing list isn't read only but doesn't really get spam - I suggest instead making it that posts to your list need to be moderated so that folks can post related announcements & reply as needed. If that proves too much overhead, then shift it to read only.

**Comment by matthewfeickert** [comment]
Both @bbockelm and @davidlange6 have recommended that `pyhf` just start a Google Groups.

**Comment by matthewfeickert** [comment]
For the time being I've created a `pyhf-announcements` Google Group for a public announcement email list. I now need to figure out instructions for how to join this group _without_ using a GMail email address.

**Comment by matthewfeickert** [comment]
> I now need to figure out instructions for how to join this group without using a GMail email address.

[Seems this is already possible](https://support.google.com/groups/answer/1067205?hl=en#), and it just has the (potentially desired?) effect of not letting you use the group web interface and forces you to use it as mail only.

> ## Join a Google group without a Gmail address
> 
> If you don't have a Google Account, you can:
> - Read posts in public groups
> - Search for posts in public groups
> 
> You need a Google Account to:
> - Create and manage a group
> - Join a group
> - Post to a group
> - Delete a post
> - Read a restricted group's posts

It seems that the way that people would subscribe to the mailing list without a Google Account would be to visit 

```
https://groups.google.com/group/<group-name-goes-here>/subscribe
```
so in our case: https://groups.google.com/group/pyhf-announcements/subscribe
