### ISSUE TITLE
pip install in clean environment fails (python 3.8)

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/pyhf#1072]
I just cloned develop, made a fresh environment with `python3 -m venv` and then ran
`pip install --ignore-installed -U  --no-cache-dir -e '.[test]'` inside. It fails with
```
ERROR: tensorflow 2.2.0 has requirement scipy==1.4.1; python_version >= "3", but you'll have scipy 1.5.2 which is incompatible.
```
Just wanted to let you know. I don't know why it apparently works in your GHA scripts, because that's where I got this command from.

**Comment by kratsg** [comment]
> ```
> ERROR: tensorflow 2.2.0 has requirement scipy==1.4.1; python_version >= "3", but you'll have scipy 1.5.2 which is incompatible.
> ```

This isn't a failing pip install (try `echo $?` to see the status code). Generally, we're aware that tensorflow has some incompatibilities here, but this is ok since we don't rely on the parts of tensorflow that rely on scipy.

**Comment by HDembinski** [comment]
Ok.
