### ISSUE TITLE
Drop Python 3.6 testing and support

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1075]
# Description

As more and more projects start to drop Python 3.6 support, should we follow [NEP 29 — Recommend Python and Numpy version support as a community policy standard](https://numpy.org/neps/nep-0029-deprecation_policy.html) and while not changing 

https://github.com/scikit-hep/pyhf/blob/72faa1c21f5446957ed33dab2135c9dc55bfb5c5/setup.cfg#L39

to

```
python_requires = >=3.7
```

remove Python 3.6 from testing? Or should we only remove a release from testing once we're also going to drop any support for it at all?

Not sure if @jpivarski, @HDembinski, and @henryiii have general thoughts as well from a Scikit-HEP perspective.

For reference, here is the [NEP drop schedule](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule)

```
On next release, drop support for Python 3.5 (initially released on Sep 13, 2015)
On Jan 07, 2020 drop support for Numpy 1.14 (initially released on Jan 06, 2018)
On Jun 23, 2020 drop support for Python 3.6 (initially released on Dec 23, 2016)
On Jul 23, 2020 drop support for Numpy 1.15 (initially released on Jul 23, 2018)
On Jan 13, 2021 drop support for Numpy 1.16 (initially released on Jan 13, 2019)
On Jul 26, 2021 drop support for Numpy 1.17 (initially released on Jul 26, 2019)
On Dec 22, 2021 drop support for Numpy 1.18 (initially released on Dec 22, 2019)
On Dec 26, 2021 drop support for Python 3.7 (initially released on Jun 27, 2018)
On Jun 21, 2022 drop support for Numpy 1.19 (initially released on Jun 20, 2020)
On Apr 14, 2023 drop support for Python 3.8 (initially released on Oct 14, 2019)
```

**Comment by matthewfeickert** [comment]
FWIW, I feel that dropping Python 3.6 is pretty safe as I think that anywhere people are going to encounter Python 3 now they're going to encounter Python 3.7+. For instance, on a CVMFS cluster if you use a [`LCG_98python3 x86_64-centos7-gcc8-opt` view](https://github.com/matthewfeickert/dotfiles/blob/b78e6cc0a1cbf500f15a2990400ff310ece56b81/.bashrc_user_ATLAS#L8-L25) you'l get

```
$ python --version --version
Python 3.7.6 (default, Aug 12 2020, 09:46:40) 
[GCC 8.3.0]
```

**Comment by henryiii** [comment]
I feel dropping 3.6 is really harsh, as foundational libraries are just now beginning to drop 3.5, and 3.6 is a fantastic version of Python. However, NEP 29 was agreed upon, and we can be as harsh as NEP 29 but no harsher, so I'd be okay with it. Personally, I'd likely start pushing for it after 3.9 is released.

Dropping 3.6 really does enable a plethora of goodies, foremost of which is `from __future__ import annotations`. :) Once we get a 3.9 compatible mypy, writing `: list[int]` instead of `from typing import List, List[int]` will be very nice...

**Comment by henryiii** [comment]
And if you drop from testing, you should drop from support. Not tested == not supported. Make sure to update Python requires!

**Comment by matthewfeickert** [comment]
> And if you drop from testing, you should drop from support. Not tested == not supported. Make sure to update Python requires!

This was my thoughts as well, but @jpivarski and @lukasheinrich suggested this might be a bit harsh and we should just warn that users are using an unsupported version.

**Comment by matthewfeickert** [comment]
Maybe we should just say that we'll drop Python 3.6 when we release `pyhf` `v3.6.0`?

**Comment by henryiii** [comment]
NEVER drop testing for a version without changing `python_requires`. The point of `python_requires` is to allow things to still work (for example, NumPy),  while you move forward. `llvmlite` is an example of where someone thought they would be “nice”/“clever” and not change Python requires until the version after breaking things, and that was a colossal mess. Also, never drop a Python version as a patch release.

Testing should always be the last to go. You can “officially” support/recommend 3.7+ but keep `python_requires` AND testing, or you can drop both; users on 3.6 will just keep getting the old version. That’s the whole point of `python_requires`, to not break things for older Python users!

**Comment by matthewfeickert** [comment]
Given this let's just drop Python 3.6 support when we release `pyhf` `v3.6.0`. There will be plenty of time for us to announce it.

**Comment by matthewfeickert** [comment]
For posterity and education I'll also leave this comment from @henryiii in the IRIS-HEP Slack:

> `pip` selects the most recent version from PyPI that has a matching `python_requires`. That’s why `pip install numpy` works on Python 3.5. And Python 2.7. The point of NEP 29 is “let’s not be held back by developing new versions for old Pythons; old Python users should also get old NumPy/etc versions too”

**Comment by HDembinski** [comment]
> NEVER drop testing for a version without changing python_requires.

This forceful language is not necessary between us.

@henryiii Since you thought about this already a lot, could you perhaps write this down in a succinct way as part of the Scikit-HEP guidelines?

**Comment by eduardo-rodrigues** [comment]
> Given this let's just drop Python 3.6 support when we release `pyhf` `v0.6.0`. There will be plenty of time for us to announce it.

This seems very sensible 👍 .

**Comment by matthewfeickert** [comment]
PR #1046 has some Python 3.6 specific code in the tests it adds that can be dropped in the PR for this.

**Comment by matthewfeickert** [comment]
We've now put out a [call for community feedback on this Issue](https://groups.google.com/g/pyhf-announcements/c/ct6YX7dn7pU) and if we don't get any resistance before 2021-01-29 we'll have dropping Python 3.6 support be the last step in the `v0.6.0` release.

**Comment by matthewfeickert** [comment]
It is also worth noting that the [end of life for Python 3.6 is December 2021](https://www.python.org/dev/peps/pep-0494/#lifespan) so now seems like a good time to move off a Python runtime that won't be supported in the near-ish future.

**Comment by matthewfeickert** [comment]
@alexander-held As [`cabinetry` is Python `3.6+`](https://github.com/alexander-held/cabinetry/blob/e8850ee643a4209d3f590554b6d344aa84e0de16/setup.cfg#L22) will dropping Python 3.6 in `v0.6.0` mess things up for you? Or would you also be willing to drop Python 3.6 in the next `cabinetry` release? Sorry, we should have asked you about this a long time ago.

**Comment by alexander-held** [comment]
@matthewfeickert No worries, I was following the discussion. There has only been a minor inconvenience in `cabinetry` so far (need to keep `ignore_missing_imports = True` for `numpy` when running `mypy` in 3.6), so there is no strong reason to drop support from the `cabinetry` side. Nevertheless, if this goes into `pyhf` 0.6, then `cabinetry` 0.2 will follow along. I do not expect complications from this.

**Comment by matthewfeickert** [comment]
> Nevertheless, if this goes into `pyhf` 0.6, then `cabinetry` 0.2 will follow along. I do not expect complications from this.

Fantastic. Thanks very much for being so flexible @alexander-held, and for excellent lines of communication. :+1:
