### ISSUE TITLE
Migrate testing of notebooks into nightly test

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1077]
# Description

As the notebooks take by far the longest to run and and are very rarely affected by changes it seems that we waste a lot of time on CI waiting for them to run. It would probably be a more efficient use of time to just run all the notebooks in a nightly CRON job.

**Comment by kratsg** [comment]
This is not a bad idea at all... I like it.

**Comment by matthewfeickert** [comment]
> This is not a bad idea at all... I like it.

We'll still catch if anything breaks the notebooks within 24 hours, and we can manually test them as well both locally and with workflow dispatch.
