### ISSUE TITLE
Migrate from bumpversion to bump2version

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1082]
# Description

@dguest has brought to my attention that [`bumpversion` is no longer maintained](https://github.com/peritus/bumpversion) (as of apparently November 2019). Given this we should probably take the project's advice

> 🎬 If you want to start using `bumpversion`, you're best advised to install one of the maintained forks, e.g. ➡ @ c4urself's [`bump2version`](https://github.com/c4urself/bump2version/#installation).

given that it seems that [transferring ownership and maintainers is taking a very long time/might not happen](https://github.com/c4urself/bump2version/issues/86).

**Comment by kratsg** [comment]
is it just as easy as switching to `bump2version`?

**Comment by matthewfeickert** [comment]
> is it just as easy as switching to `bump2version`?

I think so as `bump2version` is just a direct fork and uses `.bumpversion.cfg`. I just made this Issue as more of a reminder to myself.
