### ISSUE TITLE
Add CONTRIBUTORS file

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1094]
# Description

To recognize the contributions of everyone outside of the core devs it would be nice to add a `CONTRIBUTORS` file like the [`AUTHORS` file](https://github.com/scikit-hep/pyhf/blob/3d121b30fdef566fb7436d3a0ecd2a38930fc8f4/AUTHORS) that lists all their names. The `CONTRIBUTING.md` file should also be updated to tell people that they should add their name if they make a PR.

**Comment by lukasheinrich** [comment]
galaxy brain version: have CI action that scanes repo and adds names to CONTRIBUTORS if they're not part of it yet

**Comment by matthewfeickert** [comment]
> galaxy brain version: have CI action that scanes repo and adds names to CONTRIBUTORS if they're not part of it yet

I think I might settle for just having GitHub Action bot that reminds people to add their name to it each time they open a PR and aren't a core dev. :)

Also I'm thinking of having this be a section in the website docs now, rather than a `CONTRIBUTORS` file at top level.
