### ISSUE TITLE
Model creation from existing model - parameter names missing in model spec?

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/pyhf#1098]
# Question

I would like to create a new `pyhf.Model` from an existing model. This seems to work in general via `pyhf.Model(model.spec)`, see the example below. The example fails when working with a custom workspace that includes parameter specifications:

```python
import pyhf

model_hepdata = pyhf.simplemodels.hepdata_like(
    signal_data=[12.0, 11.0], bkg_data=[50.0, 52.0], bkg_uncerts=[3.0, 7.0]
)

# this works
pyhf.Model(model_hepdata.spec)

# custom workspace specification
ws = {
    "channels": [
        {
            "name": "SR",
            "samples": [
                {
                    "data": [
                        10.0,
                    ],
                    "modifiers": [
                        {"data": None, "name": "mu", "type": "normfactor"},
                    ],
                    "name": "Signal",
                }
            ],
        }
    ],
    "measurements": [
        {
            "config": {
                "parameters": [{"bounds": [[0, 5]], "inits": [1], "name": "mu"}],
                "poi": "mu",
            },
            "name": "minimal_example",
        }
    ],
    "observations": [{"data": [12], "name": "SR"}],
    "version": "1.0.0",
}
workspace = pyhf.Workspace(ws)

# this works as well
model_from_ws = workspace.model()

# this does not work
pyhf.Model(model_from_ws.spec)
```

To make the last step work, the missing `"name"` needs to be added back into the specification:

```python
model_from_ws.spec["parameters"][0].update({"name": "mu"})
pyhf.Model(model_from_ws.spec)
```

Is this a bug?

And as another question, would this be the recommended way to create a modified model from an existing model? I would extract the `.spec`, modify that and feed it back into `pyhf.Model`.

# Relevant Issues and Pull Requests

none I'm aware of

**Comment by kratsg** [comment]
confirmed bug -- can be fixed: https://github.com/scikit-hep/pyhf/blob/d178014019206a862d3313e0420d6c6a81504e40/src/pyhf/pdf.py#L213

we probably want to deep-copy the spec through to `ModelConfig` to be safe in any case -- but not sure why we need to `pop`. We could just `get` and not `pop`, then add a test to assert the spec remains unchanged when fed through.
