### ISSUE TITLE
fixed information faulty in validation example

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/pyhf#1107]
# Description

```
pyhf xml2json validation/xmlimport_input/config/example.xml  --basedir validation/xmlimport_input
```

produces

```
                    {
                        "fixed": true,
                        "name": "alpha_syst1"
                    }
```

whereas it should produce (I think)

```
                    {
                        "fixed": true,
                        "name": "syst1"
                    }
```

**Comment by kratsg** [comment]
Looking at this XML - my guess is the XML is specifying this fixed information wrong. I was under the assumption that the names had to match for whatever goes into the XML's ParamSetting.

**Comment by lukasheinrich** [comment]
the issue is that ROOT uses a naming convention `alpha_` for normsys, histosys and `gamma_` for shapesys, staterror, which we do not implement in `pyhf`.  Initially I thought that's useful because we might in the future intrroduce other types of modifiers that lie somewherre between histosys and shapesys (partially correlated binwise shifts). So we'd need to strip "alpha_" from whatever is in fixedparams
