### ISSUE TITLE
move cli/contrib.py to contrib/cli.py

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/pyhf#1117]
# Description

would be good to really keep all "contrib" code in one source location

**Comment by matthewfeickert** [comment]
I think this is mainly just going to involve physically moving the code from `cli/contrib.py` to `contrib/cli.py` and then changing the relevant imports in `cli/cli.py`

https://github.com/scikit-hep/pyhf/blob/abe4ebdb3fa320c074ed12c30829d2eda0e70d29/src/pyhf/cli/cli.py#L7

I think everything else from PR #1046 can stay the same. :+1:
