### ISSUE TITLE
Making workspaces immutable?

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/pyhf#1127]
# Question

Currently workspaces are mutable:

```python
import pyhf
spec = {
    "channels": [
        {
            "name": "Signal Region",
            "samples": [
                {
                    "data": [10],
                    "modifiers": [
                        {"data": [1], "name": "staterror_Signal-Region", "type": "staterror"},
                        {"data": None, "name": "Signal strength",  "type": "normfactor"},
                    ],
                    "name": "Signal",
                }
            ],
        }
    ],
    "measurements": [
        {
            "config": {
                "parameters": [{"name": "staterror_Signal-Region", "fixed": True, "inits": [1.1]}],
                "poi": "Signal strength",
            },
            "name": "fit",
        }
    ],
    "observations": [{"data": [475], "name": "Signal Region"}],
    "version": "1.0.0",
}
ws = pyhf.Workspace(spec)
model = ws.model()
print(model.config.suggested_init())  # -> [1.1, 1.0]
spec["measurements"][0]["config"]["parameters"][0]["inits"] = [1.2]
print(model.config.suggested_init())  # -> [1.1, 1.0]
model = ws.model()
print(model.config.suggested_init())  # -> [1.2, 1.0]
```

Models on the other hand are immutable. What do you think about making workspaces immutable as well? While I do not have a concrete example in mind, I imagine it could prevent some difficult-to-debug scenarios where the workspace changes without the user noticing.

# Relevant Issues and Pull Requests

none

**Comment by alexander-held** [comment]
some possible motivation for this change from @kratsg:

> if you change the spec, summary information is not recomputed.

**Comment by lukasheinrich** [comment]
this is because  we deep-copy the spec in Model:

https://github.com/scikit-hep/pyhf/blob/master/src/pyhf/pdf.py#L559

while we reuse the ctor-argument in `Workspace.__init__.py`

super(Workspace, self).__init__(spec, channels=spec['channels'])

I would personally introduce a deepcopy in wspace as well.

**Comment by matthewfeickert** [comment]
From an IRIS-HEP Slack comment form @kratsg:

> not too much work. we could disentangle the `class Workspace(dict)` part, and then hide the `spec` inside a member variable inside that object. then provide a custom `to_json` method since we do rely on converting `Workspace` back to JSON (which I lazily implemented by just inheriting from `dict`).

**Comment by lukasheinrich** [comment]
I thiink a simple change like

```
spec_copy = copy.deepcopy(spec)
super(Workspace, self).__init__(spec_copy, channels=spec_copy['channels'])
```

should suffice

**Comment by matthewfeickert** [comment]
@lukasheinrich Sorry hadn't taken the time to read all the other replies when I copy pasted that in. That would be great.
