### ISSUE TITLE
significant speedups with other optimizer methods and somehow loss due to pyhf API

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/pyhf#1156]
# Description

some how the pyhf APIs incur a pretty big overhead  but also SLSQP is not the fastest method

![image](https://user-images.githubusercontent.com/2318083/97506235-c4990800-197a-11eb-8c3e-e317c2f420bd.png)
[need_for_speed.ipynb.txt](https://github.com/scikit-hep/pyhf/files/5455249/need_for_speed.ipynb.txt)

**Comment by matthewfeickert** [comment]
Closed as duplicate of #1157
