### ISSUE TITLE
Saturated model likelihood

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/pyhf#1169]
# Description

The saturated model (see [this note](http://www.physics.ucla.edu/~cousins/stats/cousins_saturated.pdf)) is useful for goodness-of-fit testing. One way of obtaining it is to add one `shapefactor` to each bin for a given `pyhf.pdf.Model`, and to fit that new model to data. This will result in a perfect fit without the need to pull any constrained nuisance parameter, and the best-fit likelihood is the desired saturated likelihood.

It should be possible to calculate this saturated likelihood without the need for a fit. It would be convenient to have a function that calculates it in `pyhf`, but I understand it might be out of scope.

## Is your feature request related to a problem? Please describe.
Mostly convenience, to avoid the workaround described above.

### Describe the solution you'd like
It would be great to have the saturated likelihood available for everyone in the public API. Alternatively, how can I calculate it? I suspect the main question is which constant terms to take into account to be able to compare with other likelihoods (somewhat related: #764).

### Describe alternatives you've considered
Workaround as described above.

# Relevant Issues and Pull Requests
#764

# Additional context
none

**Comment by lukasheinrich** [comment]
would this be equivalent

```
import pyhf
m = pyhf.simplemodels.hepdata_like([5],[50],[7])
d = [50] + m.config.auxdata

main,aux = m.fullpdf_tv.split(pyhf.tensorlib.astensor(d))
pyhf.tensorlib.poisson_dist(main).log_prob(main) + m.constraint_logpdf(aux,pyhf.tensorlib.astensor(m.config.suggested_init()))
```

i.e. `pois(data|lambda = data) * constraint_terms()`

**Comment by alexander-held** [comment]
Thanks @lukasheinrich! This seems to work well for this single bin example, but I am not sure how to generalize it. For two bins, I get different results (the spec adds shapefactors and a second bin to your example).

```python
import pyhf

spec = {
    "channels": [
        {
            "name": "singlechannel",
            "samples": [
                {
                    "name": "signal",
                    "data": [5, 4],
                    "modifiers": [
                        {"name": "mu", "type": "normfactor", "data": None},
                        {"name": "sf", "type": "shapefactor", "data": None},
                    ],
                },
                {
                    "name": "background",
                    "data": [50, 40],
                    "modifiers": [
                        {"name": "uncorr_bkguncrt", "type": "shapesys", "data": [7, 6]},
                        {"name": "sf", "type": "shapefactor", "data": None},
                    ],
                },
            ],
        }
    ],
    "version": "1.0.0",
    "measurements": [
        {
            "name": "measurement",
            "config": {
                "poi": "mu",
                "parameters": [],
            },
        }
    ],
    "observations": [{"name": "singlechannel", "data": [50, 40]}],
}

ws = pyhf.Workspace(spec)
m = ws.model()
d = ws.data(m)

main, aux = m.fullpdf_tv.split(pyhf.tensorlib.astensor(d))
res = sum(
    pyhf.tensorlib.poisson_dist(main).log_prob(main)
    + m.constraint_logpdf(aux, pyhf.tensorlib.astensor(m.config.suggested_init()))
)
print(-2 * res)

res = pyhf.infer.mle.fit(d, m, return_result_obj=True)
print(res[1].fun)
```

**Comment by alexander-held** [comment]
It's great to see that the calculation of the terms is this clean. Feel free to close this issue, the implementation works correctly for all my test cases.

**Comment by lukasheinrich** [comment]
great!
