### ISSUE TITLE
Expand test for parameter uncertainties

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/pyhf#1193]
# Question

I was looking through #1183 and noticed that there does not seem to be a test to check the values of parameter uncertainties returned by minuit, which I would expect to be done here: https://github.com/scikit-hep/pyhf/blob/a33baddf6620df371338c6d1b98fdbab1b9da5c4/tests/test_optim.py#L384-L408

I am happy to prepare a PR to add such a test, but wanted to check first whether this is of interest. I noticed it since that PR adds a HESSE call, which should slightly change the reported uncertainties, but did not find a corresponding change in the test.

# Relevant Issues and Pull Requests

#1183

**Comment by lukasheinrich** [comment]
I think more test coverage is always better. this way we can keep track when things change

**Comment by matthewfeickert** [comment]
@alexander-held Yeah I'll second that. A PR is very welcome.
