### ISSUE TITLE
Compatibility with Windows / testing Windows in CI

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/pyhf#1204]
# Question

Currently `pyhf` runs tests in the CI [on Ubuntu and Mac OS](https://github.com/scikit-hep/pyhf/blob/62466c300e07fdc6ec42c3b90317656e8deac4a5/.github/workflows/ci.yml#L17). What do you think about adding Windows as well? An example is [here](https://github.com/scikit-hep/uproot4/blob/152c736661e910ffea73577d02ab3d8887600ce5/.github/workflows/build-test.yml#L13). I have not tried running `pyhf` under Windows, and am not aware whether any code changes would be required for that.

# Relevant Issues and Pull Requests

none

**Comment by matthewfeickert** [comment]
As [PyTorch doesn't support Windows at the moment](https://pypi.org/project/torch/#files) I don't think this is going to happen in the foreseeable future.

**Comment by matthewfeickert** [comment]
Okay, I'll amend that to mention that [the PyTorch webpage mentions](https://pytorch.org/get-started/locally/):

> Installing on Windows
> PyTorch can be installed and used on various Windows distributions. Depending on your system and compute requirements, your experience with PyTorch on Windows may vary in terms of processing time. 

and to try using

```
python -m pip install torch==1.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
```

but that means that there is no PyPI support. I'll be happy to be proven wrong on this and that it is really easy to do, but I think that unless someone contributes a PR that doesn't make the CI YAML super awful to look at I'll leave this closed.

@mickypaganini please feel free to correct me here if `torch` on Windows is actually trivial and I'm missing something. :)

**Comment by matthewfeickert** [comment]
Having given this a go with

```diff
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index 315997a8..1fccd990 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,13 +14,17 @@ jobs:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [ubuntu-latest, macos-latest]
+        os: [ubuntu-latest, macos-latest, windows-latest]
         python-version: [3.6, 3.7, 3.8]
         exclude:
           - os: macos-latest
             python-version: 3.6
           - os: macos-latest
             python-version: 3.7
+          - os: windows-latest
+            python-version: 3.6
+          - os: windows-latest
+            python-version: 3.7
 
     steps:
     - uses: actions/checkout@v2
@@ -29,10 +33,17 @@ jobs:
       with:
         python-version: ${{ matrix.python-version }}
     - name: Install dependencies
+      if: matrix.os != 'windows-latest'
       run: |
         python -m pip install --upgrade pip setuptools wheel
         python -m pip install --ignore-installed -U -q --no-cache-dir -e .[test]
         python -m pip list
+    - name: Install dependencies Windows
+      if: matrix.os == 'windows-latest'
+      run: |
+        python -m pip install --upgrade pip setuptools wheel
+        python -m pip install --ignore-installed -U -q --no-cache-dir  --find-links https://download.pytorch.org/whl/torch_stable.html -e .[test]
+        python -m pip list
     - name: Test with pytest
       run: |
         python -m pytest -r sx --ignore tests/benchmarks/ --ignore tests/contrib --ignore tests/test_notebooks.p
```

It seems that things are still going to be complicated given that `pip` gives

```pytb
ERROR: Could not find a version that satisfies the requirement jaxlib~=0.1.56; extra == "test" (from pyhf[test])
ERROR: No matching distribution found for jaxlib~=0.1.56; extra == "test"
```

which makes sense given [the following comment](https://github.com/google/jax/issues/438#issuecomment-466646020)

> JAX doesn’t support Windows right now, though it may be that the only thing standing in our way is getting the build to work. If Tensorflow can be built with XLA on Windows, then it should be possible to build JAX too, with some revisions to our own build scripts to fix issues like this.
>
> Getting JAX on Windows is out of scope for us for now, just because we need to prioritize other kinds of progress. But contributions are welcome!

Though later on it is seen that [this is being worked on by contributors](https://github.com/google/jax/issues/438#issuecomment-730487317).

I think I'll leave this closed but mark it as `help-wanted` as a contributor PR for the future.

**Comment by matthewfeickert** [comment]
This is effectivley fixed now that all the backends support Windows for Python 3.9+ and with PR #2357 and PR #2363.
