### ISSUE TITLE
Add .to_numpy() API to tensorlib

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1225]
It would be beneficial to add a ~`.numpy()`~ `.to_numpy()` API to all the tensor backends to make the transition needed for PR #1208 easier:

>> Indeed, torch.Tensor does **not** register as a Sequence. `isinstance(some_tensor, collections.abc.Sequence)` is False. The sequence protocol is required by pybind11. Now, there are three ways to fix this.
>> 
>> * in iminuit: I make a custom caster that also accepts torch.Tensor or rather everything that supports the buffer protocol.
>> * in pybind11: you could argue that their caster does not try hard enough (there are collections which are not sequences and which can still be converted to `std::vector`)
>> * in pyhf: you could convert the tensor to a numpy array in your gradient function wrapper.
>
>Thanks for this diagnosis @HDembinski. I think we should avoid you doing any extra work if possible and I _believe_ that we can just case to NumPy here without any issue. I'll let you know if we end up running into additional issues, but I'll work on implementing the
>
>> * in pyhf: you could convert the tensor to a numpy array in your gradient function wrapper.
>
>option.

_Originally posted by @matthewfeickert in https://github.com/scikit-hep/pyhf/issues/1208#issuecomment-744729277_

**Comment by matthewfeickert** [comment]
We should probably use an API of .`to_numpy()` rather than `.numpy()` as this is being called from tensorlib and the grammar seems to make more sense this way. c.f. [Awkward's API.](https://awkward-array.readthedocs.io/en/latest/_auto/ak.to_numpy.html)

**Comment by HDembinski** [comment]
`tonumpy` seems to be consistent with other `tosomething` methods

**Comment by HDembinski** [comment]
Ah nevermind, that seems to be a numpy thing.

**Comment by matthewfeickert** [comment]
> Ah nevermind, that seems to be a numpy thing.

Yeah, this difference between things that NumPy did back in the day and what most libraries do now continues to plague us.
