### ISSUE TITLE
Add commas around constrained maximal likelihood in docstring for clarity

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1234]
# Description

In PR #905 the docstring for [`pyhf.infer.mle.fixed_poi_fit`](https://scikit-hep.org/pyhf/_generated/pyhf.infer.mle.fixed_poi_fit.html) was amended, but the lines

https://github.com/scikit-hep/pyhf/blob/fd7930cce36cbc3a2d0ee1828f060d7382129579/src/pyhf/infer/mle.py#L134-L135

are missing commas around the likelihood, making it difficult to read

![missing_commas](https://user-images.githubusercontent.com/5142394/102830397-d9a87b00-43ae-11eb-8acc-502370cf9353.png)

It should read

```
,:math:`L\left(\mu, \hat{\hat{\boldsymbol{\theta}}}\right)`, in the profile 
```

**Comment by 1nF0rmed** [comment]
I would like to work on this
