### ISSUE TITLE
Use sphinx-build or other tools over setuptools for building docs

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1256]
With regards to changing building the docs with `setuptools`

https://github.com/scikit-hep/pyhf/blob/1f152585232b919075189ea80eb42d531347609c/.github/workflows/docs.yml#L46

to using something like

```bash
pushd docs
make html
popd
```

@kratsg had pointed out that Sphinx does have defined tooling for using `setuptools`, so the change might not be needed

> Still not sure why we want to change to explicitly using `make html`. https://www.sphinx-doc.org/en/master/usage/advanced/setuptools.html seems to be supported more nicely  -- so I'm not sure.

I could be wrong, and will need to go hunting for references that support this idea, that using `setuptools` to do anything explicitly is more and more being looked at as "bad" by the Python community and that APIs through more dedicated tooling is preferred. 

Off the top of my head I'm thinking of https://github.com/tox-dev/tox/issues/1100 as being a starting place for some of these discussions.

I have been wanting to move away from using `setuptools` for a while, and I would normally suggest using [`sphinx-build` directly](https://www.sphinx-doc.org/en/1.8/man/sphinx-build.html) but 

https://github.com/scikit-hep/pyhf/blob/1f152585232b919075189ea80eb42d531347609c/docs/Makefile#L4-L9
https://github.com/scikit-hep/pyhf/blob/1f152585232b919075189ea80eb42d531347609c/docs/Makefile#L54-L58

are just using `sphinx-build` anyway.

Maybe @henryiii has additional thoughts here as well.

_Originally posted by @matthewfeickert in https://github.com/scikit-hep/pyhf/pull/1221#discussion_r557032023_

**Comment by henryiii** [comment]
Yes, you should not be using `python setup.py <command>`. It was possible to extend it (pytest had it too as a plugin, but [deprecated it](https://pypi.org/project/pytest-runner/)). In general, the `setup.py` file isn't even required anymore (though if you remove it then `pip install -e .` will not work, due to the fact PEP 517 doesn't have editable installs yet). Tests are easy (you should run pytest), though docs are a little harder to pin down as a "correct" way to run it. Though `make html` is what readthedocs runs by default, right?

**Comment by matthewfeickert** [comment]
Thanks for the speedy follow up, @henryiii. :pray: 

> Yes, you should not be using `python setup.py <command>`. 
> ...
>Tests are easy (you should run pytest), though docs are a little harder to pin down as a "correct" way to run it. Though `make html` is what readthedocs runs by default, right?

Pretty similar, as [their docs mention](https://docs.readthedocs.io/en/stable/builds.html)

> When we build your Sphinx documentation, we run `sphinx-build -b <format> . _build/<format>`. We also create pdf’s and ePub’s automatically based on your project.

which is the first line of all the Make targets:

https://github.com/scikit-hep/pyhf/blob/1f152585232b919075189ea80eb42d531347609c/docs/Makefile#L54-L58

and we have the pdf’s and ePub’s enabled as well

https://github.com/scikit-hep/pyhf/blob/fd8fdf3c280604c173f6229837baab3616abe8c3/.readthedocs.yml#L13-L14
