### ISSUE TITLE
Auto scan for hypothesis test inversion (Implemented)

### ISSUE THREAD

**Issue by beojan** [scikit-hep/pyhf#1265]
# Description

An auto scan feature for hypothesis test inversion can provide faster and more precise upper limits. One good way I've found to do this is to use the [TOMS748](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.toms748.html#scipy.optimize.toms748) root finding algorithm.

### Describe the solution you'd like
An `upperlimit_auto` (or some other appropriate name) function that runs an auto scan instead of a linear scan.

### Implementation
An implementation is below. I can make a PR including this in `pyhf.infer.intevals` if this issue has support.

```python
from scipy.optimize import toms748 as _toms748

def upperlimit_auto(data, model, low, high, level=0.05, atol=2e-12, rtol=1e-15):
    """
    Calculate an upper limit interval ``(0, poi_up)`` for a single
    Parameter of Interest (POI) using an automatic scan through
    POI-space, using the TOMS748 algorithm.
    
    ..., mostly copied from upperlimit docstring.
    """

    def f_all(mu):
        return hypotest(mu, data, model, test_stat="qtilde", return_expected_set=True)

    def f(mu, limit=0):
        # Use integers for limit so we don't need a string comparison
        if limit == 0:
            # Obs
            return f_all(mu)[0] - level
        else:
            # Exp
            # (These are in the order -2, -1, 0, 1, 2 sigma)
            return f_all(mu)[1][limit - 1] - level

    tb, _ = get_backend()
    obs = tb.astensor(_toms748(f, low, high, args=(0), k=2, xtol=atol, rtol=rtol))
    exp = [
        tb.astensor(_toms748(f, low, high, args=(i), k=2, xtol=atol, rtol=rtol))
        for i in range(1, 6)
    ]
    return obs, exp
```

**Comment by kratsg** [comment]
There is a brent-bracketing implementation by @alexander-held in `cabinetry` (https://github.com/alexander-held/cabinetry/blob/c85f404bc0bdedd3bb2629c826de385b694d99fc/src/cabinetry/fit.py#L589) that does a non-linear limit finding. If this is something people want to see upstreamed, we could.

**Comment by lukasheinrich** [comment]
It would be ince to find a way to be able to inject algorithms that can perform scans without taking them on fully (maybe ismilar to the work on toy calculator API)..  scikit optimize has the ask/tell API

https://scikit-optimize.github.io/stable/auto_examples/ask-and-tell.html

probably would fit into `pyhf.infer.intervals`

**Comment by lukasheinrich** [comment]
I think for future-proofing it would be good if this returns "intervals" and  not only try to do a root-finding.. i.e. the implicit assumption is often that the itnerval is [0,root] annd this should be made explicit

**Comment by beojan** [comment]
I think it would be really helpful to have an auto scan in pyhf itself for those who don't use Cabinetry, particularly since a linear scan _is_ available.

> It would be ince to find a way to be able to inject algorithms that can perform scans without taking them on fully

I can easily extend the implementation I posted here to allow the user to change the root-finding function used (assuming it uses the bracketing API shared by the `scipy.optimize` bracketing root-finders). That said, I think TOMS748 is usually the optimal choice (and [known to be better than Brent's method](https://www.boost.org/doc/libs/1_75_0/libs/math/doc/html/math_toolkit/roots_noderiv/brent.html)), so I do think it should be the default.

> I think for future-proofing it would be good if this returns "intervals" and not only try to do a root-finding

The `upperlimit_auto` function could certainly return `(0, upper_lim)` for each of the observed and expected limits. Above, I just copied the format that the linear scan returns, which is also why I wrapped each limit in a tensor.

**Comment by alexander-held** [comment]
Hi, providing this functionality through `pyhf.infer` sounds like a good idea to me. I have a few ideas and suggestions based on my experience with the `cabinetry` implementation:
- Caching is useful, the above algorithm will repeat fits for upper/lower bracket mu values for every root finding (obs + 5x for exp, resulting in at least 10 repeated `infer.hypotest` calls).
- The starting bracket for subsequent limits (e.g. the exp limits after having calculated obs limits) can be optimized given information about CLs(mu) obtained from the previous steps.
- In a test case, the algorithm repeatedly queries the same mu for a single root finding step, example below. I am not sure what causes this, `brentq` does not show the same behavior (thank you for the pointer to `toms748`, will try that out in more detail!).
```
testing mu=0
testing mu=10
testing mu=9.497575427630334
testing mu=6.715660956538139
testing mu=6.715660956538139
testing mu=6.04083915699075
testing mu=3.020419578495375
testing mu=2.633299000060376
testing mu=2.633299000060376
testing mu=2.43394097830554
testing mu=1.21697048915277
testing mu=1.7419775663353678
testing mu=2.0585075562095017
testing mu=1.9611870482306077
```

In the longer term, I believe that an implementation which uses knowledge about the functional form of CLs(mu) under asymptotic assumptions can likely be significantly more efficient than pure root finding. An implementation of such a function-aware limit finding algorithm seems very useful when using `pyhf` to calculate limits with complex workspaces where each fit takes a non-negligible amount of time (there is a script in used internally in ATLAS that is very efficient in my experience).

**Comment by beojan** [comment]
> Caching is useful, the above algorithm will repeat fits for upper/lower bracket mu values for every root finding (obs + 5x for exp, resulting in at least 10 repeated infer.hypotest calls).

I figured that would be the case. My test implementation actually has an `@lru_cache` decorator on `f_all` but I removed it for the snippet above to remove an import. Given your third point, it does seem to be useful to add that back in.

> The starting bracket for subsequent limits (e.g. the exp limits after having calculated obs limits) can be optimized given information about CLs(mu) obtained from the previous steps.

Agreed. This isn't possible using `lru_cache`, but having tried with a manually implemented cache, it does seem to improve things.

> In a test case, the algorithm repeatedly queries the same mu for a single root finding step

I see this too. I think it's a feature of the root finding algorithm. With memoization enabled it doesn't have much impact though.

> In the longer term, I believe that an implementation which uses knowledge about the functional form of CLs(mu) under asymptotic assumptions can likely be significantly more efficient than pure root finding.

This is true, but I don't think a root finding auto scan should be left out because we're waiting for a more direct / analytical implementation of limit setting. The root finding technique is also more general and can be used with a toy-based hypothesis test implementation.

The ATLAS script you refer to does use root finding (I think it uses the secant method), it's efficiency stems from a clever choice of starting value which means you don't need many iterations of the root finding algorithm.

**Comment by alexander-held** [comment]
> I don't think a root finding auto scan should be left out because we're waiting for a more direct / analytical implementation of limit setting

I agree and would view the different implementations as complementary.

> The ATLAS script you refer to does use root finding (I think it uses the secant method), it's efficiency stems from a clever choice of starting value which means you don't need many iterations of the root finding algorithm.

Thanks for the details, I will have to take a closer look at this implementation.

**Comment by beojan** [comment]
I've opened a PR with the implementation I have. I included the suggestions @alexander-held made, but otherwise I stuck to the same return format as the linear scan so that anyone using the linear scan can move over easily.
