### ISSUE TITLE
Make default docs link point to latest stable release on ReadTheDocs

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1286]
# Description

We have enough users and enough versions out that we should prioritize having the docs be versioned cleanly along with the releases. At the moment our docs links point to the docs build from `master` but we should probably have the default view of the docs correspond to the latest stable release on PyPI &mdash; so at the time of writing that would be the `v0.5.4` API.

We already have versioned docs on ReadTheDocs, so that might just mean adding a link to the README of https://pyhf.readthedocs.io/

[![RTD_docs_versioned](https://user-images.githubusercontent.com/5142394/106814195-a60c7200-6637-11eb-9fa2-f57c441ad79d.png)](https://pyhf.readthedocs.io/)

(Note: This has the [`v0.6.0`](https://github.com/scikit-hep/pyhf/projects/10) label so that this will go in and get picked up for the upcoming PyPI release.)

**Comment by matthewfeickert** [comment]
I'm not sure if @jpivarski and @henryiii have any ideas or suggestions on the best way for redirect of https://scikit-hep.org/pyhf/ (I also need to reducate myself on how and where this happens).

Also looking at @henryiii's projects it seems that just https://pyhf.readthedocs.io/ is sufficient as it will resolve to `latest` by default.

**Comment by kratsg** [comment]
Yeah, so one annoying thing is that we've got it set up on RTD to always build latest tags -- but scikit-hep is built from master. We could think about how to improve this more -- but versioning isn't so easy with gh-pages -- so the current way we have it makes sense.. and we should... ... i'm not sure. scikit-hep should just have a banner at top saying "latest dev! for latest release, see <link>"

**Comment by matthewfeickert** [comment]
> We could think about how to improve this more -- but versioning isn't so easy with gh-pages

Exactly. I think if it was easy to do most projects would self host their versioned docs, but it is hard and so everyone uses RTD. I agree that I _want_ to keep things on our gh-pages, but I think the need of having versioned docs for users needs to go first and then we can always figure out ways to change it up later. But I think we **need** a badge on README that is like [![RTD latest](https://img.shields.io/badge/docs-latest-blue.svg)](https://pyhf.readthedocs.io/en/latest/)


> scikit-hep should just have a banner at top saying "latest dev! for latest release, see "

@kratsg I like this idea...but how do we implement this without having this eventually end up with RTD versions saying "latest dev"? Sorry if I'm missing the obvious.

**Comment by kratsg** [comment]
https://sphinx-version-warning.readthedocs.io/en/latest/

Not sure what flask does tho.

**Comment by kratsg** [comment]
<img width="1713" alt="Screen Shot 2021-02-03 at 7 28 23 PM" src="https://user-images.githubusercontent.com/761483/106826992-04e0e400-6656-11eb-8ba7-f385314b4b5d.png">

basically got something working with CSS+ JS
