### ISSUE TITLE
Uncertainties on pulls

### ISSUE THREAD

**Issue by annmwang** [scikit-hep/pyhf#1301]
# Question

Is there a way to get the uncertainties on the pulls? I followed the example here:

https://github.com/scikit-hep/pyhf/blob/master/docs/examples/notebooks/pullplot.ipynb

but I think the option "return_uncertainties" is no longer accepted for the function `pyhf.infer.mle.fit`. I get the error

`pyhf.exceptions.Unsupported: Unsupported options were passed in: ['return_uncertainties'].
`

I'm using pyhf version 0.5.4 and the numpy/scipy backend/optimizer. 

Thanks so much!

# Relevant Issues and Pull Requests

I found the notebook through: https://github.com/scikit-hep/pyhf/issues/630

**Comment by kratsg** [comment]
Use the `minuit` optimizer

```python
pyhf.set_backend('numpy', 'minuit')
```

which returns uncertainties. You'll see in the notebook that this uses the minuit optimizer

```python
    pyhf.set_backend("numpy", pyhf.optimize.minuit_optimizer(verbose=True))
```

**Comment by annmwang** [comment]
ah ok, thanks for the quick answer! 

so there's no way to do this with the scipy optimizer?

**Comment by matthewfeickert** [comment]
> so there's no way to do this with the scipy optimizer?

Correct. In HEP we have a goal of ascribing uncertainties to our minimizations, but this is not a shared universal goal in the task of minimization ([c.f. this Twitter thread](https://twitter.com/betatim/status/1030125781857566720?s=20) where @betatim first explained this to me). As as result, please use minuit in these circumstances.

**Comment by matthewfeickert** [comment]
@annmwang Also maybe of interest to you, in `pyhf` `v0.6.0` you'll have access to `iminuit`'s correlations matrix the thanks to @kratsg in PR #998.

**Comment by annmwang** [comment]
Interesting... thanks for the help- I will switch to minuit then. Thanks for the pointer to the correlations matrix too!
