### ISSUE TITLE
docs: Investiage revising author field styling in Zenodo citation

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1321]
# Description

The current Zendo citation of 

https://github.com/scikit-hep/pyhf/blob/3f0c8fc26d13bf2c7740bd2465bc10bbcd5f7746/src/pyhf/data/citation.bib#L1-L7

quotes the author field which can make some BibTeX style files force it to render in a way that is perhaps not desirable

![current_render](https://user-images.githubusercontent.com/5142394/108158122-e513dc00-70a9-11eb-8ad1-cafacccb19e5.png)

However, if the author field is given to BibTeX with more flexibility (using `and`s and without quotes)

```bibtex
@software{pyhf,
  author = {Lukas Heinrich and Matthew Feickert and Giordon Stark},
  title = "{pyhf: v0.6.0}",
  version = {0.6.0},
  doi = {10.5281/zenodo.1169739},
  url = {https://github.com/scikit-hep/pyhf},
}
```

the render can be improved

![alt_render](https://user-images.githubusercontent.com/5142394/108158152-f230cb00-70a9-11eb-88ee-e120c672063d.png)

Thoughts on style here @lukasheinrich @kratsg?

**Comment by kratsg** [comment]
I like the shorter version better, indeed.
