### ISSUE TITLE
Make test statistic configurable in infer.upperlimit

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1326]
# Description

Currently in `infer.upperlimit` there is no way to configure the test statistic used

https://github.com/scikit-hep/pyhf/blob/aab6953d716daeaf1e1660bed35e5b7dc0363580/src/pyhf/infer/intervals.py#L12

and it is currently configured to only support the alternative test stat

https://github.com/scikit-hep/pyhf/blob/aab6953d716daeaf1e1660bed35e5b7dc0363580/src/pyhf/infer/intervals.py#L52-L55

We should keep the `qtilde` as a default, but we should add a `test_stat` kwarg.

**Comment by aryan26roy** [comment]
@matthewfeickert do you mind if I help out with this? Seems easy enough to me.

**Comment by matthewfeickert** [comment]
> do you mind if I help out with this? Seems easy enough to me.

Go for it. :)

**Comment by aryan26roy** [comment]
@matthewfeickert I added the kwargs in my fork and the test has passed, do you want me to add a test specifically with some other option for test_stat?

**Comment by matthewfeickert** [comment]
> do you want me to add a test specifically with some other option for test_stat?

Yeah tests would be good to explicitly hit this. Thanks!
