### ISSUE TITLE
Harmonize docstring for test_stat between AsymptoticCalculator and ToyCalculator

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1335]
# Description

In `v0.6.0` docs, the `AsymptoticCalculator` API has a [nicely formatted docstring for the `test_stat` arg](https://pyhf.readthedocs.io/en/v0.6.0/_generated/pyhf.infer.calculators.AsymptoticCalculator.html)

https://github.com/scikit-hep/pyhf/blob/8de7566a2b6dc4a5278e0b0da9c0a45a2e5a752d/src/pyhf/infer/calculators.py#L199-L208

but the [`ToyCalculator`](https://pyhf.readthedocs.io/en/v0.6.0/_generated/pyhf.infer.calculators.ToyCalculator.html) API didn't have these changes applied to them (seems @matthewfeickert forgot to propagate these in PR #993)

https://github.com/scikit-hep/pyhf/blob/8de7566a2b6dc4a5278e0b0da9c0a45a2e5a752d/src/pyhf/infer/calculators.py#L625-L632

The `ToyCalculator` docstring should be updated to match.

**Comment by kratsg** [comment]
Similarly, need to update the warning for `qmu` to be using `qmu_tilde` with the more appropriate suggestion.

**Comment by Saransh-cpp** [comment]
@matthewfeickert can I take this up? @kratsg could you please elaborate a bit more on the warning updates?

**Comment by Saransh-cpp** [comment]
@matthewfeickert @kratsg not to disturb you again, but any updates on this?

**Comment by kratsg** [comment]
The warning updates were already done. As for documentation, why not just submit the PR? But unless you know the statistics content, we'd recommend not just rewriting without knowing what the content itself is.

**Comment by matthewfeickert** [comment]
> But unless you know the statistics content, we'd recommend not just rewriting without knowing what the content itself is.

Yeah, I was envisioning a small rewrite of this when I opened the Issue. My advice would be to only work on a PR for this if you feel comfortable with the frequentist statistics being discussed, else we'll probably have to request multiple revisions.

**Comment by Saransh-cpp** [comment]
Oh oh, my bad, I thought this required only formatting of the documentation. Thanks for letting me know!
