### ISSUE TITLE
Splitting data for a model into main and aux data

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/pyhf#1371]
# Question

Is there a recommended way to split data (main + aux) into the "main" part (yields per bin) and auxiliary?

Given a `model: pyhf.pdf.Model` and `data: List[float]` (e.g. from `workspace.data(model)`), the following works as long as there is at least a single aux parameter (I do not remember from where I picked this up, but I believe it was a suggestion):
```python
main_data, aux_data = model.fullpdf_tv.split(pyhf.tensorlib.astensor(data))
```
With no aux parameters, this fails since a list of length 1 is returned. I could instead split like this
```python
main_data = data[:model.config.nmaindata]
aux_data = data[model.config.nmaindata:]
```
which would return `[]` when `model.config.nauxdata` is zero.

Do you see any possible issue with this second approach? Looking at https://github.com/scikit-hep/pyhf/blob/f380fddf331c89030384e7949c76099e9277693a/src/pyhf/probability.py#L281-L283 I doubt that changing the `.split()` behavior would make sense for the API.

# Relevant Issues and Pull Requests

none I am aware of

**Comment by lukasheinrich** [comment]
Hm, I would have thought that would have worked as this works

```
>>> from pyhf.tensor.common import _TensorViewer
>>> import numpy as np
>>> tv = _TensorViewer([[0,1],[]])
>>> tv.split(np.array([5,6]))
[array([5, 6]), array([], dtype=int64)]
```

can you check  what ctor args `model.fullpdf_tv` is initialized with?

**Comment by alexander-held** [comment]
It uses `sizes=[n]` where `n` is # of main data, since https://github.com/scikit-hep/pyhf/blob/f380fddf331c89030384e7949c76099e9277693a/src/pyhf/pdf.py#L585-L586 is `False` and skipped.

**Comment by lukasheinrich** [comment]
hm so this should work? 

```
main_data, aux_data = model.fullpdf_tv.split(data) if model.config.nauxdata else data, pyhf.tensorlib.astensor([])
```

if so, is this sufficient or would a proper API call be bettter?

**Comment by lukasheinrich** [comment]
alternatively `model.fullpdf_tv.split(data)` should *always* work but either return a length-1 or length-2 tuple

so 

```
main_data, *rest = model.fullpdf_tv.split(data)
aux = rest[0] if rest else pyhf.tensorlib.astensor([])
```

**Comment by alexander-held** [comment]
This is fine, happy to use an approach like this. If this kind of split is commonly needed it might be useful to have something in the API for it, but I suspect it is a rare thing to use. `model.fullpdf_tv.split(data)` indeed always works, just need to handle the length-1 case accordingly.

**Comment by lukasheinrich** [comment]
ok, i'll close this then for now, but feel free to reopen if it becomes annoying (I do think this will be rare in real-life scenarios)
