### ISSUE TITLE
workspaces with fixed poi fail in hypotest (of course)

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/pyhf#1391]
# Description

some workspaces (like the one @elskorda provided) have a *fixed* POI in the workspace definition - if you naively put that through `pyhf cls` of course the fit doesn't really do anythinig useful.

options

* in readxml warn that POI is fixed
* in hypotest ensurer to un-fix POI
* others?

the least we could do is throw a warning  in the places where an unconstrained fit iss expected but a fixed POI is observed

**Comment by alexander-held** [comment]
`hypotest` seems like a good place for a warning, maybe even error. With the POI fixed, the result cannot really be meaningful. As a step towards multi-POI support, it might also be useful to have an option to override the POI from the CLI.
