### ISSUE TITLE
Uniform default precision for all backends?

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1398]
# Question

As seen [in the example](https://pyhf.readthedocs.io/en/v0.6.1/_generated/pyhf.set_backend.html) for `pyhf.set_backend` the default precision for the `numpy` backend is `64b` while the default precision for TensorFlow and PyTorch is `32b`. 

https://github.com/scikit-hep/pyhf/blob/98bb222d9c45ad13335ab5423d866e3a1508c329/src/pyhf/tensor/numpy_backend.py#L44

https://github.com/scikit-hep/pyhf/blob/98bb222d9c45ad13335ab5423d866e3a1508c329/src/pyhf/tensor/jax_backend.py#L58

https://github.com/scikit-hep/pyhf/blob/98bb222d9c45ad13335ab5423d866e3a1508c329/src/pyhf/tensor/tensorflow_backend.py#L16

https://github.com/scikit-hep/pyhf/blob/98bb222d9c45ad13335ab5423d866e3a1508c329/src/pyhf/tensor/pytorch_backend.py#L18

Given that there are known differences between `64b` and `32b` it is probably worth reconsidering / discussing if we should have a default precision of `64b` for all backends. My guess is that it is non-intuitive that switching from NumPy to Torch changes the precision.

This is somewhat related to Issue #981 and was put back into my mind by @dguest and @nhartman94 (c.f. Discussion #1397) (comments welcome from them both).

**Comment by matthewfeickert** [comment]
If @lukasheinrich and @kratsg agree here I have a branch with the changes ready for a PR (after PR #1399 goes in).

**Comment by lukasheinrich** [comment]
yeah I agree!

**Comment by kratsg** [comment]
I agree. I think we had 32b at first since that was nominally the primary support when we first started with these backends. I see no reason why we shouldn't harmonize the defaults.

**Comment by matthewfeickert** [comment]
> I agree. I think we had 32b at first since that was nominally the primary support when we first started with these backends.

Yeah this was [my memory too](https://github.com/scikit-hep/pyhf/discussions/1397#discussioncomment-571343).
