### ISSUE TITLE
Update citation information for "Charged lepton flavor violation at the EIC"

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1401]
# Description

There should be a [new INSPIRE reference](https://inspirehep.net/literature/1846026) for 

https://github.com/scikit-hep/pyhf/blob/3fc80a819cc7bdeb89d6b702313588d0342392db/docs/bib/use_citations.bib#L14-L25

now that the [paper has been published in JHEP](https://github.com/scikit-hep/pyhf/blob/3fc80a819cc7bdeb89d6b702313588d0342392db/docs/bib/use_citations.bib#L14-L25) (giving `pyhf` its [first citation that shows up on INSPIRE](https://inspirehep.net/literature/1845084)).

**Comment by Saransh-cpp** [comment]
Hi @matthewfeickert, does this require replacing the existing citation of the paper "Charged Lepton Flavor Violation at the EIC" or should the new citation be appended in the file at the bottom?

**Comment by kratsg** [comment]
Just replacing the existing citation.
