### ISSUE TITLE
Use module level __dir__ for cleaner REPL import completion

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1402]
# Description

Stealing this from @henryiii who found it from Brett Cannon's blog [An approach to lazy importing in Python 3.7](https://snarky.ca/lazy-importing-in-python-3-7/) and implemented it for `hist` in https://github.com/scikit-hep/hist/pull/179:

> I’ve used Python 3.7 module-level `__getattr__` for a while now to allow mistyping hist.axis import as hist.axes to show a warning but work anyway. However, I completely missed a fantastic usage for Python 3.7 module-level `__dir__ `: you can “fix” IPython’s tab completion to just show the items in `__all__`! Wow! One of the main things that bugged me about importing and defining unrelated things in modules, and one reason that boost-histogram has an `_internal` module.

An example of before and after in IPython for Henry

**Before:**
<img width="941" alt="Before" src="https://user-images.githubusercontent.com/5142394/114104120-e97d9980-988f-11eb-95e2-9c7bbe628010.png">

**After:**
<img width="505" alt="After" src="https://user-images.githubusercontent.com/5142394/114104150-f39f9800-988f-11eb-8d1d-45830898f595.png">

**Comment by henryiii** [comment]
Not lazy importing as per the current title, it's module level `__dir__`.

**Comment by kratsg** [comment]
This is what #735 refers to FYI.
