### ISSUE TITLE
pyhf.infer.mle.fit does not support  "return_correlations" anymore ?

### ISSUE THREAD

**Issue by alasfar-lina** [scikit-hep/pyhf#1405]
I am trying to fit a likelihood with 2 poi's and I want to get the correlation between the 2 parameters. 
I am using "Minuit" backend and when I use 
pyhf.infer.mle.fit. function with return_correlations =true.
I get an error message 

pyhf.exceptions.Unsupported: Unsupported options were passed in: ['return_correlations'].

Though this option exists in inimuit API's

**Comment by matthewfeickert** [comment]
Hi @alasfar-lina Please fill out the bug issue template for us to help:

```
# Description

Describe your bug here

# Expected Behavior

Describe what you thought should have happened

# Actual Behavior

Describe what did happen

# Steps to Reproduce

Detail your environment and `pyhf.__version__` and the commands that you are executing to generate the bug. If you have a large program please make a [Gist](https://gist.github.com/) and link it here. Additionally attach any screen shots as needed.

# Checklist

- [ ] Run `git fetch` to get the most up to date version of `master`
- [ ] Searched through existing Issues to confirm this is not a duplicate issue
- [ ] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

```

**Comment by kratsg** [comment]
Note: this was something added in [v0.6.0](https://pyhf.readthedocs.io/en/v0.6.1/release-notes.html#id5) -- can you fill out the bug issue template that Matthew linked above? Thanks!

**Comment by matthewfeickert** [comment]
@alasfar-lina As we haven't heard back from you on this, then I'm going to assume you don't have a problem and we'll close this due to lack of activity. If you still have a problem we can reopen this Issue if you fill out the bug report template.
