### ISSUE TITLE
pyhf.optimize not introspectable with inspect.getsource et al.

### ISSUE THREAD

**Issue by lhenkelm** [scikit-hep/pyhf#1413]
# Description

Trying to use inspect (from the stdlib) to inspect the source of pyhf.optimize raises an AttributeError.

# Expected Behavior

The inspect functions should work and return the source code.

# Steps to Reproduce
With pyhf 0.6.1 and python 3.7.6:
```python
import pyhf
import inspect
# this works when you replace pyhf.optimize with sys.modules[type(pyhf.optimize).__module__]
for l in inspect.getsourcelines(pyhf.optimize)[0]: print(l) 
```

# Checklist

- [ ] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

NB: I am not sure how this relates to #735 and #1402 . Would using `def __getattr__(): <...>` fix this?

**Comment by matthewfeickert** [comment]
@lhenkelm Can you give a lot more context? Why do you need to do this?

**Comment by lhenkelm** [comment]
"need" is a  strong word :-)  . Here is the story: 
I was working interactively, and trying to figure out the knobs I could play with for optimizers.
So I do `help(pyhf.optimize)`:
```
Help on _OptimizerRetriever in module pyhf.optimize object:

class _OptimizerRetriever(builtins.object)
 |  Methods defined here:
 |  
 |  __getattr__(self, name)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
```
Which tells me nothing. But never fear, introspection is here: 
```python
import inspect
for l in inspect.getsourcelines(pyhf.optimize)[0]: print(l)
```
yielding
```
TypeError                                 Traceback (most recent call last)
<lots of traceback>
TypeError: module, class, method, function, traceback, frame, or code object was expected, got NoneType
```
Aha. Now putting on the hacker hat, I come up with
```python
import sys
actual_module = sys.modules[type(pyhf.optimize).__module__]
for l in inspect.getsourcelines(actual_module)[0]: print(l)
```
And finally get the source [not shown for clarity], but as you know,
the source of the Retriever is remarkably unhelpful in answering the question "what is a scipy_optimizer and what can I use it for". 
But at least its enough so I can guess the next import:
```python
import pyhf.optimize.opt_scipy
opt_scipy = sys.modules[type(pyhf.optimize).__module__ + '.opt_scipy']
help(opt_scipy.scipy_optimizer)
```
And finally I know my options. But I hope you agree the above is not a reasonable UX for "quickly referring to the interactive help in a dynamic language". Python is for consenting adults. If I am curious about your optimizer shim, its awkward to have to resort to hacking sys.modules. You may say "read the source on github". But `help` and `inspect` also compute stuff for me. E.g:  pyhf is very mixin-happy. So I might want to know "what is the exact MRO of the scipy_minimizer?" (or any other class) and then here I am.

Now all that said, I do think this should be a low priority at best, and maybe there is no clean fix that does not break a more important use case. But as it seems you are considering changing the implementation of the import hacks anyways, I thought this might be an aspect to consider.

**Comment by matthewfeickert** [comment]
I appreciate you going through these lengths, but I'd recommend not following these patterns in general.

> Which tells me nothing

The `_` tells you this isn't meant for the public API, which I think you already know. If it isn't in the public API then we aren't going to support specific use cases.

> You may say "read the source on github"

yes.

> So I might want to know "what is the exact MRO of the scipy_minimizer?

Read the docs or ask.

**Comment by matthewfeickert** [comment]
All that being said, if this is something that is really important to you and you don't want to read the docs then please read the `CONTRIBUTING.md` and open an Issue for a corresponding PR that you'd contribute.

Please don't try to parse library code though to make decisions in user code. This is a very bad idea.

**Comment by lukasheinrich** [comment]
Thanks for clarifyinig @lhenkelm. I think the better solution iis that we need to improve the docs to answer this questoin better

> I was working interactively, and trying to figure out the knobs I could play with for optimizers.

users shouldn't need to dig into the sourcecode to find out what options they have to run optimizers (either via `inspect` or via digging through github). We do try to be good w/ our docstrings but here iit seems the rertrieve code loses some of that.

**Comment by lukasheinrich** [comment]
@kratsg makes a good point that

`help(pyhf.optimizer)` should yield good help messages

![image](https://user-images.githubusercontent.com/2318083/115925731-eedb0680-a481-11eb-9262-1732b9c60728.png)

**Comment by matthewfeickert** [comment]
btw, in the even that I misunderstood what you wanted to do I think you maybe should be using

```python
>>> import pyhf
>>> help(pyhf.optimizer)
```

as a opposed to `pyhf.optimize`. This should be clear from the docs though: https://pyhf.readthedocs.io/en/v0.6.1/_generated/pyhf.optimize.mixins.OptimizerMixin.html

**Comment by matthewfeickert** [comment]
@lhenkelm My apologies for the overly curt replies on Friday &mdash; that wasn't helpful and definitely not encouraging behavior for you to have further interactions with the project or Scikit-HEP.

I also failed to say thanks for using `pyhf` in the first place. :) We do appreciate people adopting it into their workflows and even more the people who care enough about it to open Issues and discuss with us.

From the above replies, I think it is safe to say that in addition to checking the docs website that is generated from the codebase docstrings, we could probably do a better job in the public API of distinguishing between what is actually meant for the user. PR #1403 will help with this to some extent (as you already noted &mdash; thanks for also actually reading through Issues before opening this one :+1:) and revisions related to Issue #735 will allow us to further clean up the public API as well so that things like trying to understand the between `optimize` vs. `optimizer` hopefully won't be something users have to think about at all.

I'll leave this closed for now, as it will be linked in the Issues we just mentioned and this is more related to the `_OptimizerRetriever` class that users shouldn't need to interact with, but if there are additional things worth discussing here please let us know and we're more than happy to reopen.

**Comment by matthewfeickert** [comment]
@lhenkelm for the next release, https://github.com/scikit-hep/pyhf/pull/1403#issuecomment-829609894 demos how there is a (hopefully!) helpful reduction in the viewable public API from the REPL / notebooks. The full public API is still all there of course, but we now hide some things in the REPL that a user _probably_ doesn't actually want, making it a little bit cleaner and less cluttered.

**Comment by lhenkelm** [comment]
Hi @matthewfeickert, thanks for the heads up! This is a very nice improvement for interactive exploration of the API. In particular, I notice the REPL / notebook tab-completion will now suggest `pyhf.optimizer` when prompted with `pyhf.opt<+tab>` (or similar), which as you & @lukasheinrich  noted above, has a much more helpful documentation than `pyhg.optimize`.  

One thing I am now wondering about: would it make sense to foolproof the interactive help even more by putting in a reference to the useful names to interrogate using help(..)? I.e. a line in the `_OptimizerRetriever` docstring to the effect of "The currently used optimizer is documented at pyhf.optimizer. For optimization using the iminuit backend refer to pyhf.optimize.minuit_optimizer. (etc.)". 

The same references could go in the module docstring too, but then the `_OptimizerRetriever` would need to be replaced/extended to allow the module docstring to be found. That way I would get the same redirection when clicking through the online API docs (and the alternative optimizers would be listed by help automatically, so no need to keep track in a docstring). But I believe you had good reasons to use the retriever, so I don't want to ignorantly suggest scrapping it without understanding its purpose.
