### ISSUE TITLE
Use pip's Issue Template design to guide users towards the right forum

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1452]
# Description

TIL that `pip` has a super nice Issue template page

[![pip_Issue_templates](https://user-images.githubusercontent.com/5142394/118164502-cd1dd100-b3e8-11eb-9c41-db73da2ece53.png)](https://github.com/pypa/pip/issues/new/choose)

that uses a [`.github/ISSUE_TEMPLATE/config.yml`](https://github.com/pypa/pip/blob/e6414d6db6db37951988f6f2b11ec530ed0b191d/.github/ISSUE_TEMPLATE/config.yml) file to add the ability to have additional buttons (here Discourse and IRC) to guide user's reporting.

This seems like a _great_ idea that we should encorperate as well. It would seem to also be useful for basically all of the Scikit-HEP projects, especially those with Gitter channels. cc @eduardo-rodrigues @jpivarski @henryiii

**Comment by matthewfeickert** [comment]
The GitHub Docs for the "template chooser" are here: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

**Comment by matthewfeickert** [comment]
Also to the surprise of no none, this was added in to `pip` by our helpful friend @webknjaz. :) https://github.com/pypa/pip/pull/7630

**Comment by jpivarski** [comment]
I agree:

![image](https://user-images.githubusercontent.com/1852447/118166335-f8a1bb00-b3ea-11eb-855b-8167d2261e52.png)

**Comment by henryiii** [comment]
<img width="773" alt="Screen Shot 2021-05-13 at 2 04 33 PM" src="https://user-images.githubusercontent.com/4616906/118167011-335c2100-b3f4-11eb-8fd3-34d731b93060.png">

<img width="762" alt="Screen Shot 2021-05-13 at 2 04 09 PM" src="https://user-images.githubusercontent.com/4616906/118167022-35be7b00-b3f4-11eb-8405-57a89474372d.png">

**Comment by matthewfeickert** [comment]
@jpivarski @henryiii :rofl: Seems I'm behind the curve. Great that you're already both doing this! :)

**Comment by webknjaz** [comment]
You may also be interested in issue forms as demoed here https://github.com/ansible/ansible/issues/new/choose (needs a feature flag tho).

P.S. You know that you can have an org-wide fallback in special repo `ORG/.github`, right?

**Comment by webknjaz** [comment]
Dirs are merged but not files, if a file exists in the repo, it's fallback is not used.

**Comment by henryiii** [comment]
That's about what I'd expect. So I could add dependabot for everybody... 😈

We could provide a default "gitter" issue, maybe a default contributing, etc. It could even be a way to provide a default labeling bot via an action, perhaps?

**Comment by webknjaz** [comment]
The support for non-gh-builtin things varies per GH App / bot tho. So it'll not always work.

**Comment by matthewfeickert** [comment]
c.f. https://github.com/scikit-hep/awkward-1.0/pull/987 by @agoose77 for example of using YAML to create forms. 0_0! :rocket:

**Comment by webknjaz** [comment]
@matthewfeickert not sure if you saw but FYI also check out how Pradyun attempts to direct people to discussions while only allowing bug creation after that: https://github.com/pradyunsg/furo/issues/new/choose.

**Comment by matthewfeickert** [comment]
> not sure if you saw but FYI also check out how Pradyun attempts to direct people to discussions while only allowing bug creation after that: https://github.com/pradyunsg/furo/issues/new/choose.

This is pretty clever! I'll have to look more at how this is being used.
