### ISSUE TITLE
Logging configuration in contrib/utils

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/pyhf#1455]
# Question

`pyhf.contrib.utils` sets up logging:
https://github.com/scikit-hep/pyhf/blob/6b769fd6f5e1473deba2b4c55d49ebdb3db5b447/src/pyhf/contrib/utils.py#L9 

This interferes with custom logging users may want to set up. To achieve this now, they would have to do so before `from pyhf.contrib.utils import download`. To avoid this issue, the logging should not be configured in this part of the code (and only for the CLI).

# Relevant Issues and Pull Requests

#865

**Comment by lukasheinrich** [comment]
I would consider this a big.. logging shoulld only ever be setup in the "CLI" modules that serce as non-library entryopints. Thanks!
