### ISSUE TITLE
pyhf docker workflow (for pull requests) should run using base of target

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/pyhf#1462]
# Description

PRs submitted to `pyhf` from forks will always fail as they don't get access to the secrets. See https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/ for more information and we should use `pull_request_target` instead. This came up in #1460 which failed on the docker workflow as the fork does not have access to the secrets.

# Expected Behavior

Expect PR to pass checks.

# Actual Behavior

PR does not pass checks.

# Steps to Reproduce

Create fork, submit PR, see it crash.

**Comment by matthewfeickert** [comment]
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ makes it seems like maybe we want `workflow_run` instead. I'll read more.
