### ISSUE TITLE
Argument bug in ImpactPlot.ipynb

### ISSUE THREAD

**Issue by iokarkan** [scikit-hep/pyhf#1468]
# Description
I have tried comparing my own Impact calculation function with the one in the 
docs/examples/notebooks/ImpactPlot.ipynb, specifically trying with a dummy
version of my own workspace, featuring only the lumi parameter.

The line performing the impact calculation seems to incorrectly put the init_pars value in the position of the width
argument, and vice versa.

(there is an ongoing effort for this impact plot, but I could not find the issue reported,
delete if duplicate or covered under existing efforts)

Describe your bug here

# Expected Behavior

In the line:
`        impct = calc_impact(i, b[i], e[i], width, initv[i], model.config.poi_index)`
the 'width' and 'initv[i]' arguments are in the wrong positions.

'width' and 'initv[i]' should be swapped.

# Actual Behavior

If you add a print statement for a lumi parameter,
you can see that currently width=1.0, whereas it should be something like 0.017 (for ATLAS Run 2 lumi uncertainty).
This gets the impact calculation wrong.

# Steps to Reproduce

Gist to reproduce the behaviour:
https://gist.github.com/iokarkan/b0e9df230ec59693246020c5ebd73e66

Simple workspace with lumi parameter.
Notice the print statement checking the width argument.

Detail your environment and `pyhf.__version__` and the commands that you are executing to generate the bug. If you have a large program please make a [Gist](https://gist.github.com/) and link it here. Additionally attach any screen shots as needed.

pyhf version 0.6.1

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by matthewfeickert** [comment]
@iokarkan This is already reported in Issue #1180, so closing in favor of the existing Issue.
