### ISSUE TITLE
test TF Eager execution

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/pyhf#152]
# Description

Since some time TF also has some support for eager execution. It would be interested to see what's necessary to run pyhf with the TF backend in that mode.

**Comment by matthewfeickert** [comment]
For reference for whoever works on this: [Eager Execution in TensorFlow](https://www.tensorflow.org/programmers_guide/eager)

**Comment by matthewfeickert** [comment]
Closing this as TF 2.0 is eager by default, and the default behavior for pyhf's TensorFlow backend.
