### ISSUE TITLE
tests: Fix SciPy builds to run nightly tests against SciPy HEAD

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1531]
# Description

At the moment testing against the `HEAD` of SciPy's GitHub repo is causing timeout failures and isn't helping to catch anything

https://github.com/scikit-hep/pyhf/blob/025ffe9be212f53a8eb6c46f7a53cc3e50017d81/.github/workflows/dependencies-head.yml#L24-L31

This is being reverted to just using `--pre` to test against release candidates, but it would be good to figure out how to get a working build. 

Trying to follow what [SciPy is doing in GHA for build tests](https://github.com/scipy/scipy/blob/053f3f54130f8b17c09540352a784f4c54a919df/.github/workflows/linux.yml#L24-L44) doesn't seem to actually install it.

All the testing on this is being done on the `fix/get-scipy-building` dev branch.

**Comment by matthewfeickert** [comment]
As an example, this build on `fix/get-scipy-building` was manually killed after 46 minutes of running

![scipy_timeout](https://user-images.githubusercontent.com/5142394/127066688-01473862-c4d8-4bf5-a951-d8f0bafe104a.png)

but if let run it would [run for 6 hours and then timeout](https://github.com/scikit-hep/pyhf/runs/3152765854?check_suite_focus=true).

**Comment by rgommers** [comment]
A few questions/suggestions:
- Do you need to build SciPy from source? There are nightly wheels at https://anaconda.org/scipy-wheels-nightly/
- Looking at `dependencies_head.yml`, you are not installing both ATLAS and plain LAPACK. Why the latter? Maybe it happens to pick up Netlib LAPACK for some reason rather than failing, and that's what makes it slow? Is your test suite heavy on linear algebra?

**Comment by matthewfeickert** [comment]
> * Do you need to build SciPy from source? There are nightly wheels at https://anaconda.org/scipy-wheels-nightly/

Thank you for pointing this out, @rgommers! The wheels are excellent and perfect for this use case. Huge thanks to the SciPy team and Anaconda for making these available. :rocket: 

> * Looking at `dependencies_head.yml`, you are now installing both ATLAS and plain LAPACK. Why the latter? 

Ignorance on my part, to be sure as I'm not an expert here, sadly. Though the `sudo apt-get` install that I have in the `dependencies_head.yml` on the test branch

```yaml
sudo apt-get install -y gcc python3-dev libopenblas-dev libatlas-base-dev liblapack-dev gfortran libgmp-dev libmpfr-dev libsuitesparse-dev ccache swig libmpc-dev
```

is just a slightly modified version of what I copied from [the SciPy GHA `linux.yml`](https://github.com/scipy/scipy/blob/2552ed59db97768f74afd12b53e351b76cd9b180/.github/workflows/linux.yml#L25)

```yaml
sudo apt install python3.7-dbg python3.7-dev libatlas-base-dev liblapack-dev gfortran libgmp-dev libmpfr-dev libsuitesparse-dev ccache swig libmpc-dev
```

> Maybe it happens to pick up Netlib LAPACK for some reason rather than failing, and that's what makes it slow? Is your test suite heavy on linear algebra?

Possibly? My assumption is that something was getting built wrong or picked up wrong, so this seems to make sense, but my confusion was that I was copying the SciPy GHA installs mostly. I suppose it depends on what one means by "heavy", but as `pyhf` focused on statistical fitting, yes almost everything in the test suite is making calls to NumPy and SciPy at some point to do the minimzation.

---

I'm going to close this with PR #1533, but I will probably poke around on this problem to some extent more to figure out if I can pinpoint what went wrong for my own education. Thank you very much for your help though!

**Comment by rgommers** [comment]
> is just a slightly modified version of what I copied from [the SciPy GHA `linux.yml`](https://github.com/scipy/scipy/blob/2552ed59db97768f74afd12b53e351b76cd9b180/.github/workflows/linux.yml#L25)

Ah, did not remember that - guess it is needed then.

The build log is hidden, that's why it's hard to see what is going on. Enabling it by adding `--verbose` for `pip` may be instructive.

If you find out what caused this, please let me know - it may come up in other places.

**Comment by matthewfeickert** [comment]
> If you find out what caused this, please let me know - it may come up in other places.

:+1: Will do.

**Comment by matthewfeickert** [comment]
> The build log is hidden, that's why it's hard to see what is going on.

This probably isn't a huge help at the moment, but here's a `.zip` file with the logs for a [recent build of SciPy on the test branch](https://github.com/scikit-hep/pyhf/runs/3157750993?check_suite_focus=true) that I canceled after an hour:

[scipy-ubuntu-latest-python3.8.zip](https://github.com/scikit-hep/pyhf/files/6887626/scipy-ubuntu-latest-python3.8.zip)

I can make the logs more verbose in the future.
