### ISSUE TITLE
Different ordering of channels between model.config.channels and mode.config.channel_nbins

### ISSUE THREAD

**Issue by rjhyneman** [scikit-hep/pyhf#1545]
# Description

We've recently observed that the ordering of channels outputted from `model.config.channels` differs from the order obtained with `model.config.channel_nbins`. This isn't really a bug, but more a quirk which we thought would be worth bringing to the attention of the developers. We ran into some issues when breaking up the `expected_data` list into individual channels by looping through the `model.config.channel_nbins` ordering, rather than the `model.config.channels` ordering (the `model.config.channels` order matches that of the model). Hopefully this issue helps save another user some time in the future, at very least. 

# Expected Behavior

We expected that the order of the channels in the two dictionaries from `model.config.channels` and `model.config.channel_nbins` would be the same. 

# Actual Behavior

The ordering of the channels is different. As an example, we are generating workspaces using two categories, and we're separating our data by year (2016, 2017, and 2018). This gives us six channels total. The outputs are: 
```
(Pdb) model.config.channels
['vbf_channel_16_high_cat', 'vbf_channel_16_low_cat', 'vbf_channel_17_high_cat', 'vbf_channel_17_low_cat', 'vbf_channel_18_high_cat', 'vbf_channel_18_low_cat']

(Pdb) model.config.channel_nbins
{'vbf_channel_16_low_cat': 12, 'vbf_channel_16_high_cat': 18, 'vbf_channel_17_low_cat': 12, 'vbf_channel_17_high_cat': 18, 'vbf_channel_18_low_cat': 12, 'vbf_channel_18_high_cat': 18}
```
I believe that `model.config.channels` is possibly re-ordering the channels so that the names are in alphabetical order. I have not confirmed this, though. The workspace .json file is filled with the ordering produced by `model.config.channel_nbins`. 

# Steps to Reproduce

I'm using pyhf version 0.6.2 along with python 3.8.8. 
I can make a dummy workspace for this issue, but I thought that since this is a pretty small issue, it might be overkill. Please let me know if this would be helpful, though. 

# Checklist

- [ ] Run `git fetch` to get the most up to date version of `master`
- [X] Searched through existing Issues to confirm this is not a duplicate issue
- [X] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

Thanks! -Rachel

**Comment by matthewfeickert** [comment]
Thanks for the Issue @rjhyneman. I think we can deal with this pretty easily (unless @kratsg knows something that I don't about how this might be a problem).

> We expected that the order of the channels in the two dictionaries from `model.config.channels` and `model.config.channel_nbins` would be the same.

This is the crux of it, as they're not both dictionaries: `model.config.channels` is a `list` and `model.config.channel_nbins` is a `dict`.

You can see how both are created and filled

https://github.com/scikit-hep/pyhf/blob/0588b2126e1bf19e6b7d9e00eb75d55dff535142/src/pyhf/mixins.py#L16-L29

but then a little lower down we sort the `channels`

https://github.com/scikit-hep/pyhf/blob/0588b2126e1bf19e6b7d9e00eb75d55dff535142/src/pyhf/mixins.py#L41

but there isn't an equivalent operation for a `dict` (which kind makes sense given that a `dict` is a map).

Though as the code is simple enough to read through, it is also easy to add this functionality that you want. Do you want to open a PR for it? 

Here's just a simple script to show the 1 line needed.

```python
# issue_1545.py
analyis_channels = [
    "vbf_channel_16_high_cat",
    "vbf_channel_16_low_cat",
    "vbf_channel_17_high_cat",
    "vbf_channel_17_low_cat",
    "vbf_channel_18_high_cat",
    "vbf_channel_18_low_cat",
]
channels = []
channel_nbins = {}

example_number = 1
for channel_name in analyis_channels:
    channels.append(channel_name)
    channel_nbins[channel_name] = example_number
    example_number += 1

print("After creation:")
print(f"{channels = }")
print(f"{channel_nbins = }")

channels = sorted(list(set(channels)))
print("\nAfter channels sort:")
print(f"{channels = }")
print(f"{channel_nbins = }")

channel_nbins = {channel_name: channel_nbins[channel_name] for channel_name in channels}

print("\nAfter channel_nbins sort:")
print(f"{channels = }")
print(f"{channel_nbins = }")

# Sanity check
assert channels == list(channel_nbins.keys())
```
```console
$ python issue_1545.py 
After creation:
channels = ['vbf_channel_16_high_cat', 'vbf_channel_16_low_cat', 'vbf_channel_17_high_cat', 'vbf_channel_17_low_cat', 'vbf_channel_18_high_cat', 'vbf_channel_18_low_cat']
channel_nbins = {'vbf_channel_16_high_cat': 1, 'vbf_channel_16_low_cat': 2, 'vbf_channel_17_high_cat': 3, 'vbf_channel_17_low_cat': 4, 'vbf_channel_18_high_cat': 5, 'vbf_channel_18_low_cat': 6}

After channels sort:
channels = ['vbf_channel_16_high_cat', 'vbf_channel_16_low_cat', 'vbf_channel_17_high_cat', 'vbf_channel_17_low_cat', 'vbf_channel_18_high_cat', 'vbf_channel_18_low_cat']
channel_nbins = {'vbf_channel_16_high_cat': 1, 'vbf_channel_16_low_cat': 2, 'vbf_channel_17_high_cat': 3, 'vbf_channel_17_low_cat': 4, 'vbf_channel_18_high_cat': 5, 'vbf_channel_18_low_cat': 6}

After channel_nbins sort:
channels = ['vbf_channel_16_high_cat', 'vbf_channel_16_low_cat', 'vbf_channel_17_high_cat', 'vbf_channel_17_low_cat', 'vbf_channel_18_high_cat', 'vbf_channel_18_low_cat']
channel_nbins = {'vbf_channel_16_high_cat': 1, 'vbf_channel_16_low_cat': 2, 'vbf_channel_17_high_cat': 3, 'vbf_channel_17_low_cat': 4, 'vbf_channel_18_high_cat': 5, 'vbf_channel_18_low_cat': 6}
```

**Comment by alexander-held** [comment]
See also #1141 for the task of splitting observations into channels.

**Comment by rjhyneman** [comment]
Hi all, 
Sorry for my radio silence; I am quite disorganized lately. 
I just wanted to say thanks a ton for addressing this!! I believe everything in our analysis stats framework is now consistently using the `channels` ordering, but it's reassuring that (once we update to pyhf 0.6.3) we don't need to stress so much if we missed an instance of `channel_bins`. 
I also wanted to say that I think the proposal of having some sort of "data slice" call for a given category, as described in https://github.com/scikit-hep/pyhf/issues/1141, would be really convenient. A function like this would have replaced our need for iterating through `channels`/`channel_bins` to slice the `expected_data` into categories ourselves. I personally think that any way to avoid the user needing to know in what order the bin contents for all categories are being stored in the `data` lists would be nice, since this seems to me like it might be a common spot for user error. 
Thanks again, 
-Rachel

**Comment by matthewfeickert** [comment]
> I just wanted to say thanks a ton for addressing this!! I believe everything in our analysis stats framework is now consistently using the `channels` ordering, but it's reassuring that (once we update to pyhf 0.6.3) we don't need to stress so much if we missed an instance of `channel_bins`.

Sure and thanks for the Issue @rjhyneman. If you find that you'll need it sooner than the `pyhf` `v0.6.3` release window (which will probably happen as soon as PR #1530 is in and then lead to a `v0.6.4` to get the last bits before `v0.7.0` features) you can always try the (unsupported) dev releases from TestPyPI: https://pyhf.readthedocs.io/en/v0.6.2/development.html#testpypi

> I also wanted to say that I think the proposal of having some sort of "data slice" call for a given category, as described in #1141, would be really convenient. A function like this would have replaced our need for iterating through `channels`/`channel_bins` to slice the `expected_data` into categories ourselves. I personally think that any way to avoid the user needing to know in what order the bin contents for all categories are being stored in the `data` lists would be nice, since this seems to me like it might be a common spot for user error.

Yeah, Issue #1141 would be a good candidate for either `v0.6.4` or `v0.7.0` for all the reasons Alex had laid out in it. I've added the `help-wanted` label to it given other timelines, but I'll also mention here (to anyone/everyone) that PRs for issues that are already opened like #1141 are welcome. :+1:
