### ISSUE TITLE
StatisticalAnalysis Notebook broken by `with_aux` to `include_auxdata`

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1585]
### Summary

The `StatisticalAnalysis.ipynb` is currently broken given the API change from PR #1562. 

```console
$ git grep "with_aux" docs/examples
docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb:    "        ax.scatter(x, workspace.data(pdf, with_aux=False), c=\"k\", alpha=1.0, zorder=99),\n",
docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb:    "    ax.scatter(x, workspace.data(pdf, with_aux=False), c=\"k\", alpha=1.0, zorder=99)"
docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb:    "ax.set_ylim(0, 1.5 * np.max(workspace.data(pdf, with_aux=False)))\n",
docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb:    "ax1.set_ylim(0, 1.5 * np.max(workspace.data(pdf, with_aux=False)))\n",
```

`with_aux` just needs to be changed to `include_auxdata` and it should work again.

### Documentation Page Link

https://pyhf.readthedocs.io/en/v0.6.3/examples/notebooks/binderexample/StatisticalAnalysis.html

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by kratsg** [comment]
Is this not caught by our tests?

**Comment by matthewfeickert** [comment]
> Is this not caught by our tests?

It is, but given that PR #883 isn't done to address Issue #822, the notebook tests have been failing for long enough that I've stopped checking them nightly. :grimacing: 

Time to fix them it seems.
