### ISSUE TITLE
v0.6.3 release notes refers to a channels dict, but it is a list

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1590]
### Summary

Minor papercut that @matthewfeickert made while writing the release notes: `channels` is a `list` not a `dict`, which was the point of Issue #1545

So should be
```diff
@@ -56,7 +56,7 @@ Python API
       ['mu', 'uncorr_bkguncrt[0]', 'uncorr_bkguncrt[1]']
 
 * The :class:`pyhf.pdf._ModelConfig` ``channel_nbins`` dict is now sorted by
-  keys to match the order of the ``channels`` dict.
+  keys to match the order of the ``channels`` list.
   (PR :pr:`1546`)
 
 * The :func:`pyhf.workspace.Workspace.data` ``with_aux`` keyword arg has been
```

### Documentation Page Link

https://github.com/scikit-hep/pyhf/blob/173c3c711c8037928a966d381c922fd535be956f/docs/release-notes/v0.6.3.rst

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by RhnSharma** [comment]
I would like to take this one.
