### ISSUE TITLE
chore: some possible cleanup / extra testing

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/pyhf#1685]
The old black Jupyter code still needs to be removed:
https://github.com/scikit-hep/pyhf/blob/c493c7c5ad3e5aeda7d022cdf5fe77e9fdab43a2/pyproject.toml#L78-L79
(and a line below)

https://github.com/scikit-hep/pyhf/blob/c493c7c5ad3e5aeda7d022cdf5fe77e9fdab43a2/pyproject.toml#L81-L82

The pytest adpdotps probably could do without the ignores? What are they for?

https://github.com/scikit-hep/pyhf/blob/c493c7c5ad3e5aeda7d022cdf5fe77e9fdab43a2/pyproject.toml#L44-L55

Some of the options here for pytest might be useful:
https://scikit-hep.org/developer/pytest#configuring-pytest

I’d probably at least put the lower bound requirements into tests, that’s not a public thing really. Keeping the main directory from getting too big reduces user scrolling.

**Comment by matthewfeickert** [comment]
Thanks for following up here like I requested @henryiii. :) I'll do some cleaning on this soon.
