### ISSUE TITLE
Option to skip workspace validation

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/pyhf#1699]
### Summary

Workspace validation is currently not skippable:

https://github.com/scikit-hep/pyhf/blob/767ed59d06274f810e47944f1fe4c95d94968543/src/pyhf/workspace.py#L289-L298

In some scenarios the validation takes a significant amount of time, and it would be convenient if it was possible to skip it.

### Additional Information

This is using [NormalMeasurement_combined.txt](https://github.com/scikit-hep/pyhf/files/7522251/NormalMeasurement_combined.txt) from https://github.com/scikit-hep/pyhf/discussions/1695. While working with [this gist](https://gist.github.com/alexander-held/2f6727df4cc8f65d75368e293ca83b5a) used in https://github.com/scikit-hep/pyhf/discussions/1695#discussioncomment-1635955, I noticed that workspace validation can take a long time for this example. Below is a minimal reproducer:

```python (paste below)
import pyhf
import json

with open("NormalMeasurement_combined.txt") as f:
    ws = pyhf.Workspace(json.load(f))
```

This runs in around 5.4 seconds for me locally.

When commenting out 

https://github.com/scikit-hep/pyhf/blob/767ed59d06274f810e47944f1fe4c95d94968543/src/pyhf/workspace.py#L298

this time goes down to 1.6 seconds.

The workspace validation takes about as long as the model construction (via `ws.model()`), which for me takes about 4 seconds by itself (again dominated by validation time in this example). It is possible to skip model validation (via `validate=False`), and I believe it would be useful to allow the same for the workspace.

I also noticed that arbitrary kwargs can be passed to workspace construction, e.g. in the above example
```python
ws = pyhf.Workspace(json.load(f), abcdefg=False)
```
also runs fine. It may be convenient to catch these kwargs to help users identify typos.

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by matthewfeickert** [comment]
This seems reasonable to add with it being turned off by default so that only expert users will try to use it.
