### ISSUE TITLE
Clarify absolute vs relative for likelihood specification

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/pyhf#1718]
### Summary

This was mentioned in an offline discussion by @hepstr but an example for `histosys` doesn't explicitly state the meaning of the specification/declaration. It would be nicer if we mentioned exactly what the effect is (a shift from nominal to 20 events in first bin and 15 events in second bin for up variation...)

### Documentation Page Link

https://scikit-hep.org/pyhf/likelihood.html#correlated-shape-histosys

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by alexander-held** [comment]
related issue for `staterror`: #1018
