### ISSUE TITLE
Remove deprecated distutils functionality

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1728]
`distutils` is deprecated in Python 3.10+, as noted in the [`pip` `v21.3` release notes](https://pip.pypa.io/en/stable/news/#v21-3)

> On Python 3.10 or later, the installation scheme backend has been changed to use `sysconfig`. This is to anticipate the deprecation of `distutils` in Python 3.10, and its scheduled removal in `3.12`. For compatibility considerations, pip installations running on Python 3.9 or lower will continue to use `distutils`.

To prevent bugs in the future that will cause tests to break, we should switch the `distutils` functionality that `pyhf` uses

https://github.com/scikit-hep/pyhf/blob/43c156702fd2a0392114c5b2468f0128ed16ea72/tests/conftest.py#L7

https://github.com/scikit-hep/pyhf/blob/43c156702fd2a0392114c5b2468f0128ed16ea72/tests/conftest.py#L130-L134

to `setuptools` (I think it is `setuptools`).

Assigning this to Giordon for now given `git blame` leads to PR #847. :+1:

**Comment by kratsg** [comment]
yeah, the comment said we need to wait until python 3.8+ only.

**Comment by matthewfeickert** [comment]
> yeah, the comment said we need to wait until python 3.8+ only.

No that's with regards to using `shutil`. We should move to trying to use `setuptools` in place of `distutils` now though.
