### ISSUE TITLE
Use of `del` for staterror in writexml necessary?

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1770]
In PR #435 the use of `del` was added in 

https://github.com/scikit-hep/pyhf/blob/e3d879f3e4982ac629bec7bf92d78b00025e52dc/src/pyhf/writexml.py#L186-L191

I assume because later on in the PR it mentions

https://github.com/scikit-hep/pyhf/blob/e3d879f3e4982ac629bec7bf92d78b00025e52dc/tests/test_export.py#L257-L259

However, if you remove that `del` statement

```
pytest -sx tests/test_export.py -k test_export_modifier
```

still passes.

Do we still need it? @kratsg have any thoughts here?

**Comment by kratsg** [comment]
It's needed -- https://github.com/scikit-hep/pyhf/blob/569f51257c6a895508f9c026bd61a2e723cb339c/src/pyhf/schemas/HistFactorySchema.dtd#L105-L112

We do need a test to assert that the exported staterror XML does not have a `Name` attribute. HiFa doesn't support staterror having names.
