### ISSUE TITLE
build: Use `"setuptools>=42" in build-system requires in pyproject.toml

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1774]
`"setuptools>=30.3.0"` should be `"setuptools>=42"`; anything before 42 was too buggy to be used with pyproject.toml (40-42), or didn't support pyproject.toml at all. (technically, PEP 517)

_Originally posted by @henryiii in https://github.com/scikit-hep/pyhf/pull/1773#issuecomment-1034493252_

So

https://github.com/scikit-hep/pyhf/blob/b0919859ad9bbbed7541a8217576d2594bd5386c/pyproject.toml#L1-L3

should be

```toml
requires = ["wheel", "setuptools>=42.0.0", "attrs>=17.1", "setuptools_scm[toml]>=3.4"]
```

**Comment by RishiKumarRay** [comment]
@matthewfeickert i would like to take this

**Comment by RishiKumarRay** [comment]
@matthewfeickert is it available?
