### ISSUE TITLE
handle empty bins gracefully

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/pyhf#180]
# Description

Poissons are only defined for rate parameters > 0. But it might well be that the histograms contain bins in which the total expected rate is 0 (perhaps the binning was chosen to include bins that never get filled).

Arguably those should be filtered out -- or we leave it up to the user, but then we should print a warning.

**Comment by kratsg** [comment]
Can you add an example? I'm not sure I fully understand the issue here.

**Comment by matthewfeickert** [comment]
@lukasheinrich So if I understand the idea, you're saying that as the p.mf. for the Poisson distribution is

<a href="https://www.codecogs.com/eqnedit.php?latex=f\left(n\,\middle|\,\nu&space;\right)&space;=&space;\frac{\nu^{n}&space;\,e^{-\nu}}{n!}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?f\left(n\,\middle|\,\nu&space;\right)&space;=&space;\frac{\nu^{n}&space;\,e^{-\nu}}{n!}" title="f\left(n\,\middle|\,\nu \right) = \frac{\nu^{n} \,e^{-\nu}}{n!}" /></a>

then for bins with <a href="https://www.codecogs.com/eqnedit.php?latex=\nu&space;=&space;0" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\nu&space;=&space;0" title="\nu = 0" /></a> the p.m.f. is 0 and so they should be filtered out of the model as they don't contribute. I would think that this is the correct behavior, but can you or @kratsg think of instances in which they should not be? If so I guess I would think the default behavior should still be to filter them out but allow the user to pass some option that overrides this with a warning.

**Comment by kratsg** [comment]
For Poissons, we have to filter them out. What's not clear to me is how the code is affected. I guess this is introducing some of the "divide by zero encountered" errors that we see from time to time.

**Comment by matthewfeickert** [comment]
Closing this in favor of Issue #293.
