### ISSUE TITLE
xml2json extremely slow

### ISSUE THREAD

**Issue by cburgard** [scikit-hep/pyhf#1882]
### Summary

When trying to convert some XMLs to pyhf JSON, I found that the runtime was unacceptably slow (order of hours).

### OS / Environment

```console
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo
```

### Steps to Reproduce

The XMLs are ATLAS internal, but I'm happy to share them with ATLAS members of the dev team on request.

### Expected Results

I was hoping it would finish relatively fast.

### Actual Results

```console
It took hours.
```

### pyhf Version

```console
pyhf, version 0.6.3
uproot 4.2.2
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by matthewfeickert** [comment]
Thanks for the report @cburgard. Can you please share the files as a private GitHub Gist with the dev team?

**Comment by matthewfeickert** [comment]
@cburgard Please first verify that you have read through the [translations docs](https://pyhf.readthedocs.io/en/v0.6.3/babel.html#translations) and tell us how the workspaces were created. Then please tell us the exact commands that you are using.

**Comment by cburgard** [comment]
The workspaces were created with SFramwork, specifically with this function:
https://gitlab.cern.ch/atlas-caf/CAFCore/-/blob/master/SFramework/Root/TSModelFactory.cxx#L176

The exact command I was using is
`pyhf xml2json hww-xml/HWWRun2GGF.xml`

**Comment by matthewfeickert** [comment]
> The workspaces were created with SFramwork, specifically with this function: https://gitlab.cern.ch/atlas-caf/CAFCore/-/blob/b1d40c29b0b4635c28d563db1483317d4a8b25d5/SFramework/Root/TSModelFactory.cxx#L176

@cburgard Okay, well as you'll note we have no translation recipe for `SFramework` in the docs, so we can't make any statements of support for `SFramework` until we have one. If `SFramework` is only capable of hardcoding full paths into the XML then I to do any debugging we would need the original files. Though I'm assuming that this is just a choice that was enabled somewhere in `SFramework`? Can you produce the workspaces with relative paths? Otherwise this would mean the workspaces would be unusable anywhere but on the machine where they were originally produced.

**Comment by matthewfeickert** [comment]
> If you'd be aware of a simple way to instruct the C++ implementation of HistFactory to output xmls with relative rather than absolute paths, I'd be happy to reproduce the xmls with that setting, otherwise, `sed` will have to suffice I fear.

:grimacing: Thanks for the info as this helps move things forward. Perhaps we he's back from holiday we can ask @kratsg if he has any insight onto how HistFitter is able to do things unless @longjon929 is able to comment on that sooner.

**Comment by matthewfeickert** [comment]
@cburgard great news (I hope)! @kratsg is adding a feature in PR #1909 that is able to automatically deal with hardcoded absolute paths and when he does the conversion on an old 2011 macbook running macOS 10.11 (his current MBP is in for repairs :cry:) he gets the following

```console
$ time pyhf xml2json --hide-progress -v $PWD:/home/cburgard/Physics/statistics/pyfittools hww-xml/HWWRun2GGF.xml --output-file test.json

real	1m7.212s
user	1m6.320s
sys	0m1.180s
```

so hopefully you'll get things even faster than that on your local machine.

**Comment by longjon929** [comment]
Hi @matthewfeickert , sorry for being slow and I imagine this isn't very useful.  It looks like HistFitter writes out the XML by hand making a top level file from the fitconfig [here](https://github.com/histfitter/histfitter/blob/master/python/fitConfig.py#L865) and then each channel is looped over and dumps a file [here](https://github.com/histfitter/histfitter/blob/master/python/channel.py#L513).  I imagine HF was developed with this structure in mind from HistFactory, which makes it straightforward to write out the xml.

**Comment by alexander-held** [comment]
[`PrintXML`](https://root.cern.ch/doc/master/classRooStats_1_1HistFactory_1_1Channel.html#ae83497da2ea795d2ed1063e7d43b1ea2) allows using relative paths too. The downside of using relative paths there is that you (currently) need to call `pyhf xml2json` from the same place where the relative paths originate from, which is not necessarily the place where the top-level xml is located.

**Comment by kratsg** [comment]
> [`PrintXML`](https://root.cern.ch/doc/master/classRooStats_1_1HistFactory_1_1Channel.html#ae83497da2ea795d2ed1063e7d43b1ea2) allows using relative paths too. The downside of using relative paths there is that you (currently) need to call `pyhf xml2json` from the same place where the relative paths originate from, which is not necessarily the place where the top-level xml is located.

This will be better with #1909 but you can already use `--basedir` to change the base of the relative paths, by prefixing them, so it doesn't necessarily need to be in the same place.

**Comment by matthewfeickert** [comment]
Thanks to some fantastic work by @kratsg, PR #1909 is in `master` now. So I believe that this should be resolved if people install from the development `HEAD`. I haven't actually taken the time to look at this particular Issue with PR #1909 in yet, but I can try to later this week.

**Comment by matthewfeickert** [comment]
A final note on this, as I write up the release notes in PR #1705:

```console
$ time pyhf xml2json \
    --hide-progress \
    --mount $PWD:/home/cburgard/Physics/statistics/pyfittools/ \
    --output-file workspace.json \
    hww-xml/HWWRun2GGF.xml
pyhf xml2json --hide-progress --mount  --output-file workspace.json   14.71s user 2.33s system 119% cpu 14.269 total
```

:+1: Great work by @kratsg! :rocket:
