### ISSUE TITLE
CI failing for `iminuit` `v2.12.2`

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1918]
### Summary

On 2022-07-15 [`iminuit` `v2.12.2`](https://github.com/scikit-hep/iminuit/releases/tag/v2.12.2) was released to "fix bug in error heuristic and prevent assigning non-positive values". With this release the CI is failing for `tests/test_infer.py`, `tests/test_otim.py`, `tests/test_jit.py`, `tests/test_public_api.py`, `tests/test_scripts.py`, and `tests/test_validation.py`

### OS / Environment

```console
All
```

### Steps to Reproduce

Run the test suite in CI

### Expected Results

CI to pass

### Actual Results

```console
All the above tests fail.
```

### pyhf Version

```console
`HEAD` which is currently 8e242c9c829963c714f9b10acd28494f004a2452
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by alexander-held** [comment]
I saw the same for `cabinetry`, presumably due to https://github.com/scikit-hep/iminuit/issues/762.

**Comment by matthewfeickert** [comment]
This is also happening (understandably) in `v2.13.0` given that it was released today.
