### ISSUE TITLE
Minimum supported version tests failing

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1957]
Following merging of PR #1909, the 

https://github.com/scikit-hep/pyhf/blob/f01dcf59da10ec9313345305efc49cfb7186bf99/.github/workflows/lower-bound-requirements.yml#L1

workflow started failing for

https://github.com/scikit-hep/pyhf/blob/f01dcf59da10ec9313345305efc49cfb7186bf99/tests/test_scripts.py#L166

with

```
=================================== FAILURES ===================================
______________________ test_import_usingMounts[inprocess] ______________________

datadir = PosixPath('/tmp/pytest-of-runner/pytest-0/test_import_usingMounts_inproc0')
tmpdir = local('/tmp/pytest-of-runner/pytest-0/test_import_usingMounts_inproc0')
script_runner = <ScriptRunner inprocess>

    def test_import_usingMounts(datadir, tmpdir, script_runner):
        data = datadir.joinpath("xmlimport_absolutePaths")
    
        temp = tmpdir.join("parsed_output.json")
        command = f'pyhf xml2json --hide-progress -v {data}:/absolute/path/to -v {data}:/another/absolute/path/to --output-file {temp.strpath:s} {data.joinpath("config/example.xml")}'
    
        ret = script_runner.run(*shlex.split(command))
>       assert ret.success
E       assert False
E        +  where False = <pytest_console_scripts.RunResult object at 0x7f93d[84](https://github.com/scikit-hep/pyhf/runs/8031258926?check_suite_focus=true#step:6:85)a6750>.success

command    = 'pyhf xml2json --hide-progress -v /tmp/pytest-of-runner/pytest-0/test_import_usingMounts_inproc0/xmlimport_absolutePat..._output.json /tmp/pytest-of-runner/pytest-0/test_import_usingMounts_inproc0/xmlimport_absolutePaths/config/example.xml'
data       = PosixPath('/tmp/pytest-of-runner/pytest-0/test_import_usingMounts_inproc0/xmlimport_absolutePaths')
datadir    = PosixPath('/tmp/pytest-of-runner/pytest-0/test_import_usingMounts_inproc0')
ret        = <pytest_console_scripts.RunResult object at 0x7f93d84a6750>
script_runner = <ScriptRunner inprocess>
temp       = local('/tmp/pytest-of-runner/pytest-0/test_import_usingMounts_inproc0/parsed_output.json')
tmpdir     = local('/tmp/pytest-of-runner/pytest-0/test_import_usingMounts_inproc0')

tests/test_scripts.py:173: AssertionError
----------------------------- Captured stdout call -----------------------------
# Running console script: pyhf xml2json --hide-progress -v /tmp/pytest-of-runner/pytest-0/test_import_usingMounts_inproc0/xmlimport_absolutePaths:/absolute/path/to -v /tmp/pytest-of-runner/pytest-0/test_import_usingMounts_inproc0/xmlimport_absolutePaths:/another/absolute/path/to --output-file /tmp/pytest-of-runner/pytest-0/test_import_usingMounts_inproc0/parsed_output.json /tmp/pytest-of-runner/pytest-0/test_import_usingMounts_inproc0/xmlimport_absolutePaths/config/example.xml
# Script return code: 1
# Script stdout:

# Script stderr:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pytest_console_scripts.py", line 188, in console_script
    return s()
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pyhf/cli/rootio.py", line 63, in xml2json
    validation_as_error=validation_as_error,
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pyhf/readxml.py", line 455, in parse
    ET.parse(resolver(inp)), resolver, track_progress
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/xml/etree/ElementTree.py", line 5[87](https://github.com/scikit-hep/pyhf/runs/8031258926?check_suite_focus=true#step:6:88), in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/absolute/path/to/config/example_channel.xml'
```

we had thought that PR #1917 would fix this, but it hasn't. Given the core requirements of pyhf are modest

https://github.com/scikit-hep/pyhf/blob/f01dcf59da10ec9313345305efc49cfb7186bf99/tests/constraints.txt#L1-L9

it is unclear to me why the tests with these unpinned pass, but fail here.

**Comment by matthewfeickert** [comment]
Running 

```console
$ pytest tests/test_scripts.py -k 'test_import_usingMounts'            
```

fails

```
================================================================================= test session starts =================================================================================
platform linux -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0
Matplotlib: 3.5.2
Freetype: 2.6.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/feickert/Code/GitHub/pyhf, configfile: pyproject.toml
plugins: console-scripts-1.3.1, mpl-0.16.0, benchmark-3.4.1, cov-3.0.0, mock-3.8.2, requests-mock-1.9.3, anyio-3.6.1
collected 62 items / 60 deselected / 2 selected                                                                                                                                       

tests/test_scripts.py F.                                                                                                                                                        [100%]

====================================================================================== FAILURES =======================================================================================
_________________________________________________________________________ test_import_usingMounts[inprocess] __________________________________________________________________________

datadir = PosixPath('/tmp/pytest-of-feickert/pytest-4/test_import_usingMounts_inproc0'), tmpdir = local('/tmp/pytest-of-feickert/pytest-4/test_import_usingMounts_inproc0')
script_runner = <ScriptRunner inprocess>

    def test_import_usingMounts(datadir, tmpdir, script_runner):
        data = datadir.joinpath("xmlimport_absolutePaths")
    
        temp = tmpdir.join("parsed_output.json")
        command = f'pyhf xml2json --hide-progress -v {data}:/absolute/path/to -v {data}:/another/absolute/path/to --output-file {temp.strpath:s} {data.joinpath("config/example.xml")}'
    
        ret = script_runner.run(*shlex.split(command))
        assert ret.success
        assert ret.stdout == ''
>       assert ret.stderr == ''
E       AssertionError: assert 'DEBUG:pyhf.c...output.json\n' == ''
E         + DEBUG:pyhf.cli.rootio:Written to /tmp/pytest-of-feickert/pytest-4/test_import_usingMounts_inproc0/parsed_output.json

command    = 'pyhf xml2json --hide-progress -v /tmp/pytest-of-feickert/pytest-4/test_import_usingMounts_inproc0/xmlimport_absoluteP...utput.json /tmp/pytest-of-feickert/pytest-4/test_import_usingMounts_inproc0/xmlimport_absolutePaths/config/example.xml'
data       = PosixPath('/tmp/pytest-of-feickert/pytest-4/test_import_usingMounts_inproc0/xmlimport_absolutePaths')
datadir    = PosixPath('/tmp/pytest-of-feickert/pytest-4/test_import_usingMounts_inproc0')
ret        = <pytest_console_scripts.RunResult object at 0x7fe02f776740>
script_runner = <ScriptRunner inprocess>
temp       = local('/tmp/pytest-of-feickert/pytest-4/test_import_usingMounts_inproc0/parsed_output.json')
tmpdir     = local('/tmp/pytest-of-feickert/pytest-4/test_import_usingMounts_inproc0')

tests/test_scripts.py:175: AssertionError
-------------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------------
# Running console script: pyhf xml2json --hide-progress -v /tmp/pytest-of-feickert/pytest-4/test_import_usingMounts_inproc0/xmlimport_absolutePaths:/absolute/path/to -v /tmp/pytest-of-feickert/pytest-4/test_import_usingMounts_inproc0/xmlimport_absolutePaths:/another/absolute/path/to --output-file /tmp/pytest-of-feickert/pytest-4/test_import_usingMounts_inproc0/parsed_output.json /tmp/pytest-of-feickert/pytest-4/test_import_usingMounts_inproc0/xmlimport_absolutePaths/config/example.xml
# Script return code: 0
# Script stdout:

# Script stderr:
DEBUG:pyhf.cli.rootio:Written to /tmp/pytest-of-feickert/pytest-4/test_import_usingMounts_inproc0/parsed_output.json
```

even though running the full scripts tests suite passes

```console
$ pytest tests/test_scripts.py
```

so it might additionally be worth considering checking if

https://github.com/scikit-hep/pyhf/blob/f01dcf59da10ec9313345305efc49cfb7186bf99/tests/test_scripts.py#L175

is still actually needed/desirable.

**Comment by kratsg** [comment]
If #1958 is supposed to somehow fix this, that's not clear. There's nothing in `click` that would change the behavior of the python logging. This must have something to do with the `CliRunner` and `logging.basicConfig()` in `src/pyhf/cli/cli.py` somehow, but this test shouldn't depend on the version of `Click`. That's the only way I see this happening...

In fact, for the test failing, we rely on `script_runner` which even has a test for this exact scenario (https://github.com/kvas-it/pytest-console-scripts/blob/a34120fae03022100bfd3ea1968fd55600ddca27/tests/test_run_scripts.py#L309-L323) so something else must be going on.

**Comment by matthewfeickert** [comment]
> If #1958 is supposed to somehow fix this, that's not clear. There's nothing in `click` that would change the behavior of the python logging. This must have something to do with the `CliRunner` and `logging.basicConfig()` in `src/pyhf/cli/cli.py` somehow, but this test shouldn't depend on the version of `Click`.

Looking at https://github.com/scikit-hep/pyhf/pull/1958#issuecomment-1228224581, if you take the installed packages list from any of the failed scheduled versions of the workflow ([fail.txt](https://github.com/scikit-hep/pyhf/files/9434130/fail.txt)) and compare them to what is installed with a manually triggered workflow with ([pass.txt](https://github.com/scikit-hep/pyhf/files/9434133/pass.txt)) the only difference is `click`

```console
$ diff fail.txt pass.txt 
18c18
< Click                   7.0
---
> click                   8.0.0
```

**Comment by kratsg** [comment]
Ok, this is a problem. Because this does indicate that `Click` is parsing the CLI arguments incorrectly if it has colons versus if it doesn't. 

> `FileNotFoundError: [Errno 2] No such file or directory: '/absolute/path/to/config/example_channel.xml'`

should not happen at all. It should be replacing that path to the local path on disk for the file, since the whole point is to test that it's mounting files correctly.

**Comment by matthewfeickert** [comment]
> It should be replacing that path to the local path on disk for the file, since the whole point is to test that it's mounting files correctly.

So seems there is some bug in Click v7 then that got fixed in v8, no? We don't see this in any runs with click `v8.0.0+`.

**Comment by kratsg** [comment]
> > It should be replacing that path to the local path on disk for the file, since the whole point is to test that it's mounting files correctly.
> 
> So seems there is some bug in Click v7 then that got fixed in v8, no? We don't see this in any runs with click `v8.0.0+`.

I can't find a reason for `Click` to impact this though... there's nothing in the release logs. We should confirm?

**Comment by matthewfeickert** [comment]
> I can't find a reason for `Click` to impact this though... there's nothing in the release logs. We should confirm?

I agree there's nothing in the [`click` `v8.0.0` release notes](https://click.palletsprojects.com/en/8.1.x/changes/#version-8-0-0) on this. We could open up a GitHub Discussion, but I'm not sure if we're really going to get any feedback on this soon given that we're going to be asking about release changes from a year ago. (@davidism not sure how you feel about such things in general.)

I'm happy to investigate this, but what are your thoughts @kratsg on merging PR #1958 so that we have a known stable lower bound and then seeing if we can't revert that to get back to a `v7.0` lower bound if there was _no_ bug fix in `click` `v8.0.0`?

**Comment by davidism** [comment]
I can't really tell what's failing here, or how it's related to Click. Just note that Click 7.x and 8.0.x are no longer supported, we only support the latest feature branch, currently 8.1.x.

**Comment by matthewfeickert** [comment]
> Just note that Click 7.x and 8.0.x are no longer supported, we only support the latest feature branch, currently 8.1.x.

That's all the information I needed. Thanks for your time @davidism! (We didn't want you to investigate yourself, just to know if opening a Discussion with our digging into a `v7` release was going to be worth it or not &mdash; now we know it won't be. :+1:)

**Comment by kratsg** [comment]
Problem is that `click` 7.0 and 8.0 changed path types

```
(pyhf-dev) Lord Stark:~/pyhf (master)$ pyhf xml2json --mount test:bar test.py 
((b'/Users/kratsg/pyhf/test', b'bar'),)
(pyhf-dev) Lord Stark:~/pyhf (master)$ pyhf xml2json --mount test:bar test.py 
((PosixPath('/Users/kratsg/pyhf/test'), PosixPath('bar')),)
```

which is the problem. Typehints would catch this change.

**Comment by kratsg** [comment]
The 7.0 behavior is buggy.

**Comment by matthewfeickert** [comment]
> Problem is that `click` 7.0 and 8.0 changed path types
> 
> ```
> (pyhf-dev) Lord Stark:~/pyhf (master)$ pyhf xml2json --mount test:bar test.py 
> ((b'/Users/kratsg/pyhf/test', b'bar'),)
> (pyhf-dev) Lord Stark:~/pyhf (master)$ pyhf xml2json --mount test:bar test.py 
> ((PosixPath('/Users/kratsg/pyhf/test'), PosixPath('bar')),)
> ```
> 
> which is the problem.

Ah okay so we do need to update the lower bound then. I'll note the reason in PR #1958.
