### ISSUE TITLE
Replace old GHA choice input by type: boolean

### ISSUE THREAD

**Issue by Sinclert** [scikit-hep/pyhf#1966]
This issue started as an informal conversation between @matthewfeickert and myself on Twitter.

If I am not mistaken, GitHub recently extended the possible values for the `type` field, when describing workflow parameters. Possible values for this field are: _string_, _choice_, _environment_ and **_boolean_** ([this is the blog post](https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/) where the list was extended).

Therefore, any _choice_ marked input, whose only options are `true` and `false`, can be simplified by stating `type: boolean`. I personally did this in a couple of projects, and this is how it looks like:

<img width="318" alt="Screenshot 2022-08-27 at 17 13 10" src="https://user-images.githubusercontent.com/6978377/187036431-a75d0496-85dc-40cb-b124-df9778371afe.png">

---

I suggest you simplify the syntax of the following workflows:
- [bump-version.yml](https://github.com/scikit-hep/pyhf/blob/master/.github/workflows/bump-version.yml).
- [publish-package.yml](https://github.com/scikit-hep/pyhf/blob/master/.github/workflows/publish-package.yml).

**Comment by matthewfeickert** [comment]
Resolved by PR https://github.com/scikit-hep/pyhf/pull/2480
