### ISSUE TITLE
Include `model.config` property in the `pyhf.pdf.Model` API documentation

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/pyhf#1982]
I would also suggest somehow pointing to `_ModelConfig` from the `pyhf.pdf.Model` page. The `.config` API is not listed there, and it is not particularly intuitive for a user to look at `_ModelConfig` to find out about that `.config` attribute, where it says

> `_ModelConfig` should not be called directly. It should instead by accessed through the `config` attribute of `Model`

Given that `_ModelConfig` implies internal API, I wonder whether all of this page should just live within the `Model` API documentation page? This is where I would expect a user to look for it.

_Originally posted by @alexander-held in https://github.com/scikit-hep/pyhf/pull/1972#pullrequestreview-1095476721_

**Comment by kratsg** [comment]
> Given that `_ModelConfig` implies internal API, I wonder whether all of this page should just live within the `Model` API documentation page? This is where I would expect a user to look for it.

This part requires a larger rewrite of how we set up documentation. We currently set it up with one class per page (autoclass/autodoc). We'll probably change the way we do it in the future. But for now, this can be done by just linking to `_ModelConfig`.
