### ISSUE TITLE
reorg: submodules "lib" "visualization" "cli"

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/pyhf#199]
# Description

Now that we are adding some more advanced features #197 (also discussed in  #174 )

maybe we should further reorganize

```
/__init__.py
/lib (or core?)
  ... current files except commandline.py
/cli
   /commandline.py
/viz
   .. some visualization
```

thoughts @matthewfeickert @kratsg ?

**Comment by kratsg** [comment]
Probably too much for right now, but I dunno. Is this over-optimizing?

**Comment by matthewfeickert** [comment]
I personally like the idea (but I'm biased given what I asked in Issue #174). I agree that this isn't a huge priority, but as I don't have a lot of time right now as is if this is something that could be slowly worked on then if we agree on the structure this could get done.

Thoughts?

**Comment by lukasheinrich** [comment]
just want to make sure we don't mix things too much that have different concerns (with relative imports that jump via `..` would make this easy to track).

e.g. `tqdm` is very nice but also I was a bit iffy adding this as an import into `readxml` since it is only for UI / interactive use (since it has a nice disable feature, I think it's fine in this case)

we could stsart by keeping everything cli related in `commandline.py` and everything viz relates in `visualize.py` and once we need more than two files reorg as above?

**Comment by kratsg** [comment]
> e.g. tqdm is very nice but also I was a bit iffy adding this as an import into readxml since it is only for UI / interactive use (since it has a nice disable feature, I think it's fine in this case)

My other idea was to have a `tqdm` module passed in through the function, but that seemed reaaaaallllly overkill. Also makes things less stateless.



> we could stsart by keeping everything cli related in commandline.py and everything viz relates in visualize.py and once we need more than two files reorg as above?

I think this is the best way forward for now. It's not clear if the `commandline.py` will ever get so complicated or messy that it necessitates a separate submodule, for example. `viz` most definitely will end up getting messy.

**Comment by matthewfeickert** [comment]
The above all sounds good to me, so it seems that we're in agreement. :+1:

**Comment by lukasheinrich** [comment]
mostly done
