### ISSUE TITLE
Setup extra "complete" no longer exists, but is mentioned in contribution docs

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/pyhf#2110]
### Summary

The "complete" setup extra no longer exists, but the contributing docs mention it. Should presumably be replaced by "all"

### Documentation Page Link

https://github.com/scikit-hep/pyhf/blob/main/CONTRIBUTING.md#installing-the-development-environment

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by alexander-held** [comment]
This also affects https://scikit-hep.org/pyhf/development.html.

**Comment by matthewfeickert** [comment]
Yeah, I had left this as is until we figured out how to do developer environments in `hatch` in https://github.com/scikit-hep/pyhf/issues/2096 but I can amend this now and then revise it again if needed.

**Comment by matthewfeickert** [comment]
> Should presumably be replaced by "all"

Not quite. We made `all` to be user facing

https://github.com/scikit-hep/pyhf/blob/2b168b7a04becb0087c7cd614f206df4b6e2d92a/pyproject.toml#L80

while `complete` used to install all the developer dependencies as well. That currently doesn't exist anymore.

**Comment by matthewfeickert** [comment]
Oh, I see that

```console
$ python -m pip install --upgrade "git+https://github.com/scikit-hep/pyhf.git#egg=pyhf[all]"
```

prints out

> DEPRECATION: git+https://github.com/scikit-hep/pyhf.git#egg=pyhf[all] contains an egg fragment with a non-PEP 508 name pip 25.0 will enforce this behaviour change. A possible replacement is to use the req @ url syntax, and remove the egg fragment. Discussion can be found at https://github.com/pypa/pip/issues/11617
