### ISSUE TITLE
pyhf contrib download does not work for EWK 2L2J HEPData entry

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/pyhf#2265]
### Summary

- https://www.hepdata.net/record/116034
- https://atlas.web.cern.ch/Atlas/GROUPS/PHYSICS/PAPERS/SUSY-2018-05/

### OS / Environment

```console
.
```

### Steps to Reproduce

```console
$ pyhf contrib download https://doi.org/10.17182/hepdata.116034 example
```

### Expected Results

Something similar to following https://www.hepdata.net/record/resource/2880059?landing_page=true

```console
$ curl -OJLH "Accept: application/x-tar" https://doi.org/10.17182/hepdata.116034.v1/r34
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   207  100   207    0     0    737      0 --:--:-- --:--:-- --:--:--   739
100   131    0   131    0     0    153      0 --:--:-- --:--:-- --:--:--  5695
100 11.9M  100 11.9M    0     0  2934k      0  0:00:04  0:00:04 --:--:-- 5138k
$ ls
llh_jsons.tar
```

### Actual Results

```console
$ pyhf contrib download https://doi.org/10.17182/hepdata.116034 example
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/pyhf/contrib/utils.py", line 91, in download
    with tarfile.open(
         ^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/tarfile.py", line 1804, in open
    raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
tarfile.ReadError: file could not be opened successfully:
- method gz: ReadError('not a gzip file')
- method bz2: ReadError('not a bzip2 file')
- method xz: ReadError('not an lzma file')
- method tar: ReadError('invalid header')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/pyhf", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pyhf/contrib/cli.py", line 67, in download
    utils.download(archive_url, output_directory, force, compress)
  File "/opt/conda/lib/python3.11/site-packages/pyhf/contrib/utils.py", line 97, in download
    raise exceptions.InvalidArchive(
pyhf.exceptions.InvalidArchive: The archive downloaded from https://doi.org/10.17182/hepdata.116034 is not a tarfile or a zipfile and so can not be opened as one.
```

### pyhf Version

pyhf v0.7.2

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by matthewfeickert** [comment]
@kratsg I think this is more of an issue with how HEPData is doing redirects as if we click on the HistFactory button on https://www.hepdata.net/record/116034 we get redirected to https://www.hepdata.net/record/resource/2880059?landing_page=true and the directions there for the download of the probability model `.tar` file are

> Download via DOI: `curl -OJLH "Accept: application/x-tar" https://doi.org/10.17182/hepdata.116034.v1/r34`

If we do

```
$ pyhf contrib download https://doi.org/10.17182/hepdata.116034.v1/r34 issue-2265
$ ls issue-2265/*.json.tgz | wc -l
38
```

then things work as expected. The reason I think this has to deal with redirects is if I put a `breakpoint()` in at line `90` before the `try` to open the `tarfile`

https://github.com/scikit-hep/pyhf/blob/bd8c21a33b2f3ce8b41ea78cb351eef91c21b92b/src/pyhf/contrib/utils.py#L89-L92

and just visually inspect `response.content` it contains the page source for https://www.hepdata.net/record/ins2072870

![page-source](https://github.com/scikit-hep/pyhf/assets/5142394/76442384-d3c3-4492-86f1-c16cdedaffea)

Though when I look at the `pyhf` `v0.7.2` docs for [`pyhf.contrib.utils.download`](https://pyhf.readthedocs.io/en/v0.7.2/_generated/pyhf.contrib.utils.download.html#pyhf-contrib-utils-download) and [`pyhf contrib download`](https://pyhf.readthedocs.io/en/v0.7.2/cli.html#pyhf-contrib-download) we don't ever show examples of _just_ the DOI url like `https://doi.org/10.17182/hepdata.116034` but always with a version and reference number like `https://doi.org/10.17182/hepdata.116034.v1/r34`. So this at least seems consistent.

Do we have any public examples of us showing only using the DOI url?
