### ISSUE TITLE
Move documentation pages to PyData Sphinx Theme

### ISSUE THREAD

**Issue by melissawm** [scikit-hep/pyhf#2512]
### Summary

Hi all! After talking to @matthewfeickert , I was wondering if you folks are interested in moving to the PyData Sphinx Theme for your documentation pages. I have experimented with it and it would be a very simple PR. The advantage in doing this is that the PyData Sphinx Theme has been doing a number of usability, design and accessibility improvements to the theme, and it is widely adopted by other projects in the ecosystem.

Let me know what you think.

### Additional Information

Here is how it looks with minimal customization:

![Captura de imagem_20240605_102435](https://github.com/scikit-hep/pyhf/assets/3949932/eafc5927-1e40-4656-b2a2-612d6f9126da)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by kratsg** [comment]
lgtm, will you submit a PR?
