### ISSUE TITLE
lumi schema & name property

### ISSUE THREAD

**Issue by andrewfowlie** [scikit-hep/pyhf#2547]
I was looking at the schema, trying to understand which elements are required etc. I noticed that the `lumi` modifier schema gives the name as well as the type to be `{ "const": "lumi" }`

https://github.com/scikit-hep/pyhf/blob/3d26434be836050e334190c212b1db1a6f7650c8/src/pyhf/schemas/1.0.0/defs.json#L115-L122

_If I understand this correctly_, it says that all `lumi` modifiers must be called `lumi`.

Compare this to other modifiers e.g., `shapesys`. 

https://github.com/scikit-hep/pyhf/blob/3d26434be836050e334190c212b1db1a6f7650c8/src/pyhf/schemas/1.0.0/defs.json#L165-L170

here, it seems like the name can be any string you want.

Do I understand this correctly? Is this `lumi` restriction deliberate so that there can only ever be a single `lumi` modifier named `lumi`? This kind of makes sense, although I could imagine wanting to have different `lumi` modifiers, especially if I was including both ATLAS and CMS data. Or is it a copy-paste error since it is the same as the line below it?

**Comment by andrewfowlie** [comment]
Any clarification would be appreciated - I may well have misunderstood something about how the json spec works

**Comment by alexander-held** [comment]
This is similar to the discussion in #2552. Your understanding is correct that the `"lumi"` name is hardcoded. This aligns with the behavior in the ROOT implementation, where the treatment of this modifier is special (and it does not have a dedicated name field). When multiple lumi-type modifiers are needed I would instead recommend using `normsys` modifiers, which allow custom names and implement the same constraint term.
