### ISSUE TITLE
Bug Report: Zenodo isn't updating releases

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#255]
# Description

[Zenodo is stuck on release `v0.0.8`](https://zenodo.org/record/1172961#.W5eGgt0zZhE) and isn't updating along with GitHub/PyPI. 

# Expected Behavior

With every GitHub release Zenodo should be triggered to archive the project and update the DOI.

# Actual Behavior

Zenodo is stuck on release `v0.0.8`.

**Comment by matthewfeickert** [comment]
@lukasheinrich, as you're the only one of us who has access to the diana-hep Zenodo account can you check to make sure nothing has changed on our side before I follow up with the Zenodo team?

**Comment by matthewfeickert** [comment]
The main issue here in my mind is that `v0.0.8` doesn't have @kratsg listed as an author. The rest is just cosmetics, though it would be nice to have a more modern release now that `pyhf` has been cited (c.f. Issue #315).

**Comment by kratsg** [comment]
Isn't it not auto-updating because @lukasheinrich needs to update manually? See #90

**Comment by matthewfeickert** [comment]
I don't think so(?). Zenodo is tracking GitHub and so anytime that we make a tag it should update to a new version. If you go to the "cite all versions" DOI [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1172961.svg)](https://doi.org/10.5281/zenodo.1172961)
 which always shows the latest release it still shows `v0.0.8`. The only thing I can think of is I don't remember when we moved from being under @lukasheinrich's GitHub account to being under the [DIANA-HEP org](https://github.com/diana-hep/). So if it was after February then maybe Zenodo is tracking the wrong thing?

**Comment by matthewfeickert** [comment]
As we have `v0.1.0` out of pyhf it would be nice to update Zenodo, as the DOI [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1169739.svg)](https://doi.org/10.5281/zenodo.1169739) is still pointing to`v0.0.15`.

**Comment by matthewfeickert** [comment]
This should get re-escalated as Zenodo is the primary way that we cite pyhf in papers. We should definitely make a new Zenodo release now that we're part of Scikit-HEP.

**Comment by kratsg** [comment]
we need a zenodo release for last python2 version and for v0.4.0

**Comment by matthewfeickert** [comment]
I have recently got some _very_ helpful information from @slint at Zenodo that

> ...the issue is that the releases that you've made are only git tag pushes, and thus do not create a GitHub release object.

which is correct. I just made (in order) releases for all of the tags we have and they [now appear on Zenodo correctly](https://zenodo.org/search?page=1&size=20&q=conceptrecid:%221169739%22&sort=-version&all_versions=True).

Now the question is can we trigger release creation in our publishing workflow? Or does this need to be done by hand?

**Comment by kratsg** [comment]
https://github.com/actions/create-release

**Comment by matthewfeickert** [comment]
Resolved by #789
