### ISSUE TITLE
Example Notebooks Have Bugs And Dont Run

### ISSUE THREAD

**Issue by dantrim** [scikit-hep/pyhf#325]
# Description

I have a problem running the notebooks in my jupyter-notebook so I ported a [notebook example](https://github.com/diana-hep/pyhf/blob/master/docs/examples/notebooks/multichannel-coupled-normsys.ipynb) into actual python code. The code is also exampled on the pyhf website under "Interval Estimation (Computing Upper Limits on µ)" [here](https://diana-hep.org/pyhf/examples/notebooks/binderexample/StatisticalAnalysis.html).

The model config specification in the abovementioned notebook appears to no longer follow the [JSON spec](https://github.com/diana-hep/pyhf/blob/master/pyhf/data/spec.json) so I first had to re-build the example's model input following the correct specification.

Some of the functions in the example also have bugs. For example, the function "plot_results" has an input parameter "test_mus" but within the function that parameter is *never* used. Rather, the variable defined in the notebook cell "mu_tests" is used. Running the code in python the functions as defined do not work.

# Expected Behavior

What is illustrated in the pre-executed notebooks.

# Actual Behavior

Not what was illustrated in the pre-executed notebooks.

# Thoughts / Questions

Are there any non-notebook examples? I feel that these would be super useful / more relevant for users of the pyhf _library_. How does one create merge requests on notebooks?

Are there examples of JSON model files that are complete and up to date?

**Comment by lukasheinrich** [comment]
Thans @dantrim, these were very early notebooks and apparently are not covered by our tests (we do try to tests the notebooks using papermill). I'll have a look and get back to you.

**Comment by lukasheinrich** [comment]
@matthewfeickert can you check what the current coverage of the notebooks looks like?

**Comment by dguest** [comment]
Hi, I'd like to mirror @dantrim's request for non-notebook examples. Sometimes it's easier to debug a python script with fewer dependencies. I would imagine we'll also get lots of grad students with dependency issues so if we can have an example to test the library with the absolute minimum requirements it would be nice.

**Comment by matthewfeickert** [comment]
Thanks very much for the Issue, @dantrim. :+1:

> we do try to tests the notebooks using papermill

Indeed, but as 

> these were very early notebooks

we haven't taken the time so go back and update most of them beyond the ones that we use as major examples. As such, they are also not covered in the CI by `papermill` (you'll note at the moment we [actually have very sparse coverage there](https://github.com/diana-hep/pyhf/blob/d470ae07145e53d7dc270e31fbdb6e479e09ed38/tests/test_notebooks.py)).

I would suggest that as all of us are busy working on other parts of `pyhf` at the moment we remove the examples that are not in the CI from being on the website until we have time to rewrite them and clean them up. @lukasheinrich @kratsg thoughts?

**Comment by lukasheinrich** [comment]
@dguest yeah, we do have the one in the README, but I agree, we should perhaps add some more.

**Comment by lukasheinrich** [comment]
we are very close to merging a massive PR, and I think after that we can try to settle down, clean up the examples and cut a new release

**Comment by matthewfeickert** [comment]
> Are there any non-notebook examples? I feel that these would be super useful / more relevant for users of the `pyhf` library

@dantrim @dguest Can you make a new Issue for this?

> How does one create merge requests on notebooks?

This can be tricky. At the moment I would suggest just treating it like normal code but that your diff will be huge. Use `nbdime` to sanely understand what is changing.

**Comment by matthewfeickert** [comment]
This is temporarily mitigated, but **not** resolved, by PR #326. This will need to get followed up on and resolved after PR #285 is done.

**Comment by matthewfeickert** [comment]
I'm pretty sure this has been resolved now, so I'm going to close this, but am willing to reopen if there are people who feel otherwise.

With regards to @dguest's point about non-notebook examples in https://github.com/scikit-hep/pyhf/issues/325#issuecomment-431356915, while we don't have a directory full of script examples I think this is addressed through https://pyhf.github.io/pyhf-tutorial/ where we have a user guide now, which is hopefully better than copy-paste scripts.

Also any notebook can be converted to a script with `jupytext`'s CLI API with

```
jupytext --to py <notebook path>
```
