### ISSUE TITLE
Fix ShapeSys masking

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/pyhf#404]
# Description

https://github.com/diana-hep/pyhf/blob/49f30cd52bd543e67b1464d0ce916e15014a6f5b/pyhf/modifiers/shapesys.py#L106-L119

is a bit hacky right now by letting `==0` mean that the bin does not participate. Should be masking instead.

# Expected Behavior

Expect to do something more like

```
factors = nom_sq / unc_sq
```

and then mask `factors` after the fact.

# Actual Behavior

No masking is happening.

# Steps to Reproduce

See the code.

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by lukasheinrich** [comment]
the issue here is not really the masking but two separate things

```
            unc_nom = default_backend.astensor(
                [x for x in uncert_this_mod[:, :, :] if any(x[0][x[0] > 0])]
            )
            unc = unc_nom[0, 0]
            nom = unc_nom[0, 1]
```

this code assumes that len(unc_nom) == 1  since shapesys cannot be shared, we are sure that unc_norm is not >1 but it can be `len(unc_nom)==0` since some samples might have a declared uncertainty of "0"

then later we have the issue here:

```
            numerator = default_backend.where(
                unc_sq > 0, nom_sq, default_backend.zeros(unc_sq.shape)
            )
            denominator = default_backend.where(
                unc_sq > 0, unc_sq, default_backend.ones(unc_sq.shape)
            )

            factors = numerator / denominator
            factors = factors[factors > 0]
```

where this becomes an issue when the nominal data for the sample is zero..

both cases typically happen at the same time when 


```
                {
                    "data": [
                        0.0
                    ],
                    "modifiers": [
                        {
                            "data": [
                                0.0
                            ],
                            "name": "shape_fakes_stat_fakes_SRee_eMLLc_hghmet_obs_cuts",
                            "type": "shapesys"
                        }
                    ],
                    "name": "fakes"
                },
```

**Comment by kratsg** [comment]
just dumping this in for now

```
$ python
Python 3.7.3 (default, Mar 27 2019, 09:23:32) 
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> setup = """
... import json, numpy as np
... data = np.array(json.load(open('uncert_this_mod.json')))
... """
>>> timeit.timeit('[x for x in data if any(x[0][x[0]>=0])]', setup=setup, number=10000)
0.19244455399999083
>>> timeit.timeit('data[np.sum(data[:,0]>=0, axis=1)==1,:,:]', setup=setup, number=10000)
0.13176023799999825
```
