### ISSUE TITLE
Drop Python 2.7 support

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#469]
# Description

Given 

> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.

can be viewed as something to look forward to (so we can be free to Travis CI issues among other things), pyhf should drop Python 2.7 support in the last week of December 2019.

Once this is done, a future Issue should be created to move all print statements to using f-strings (c.f. [PEP 498 -- Literal String Interpolation](https://www.python.org/dev/peps/pep-0498/)).

**Comment by lukasheinrich** [comment]
hm, as long as we don't have a blocking reason to drop it I think i'd still keep it. Given that all CERN Centos 7 still has python 2.7 as its default. I agree in general with pushing for depreciation and perhaps we won't *support* 2.7 but we shouldn't intentionally break it either

**Comment by matthewfeickert** [comment]
> Given that all CERN Centos 7 still has python 2.7 as its default. I agree in general with pushing for depreciation and perhaps we won't _support_ 2.7 but we shouldn't intentionally break it either

My main motivation for trying to force people to use Python 3 is related to this as I would guess (though maybe you know more than me?) that CERN will be keeping Python 2.7 alive for a long time to come, and it might be easier to make a clean break. While I don't think that having pyhf working on Python 2.7 in the future is a _bad_ thing, it seems almost inevitable that if we drop testing it and drop support then as we continue to develop we'll break something Python 2.7 related. If part of Python 2.7 is broken, and we aren't going to fix it, then why not go all in on Python 3? Or would you suggest that we just wait until we get our first report of Python 2.7 being broken?

**Comment by kratsg** [comment]
We are already using dependencies that are sunsetting/dropping python 2.7 support. It's going to get _very_ difficult to start maintaining things if we keep it up...

**Comment by lukasheinrich** [comment]
yeah I think if we use core components in numpy that will need py3 or similar i'm fine .. I guess what I'm saying is I might reconsider to break 2.7  if it's only due to f-strings

**Comment by matthewfeickert** [comment]
>  I guess what I'm saying is I might reconsider to break 2.7 if it's only due to f-strings

Sure. Perhaps a compromise where we drop support for Python 2.7 but then keep testing it in the CI and then once we find that the CI breaks on it due to Python 2 vs. 3 issues/dependencies we can move to f-strings?

**Comment by kratsg** [comment]
Circular imports are currently an issue because python 2 handles it differently than python 3.
