### ISSUE TITLE
Consider adding preferred BibTeX citation to docs

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#478]
# Description

As was recently discussed, the [BibTeX citation that is automatically generated by Zenodo](https://zenodo.org/record/3245478/export/hx) is probably not the one that we want people who are citing pyhf to use. In addition to seeing how much control we have over the Zenodo citation, it might be worthwhile to add a preferred BibTeX citation entry to the docs under "[Use and Citations](https://diana-hep.org/pyhf/citations.html)" to make it clear to people how they should cite pyhf.

Perhaps something like

```
@software{pyhf,
  author = "{Heinrich, Lukas and Feickert, Matthew and Stark, Giordon}",
  title = "{pyhf}",
  version = {0.1.0},
  doi = {10.5281/zenodo.1169739},
  url = {https://github.com/diana-hep/pyhf},
  month = apr,
  year = 2019,
}
```

**Comment by kratsg** [comment]
We should ping the Zenodo team about supporting a customized version...
