### ISSUE TITLE
NP ranking

### ISSUE THREAD

**Issue by dantrim** [scikit-hep/pyhf#500]
It is not clear how I would use the current schema or pyhf utilities to calculate the impact of the various NP, by making, for example, an NP ranking plot. An example plot of this is Figure 19 of [this analysis](https://cds.cern.ch/record/2266094) (on page 44 of the document).

For this, once needs to fix a specific NP at its +/-1 sigma value and then re-do the entire fit and then determine the effect on the POI.

There seems to be the ability to fix a modifier, but that is within the schema itself and it seems to be fixing it to the pre-fit values. The fact that it is within the schema seems to make it hard to automate/script this.

Any ideas/hints?

**Comment by lukasheinrich** [comment]
Hi @dantrim the optimzers (e.g. minuit) have an option to fix some parameters, but we are not exposing this in the pyhf APIs yet. I discussed this recently with @kratsg and we will extend the API accordingly so that individual parameters can be fit to a given value.

I'm curious. Were you able to reproduce the toplevel limit results? (we've been mostly focusing on this, but I agree we should provide APIs for diagnostics)

**Comment by kratsg** [comment]
Hi @dantrim , everything @lukasheinrich said is right. The current focus has been on the fundamental CLs (obs/exp) results. Now that we've gotten the API and spec down and we're reasonably happy with the speed -- we're moving on to things like this.

To help us a bit, as you're a user, do you have an idea of how you expect to run it? Do you prefer it to be a bit more high-level like:

```
m = workspace.model()
m.rank_nps()
```

or do you prefer something more low-level like

```
results = {}
for np in m.config.parameters:
  results[np][1.0] = m.fit(...., fixed_params=[(np, 1.0)]
  results[np][-1.0] = m.fit(...., fixed_params=[(np, -1.0)]
```

I see benefits in both ways. I usually prefer the latter as this doesn't hide too much magic from new users, so they get a better idea of what is actually being done, but...

**Comment by lukasheinrich** [comment]
I kinda am leaning towards having pyhf only support the basic operation of setting parameters constant .. it should not need to know about what a "ranking plot" is. I'd happily leave this to a higher level library (incl visualization etc)

**Comment by matthewfeickert** [comment]
Yeah, this seems like something that we would ideally do in `pyhf-viz`. @dantrim, any input on expected API would be quite welcome.

**Comment by beojan** [comment]
Have there been any changes on this?
Also, unless I'm looking in the wrong place, it doesn't seem to be possible to get uncertainties on the fit values from `pyhf.optimizer.(un)constrained_bestfit`.

**Comment by kratsg** [comment]
> Also, unless I'm looking in the wrong place, it doesn't seem to be possible to get uncertainties on the fit values from `pyhf.optimizer.(un)constrained_bestfit`

So there is a way doing something like

```python
    workspace = pyhf.Workspace(spec)
    model = workspace.model()   
    data = w.data(m)

    result = minuit_fit(
        pyhf.utils.loglambdav,
        constraints,
        data,
        model,
        model.config.suggested_init(),
        model.config.suggested_bounds(),
        return_errors=True,
    )   
    values, errors = result[:, 0], result[:, 1]
    fitresult = {}
    for par_name, par_info in model.config.par_map.items():
        value = result[par_info["slice"]].tolist()
        error = result[par_info["slice"]].tolist()
        if len(value) == 1:
            fitresult[par_name] = {"val": value[0], "err": error[0]}
```

**Comment by alexander-held** [comment]
#653 implemented an example for this in `pyhf/docs/examples/notebooks/ImpactPlot.ipynb`
