### ISSUE TITLE
Write JOSS Submission

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#502]
# Description

Given conversations with @labarba at SciPy 2019 it seems that pyhf would be a good candidate for a [JOSS paper](https://joss.theoj.org/). Given @cranmer's good experience with this for carl [![DOI](http://joss.theoj.org/papers/10.21105/joss.00011/status.svg)](https://doi.org/10.21105/joss.00011) it seems if we clean up and finish a few of the docstrings then we would be in good shape to submit for a review (once we finish up the other publication process we have ongoing).

The [carl paper submission review](https://github.com/openjournals/joss-reviews/issues/11) might be a good premeptive checklist for this.

**Comment by kratsg** [comment]
Also see things that we did for root_numpy here (https://github.com/scikit-hep/root_numpy/issues?q=is%3Aissue+joss+is%3Aclosed+label%3AJOSS) which was under scikit-hep at the time.

**Comment by matthewfeickert** [comment]
Today in the SciPy 2020 Maintainers Track discussion I asked

> The pyOpenSci website mentions that "Any package that passes the pyOpenSci review and is within scope for JOSS can be fast-tracked through the JOSS review process." Would you recommend that people attempt to go through pyOpenSci review before submitting to JOSS to make it easier for the JOSS reviewers?

 @kyleniemeyer (who was presenting on behalf of JOSS) thought this was probably a good idea. So maybe we should just do the work once and a bit extra to get a [PyOpenSci](https://www.pyopensci.org/) review and then submit to JOSS.

**Comment by matthewfeickert** [comment]
FWIW, I think that trying to get something done with pyOpenSci is going to take too long, and we should just write up a JOSS paper and get it out. I'll take point on this and try to get something going with JOSS this weekend.

**Comment by cranmer** [comment]
Sounds like a good idea. pyhf is in very good shape for a JOSS paper
