### ISSUE TITLE
CLs plot displayed in ShapeFactor example does not match runtime plot

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#579]
# Description

The CLs plot for the [ShapeFactor example in the docs](https://github.com/diana-hep/pyhf/blob/d9a9ad13fbb6336a73ce9a6d53a6c044f8807a49/docs/examples/notebooks/ShapeFactor.ipynb) is quite different from the plot that is get when the notebook is currently run.

| **Docs** | **Binder on c0d42f8**        |
|---------|------------------|
| ![In_docs](https://user-images.githubusercontent.com/5142394/65402580-ecd82f80-dd94-11e9-9fe5-84f8565ad4de.png) | ![in_binder](https://user-images.githubusercontent.com/5142394/65402581-f2357a00-dd94-11e9-83c9-d6767893dfea.png) |

I'm not sure yet when this change happened ([obviously sometime since PR 341](https://github.com/diana-hep/pyhf/commits/master/docs/examples/notebooks/ShapeFactor.ipynb)) but this should be understood and get addressed in the future, as the plots on the webpage should be what the user gets when they run the code.

# Expected Behavior

The plots in the documentation should match those generated.

# Actual Behavior

The observed CLs values vary greatly.

# Steps to Reproduce

Run the `ShapeFactor` notebook.

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by iokarkan** [comment]
I stumbled upon this issue as well, coming into pyhf (using pyhf==0.5.4)

Looking a bit more into it, there are differences in the values of pdf.expected_data(init_pars) as well as the post-fit parameter values.

```print('expected data: {}'.format(pdf.expected_data(init_pars)))

unconpars = pyhf.infer.mle.fit(data, pdf)
print(f'parameters post unconstrained fit: {unconpars}')
```

returns

```
expected data: [100. 100. 120.  90.]  
parameters post unconstrained fit: [3.22420201 1.84054498 2.66429351]
```
which is different to the notebook where: `expected data: [120.  90. 100. 100.]`
It seems that in Runtime Control Region expected data is displayed first, whereas the opposite happens in the notebook.

**Comment by kratsg** [comment]
So there is indeed some sort of bug in the plotting that somehow depends on the ordering of the channels:

```
data: [220.0, 230.0, 200.0, 300.0]
channels: ['control', 'signal']
expected data: [100. 100. 120.  90.]
```

which shouldn't happen.

**Comment by kratsg** [comment]
Indeed, the issue is here

<img width="502" alt="Screen Shot 2021-01-07 at 7 31 42 PM" src="https://user-images.githubusercontent.com/761483/103959935-097daf80-511f-11eb-8b21-763cccd0c8ca.png">

**Comment by matthewfeickert** [comment]
@iokarkan This should be resolved now. Thanks for following up with us here!
