### ISSUE TITLE
Inconsistency in CLs definition in hypotest

### ISSUE THREAD

**Issue by dantrim** [scikit-hep/pyhf#601]
If I look at the [hypotest docs](https://diana-hep.org/pyhf/_generated/pyhf.utils.hypotest.html), it seems to me that what is called `p_b` is incorrect. In the docs just linked to, you can see that `CLb = 1 - p_b = 1 - \int_{-infinity}^{q_obs} f(q|b) dq`, which appears to be defining `p_b` as if it were a _left _tailed__ probability, which it is not. All p-values, including `p_b`, should be defined, I believe, as `p_b = \int_{q_obs}^{+infinity} f(q|b) dq`. 

If I look at the implementation of the `pvals_from_teststat` methods [here](https://github.com/diana-hep/pyhf/blob/d9a9ad13fbb6336a73ce9a6d53a6c044f8807a49/src/pyhf/utils.py#L171),

https://github.com/diana-hep/pyhf/blob/d9a9ad13fbb6336a73ce9a6d53a6c044f8807a49/src/pyhf/utils.py#L171

 the quantity with variable name `CLb` is given as `1 - CDF(q)`, which is actually `p_b` (using the right-tailed p-value definition). And so, the [CLs value](https://github.com/diana-hep/pyhf/blob/d9a9ad13fbb6336a73ce9a6d53a6c044f8807a49/src/pyhf/utils.py#L172) 

https://github.com/diana-hep/pyhf/blob/d9a9ad13fbb6336a73ce9a6d53a6c044f8807a49/src/pyhf/utils.py#L172

should be corrected as `CLs = CLsb / (1-CLb)`, where I use the same variable name of `CLb` as [here](https://github.com/diana-hep/pyhf/blob/d9a9ad13fbb6336a73ce9a6d53a6c044f8807a49/src/pyhf/utils.py#L197), 

https://github.com/diana-hep/pyhf/blob/d9a9ad13fbb6336a73ce9a6d53a6c044f8807a49/src/pyhf/utils.py#L197

which is _not_ what CLb is in the literature, at least not how it is defined when constructing CLs.

I think the implementation in `pvals_from_teststat` is taken from the discussion in the [asymptotics paper](https://arxiv.org/abs/1007.1727) from the discussion based on the Tevatron test statistic, which does not follow the same behavior as the profile likelihood ratio test statistic we use. But who knows, because I argue that Equation 76 abuses notation like nobody's business.

Let me know if I'm misinterpreting anything! I was just going through the [implementation](https://github.com/diana-hep/pyhf/blob/d9a9ad13fbb6336a73ce9a6d53a6c044f8807a49/src/pyhf/utils.py#L171) and the fact that the mathematical form for CLsb and CLb were the same

https://github.com/diana-hep/pyhf/blob/d9a9ad13fbb6336a73ce9a6d53a6c044f8807a49/src/pyhf/utils.py#L170-L171

 caught my eye.

**Comment by dantrim** [comment]
I was trying to dig around for Eilam's statistics lecture series that he gave at CERN a few years ago, detailing all of this. On indico found a [set of slides](https://indico.cern.ch/event/687487/attachments/1639490/2617187/Statistics_CERN_2018_Part2_.pdf#search=Eilam%20Gross) that looked similar. If you look at Slide 74, you will see an expression for what he calls `p_{\mu}^{\prime}`, which should actually be called CL_s [1], is given by `(1 - CDF[ sqrt(q_mu) ] )/ ( CDF[ sqrt(q_muA) - sqrt(q_mu) ])`, which is inconsistent with the hypotest implementation in pyhf. I would check with the asymptotics people to confirm.

The chi-square asymptotic formulae do not go negative, and "less compatibility with the background only hypothesis" is for larger values of qmu, which is the opposite behavior motivating Equations 75 and 76 in the [asymptotics paper](https://arxiv.org/abs/1007.1727).


[1] notation abuse abounds in the asymptotics literature

**Comment by lukasheinrich** [comment]
hi @dantrim 

i'll review the docstrings but I just wnated to give you a small notebook to see where this inversion of tail direction comes from. For q_mu and q_mu tilde test stats there is a definite "signal direction" in the test statistic (towards zero) which you can connect to the normal distributions of the best fitted mu (from wald's theorem)

<img width="536" alt="screenshot" src="https://user-images.githubusercontent.com/2318083/66188513-b3060380-e687-11e9-87d7-6b848af4c76b.png">

**Comment by dantrim** [comment]
Hi @lukasheinrich , I think I would need to see a notebook and explanation. What you have there doesn't tell me much. As far as I understand, an increase in mu (incompatibility with null hypothesis) leads to increase in qmu?

Looking into the [RooStats implementation](https://root.cern.ch/doc/v608/classRooStats_1_1AsymptoticCalculator.html#a33f5b0c5ccd487cdfa482b3c9108351b), there are two versions of CLs depending on whether `BackgroundIsAlt'. By default `BackgroundIsAlt = False`, and the CLs values are computed as:

1. `CLs(BackgroundIsAlt = False, ROOSTATS) = CDF( sqrt(qmu_A) - sqrt(qmu) ) / (1 - CDF(sqrt(qmu))`
2. `CLs(BackgroundIsAlt = True, ROOSTATS) = (1 - CDF( sqrt(qmu) ) ) / ( CDF( sqrt(qmu_A) - sqrt(qmu)))`

The CLs computation done in pyhf's [hypotest](https://github.com/diana-hep/pyhf/blob/d9a9ad13fbb6336a73ce9a6d53a6c044f8807a49/src/pyhf/utils.py#L131) is:

`CLs(pyhf) = ( 1 - CDF( sqrt(qmu)) ) / ( 1 - CDF( sqrt(qmu) - sqrt(qmu_A) ) )`

Just doing a blind comparison on the implementations, and assuming the notations are the same, the pyhf does not match with either of RooStats'.

**Comment by matthewfeickert** [comment]
> By default `BackgroundIsAlt = False`, and the CLs values are computed as:
> 
> 1.
> ```c++
> CLs(BackgroundIsAlt = False, ROOSTATS) = CDF( sqrt(qmu_A) - sqrt(qmu) ) / (1 - CDF(sqrt(qmu))
> ```
> 
> 2.
> ```c++
> CLs(BackgroundIsAlt = True, ROOSTATS) = (1 - CDF( sqrt(qmu) ) ) / ( CDF( sqrt(qmu_A) - sqrt(qmu)))
> ```
> 
> The CLs computation done in pyhf's [hypotest](https://github.com/diana-hep/pyhf/blob/d9a9ad13fbb6336a73ce9a6d53a6c044f8807a49/src/pyhf/utils.py#L131) is:
> 
> `CLs(pyhf) = ( 1 - CDF( sqrt(qmu)) ) / ( 1 - CDF( sqrt(qmu) - sqrt(qmu_A) ) )`
> 
> Just doing a blind comparison on the implementations, and assuming the notations are the same, the pyhf does not match with either of RooStats'.

The implementation is the same as the `CLs(BackgroundIsAlt = True, ROOSTATS)`, no? For the Normal distribution's CDF

```
CDF(-x) = 1 - CDF(x)
```

so

```
CDF( sqrt(qmu_A) - sqrt(qmu)) = 1 - CDF( sqrt(qmu) - sqrt(qmu_A) )
```

**Comment by dantrim** [comment]
Hi @matthewfeickert 
Maybe I am missing something, but I am not sure where the assumption on the distributions being symmetric is coming from? The sampling distributions of the qmu (i.e. f(qmu|mu')) are not symmetric...

**Comment by matthewfeickert** [comment]
> I am not sure where the assumption on the distributions being symmetric is coming from? The sampling distributions of the qmu (i.e. f(qmu|mu')) are not symmetric...

You're correct that `f(qmu|mu')` isn't symmetric, as it is  chi-square distributed. However, for the CLs we're taking the ratio of probabilities _which are able to be efficiently calculated from the Normal distribution's CDF_ given the shift of the noncentrality parameter (q_μA = Λ) ([arXiv:1007.1727](https://arxiv.org/abs/1007.1727) related Eqs. 35, 50, 57, 59, 65, 67), which is what I was trying to get across in the [`pyhf.utils.pvals_from_teststat` docstring](https://diana-hep.org/pyhf/_generated/pyhf.utils.pvals_from_teststat.html):

![pvals_from_teststat_docstring](https://user-images.githubusercontent.com/5142394/66215496-f2eadc00-e6c3-11e9-8eea-23fa20c2cbcf.png)
