### ISSUE TITLE
Add smoketests to make sure that the public API is stable

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#605]
# Description

As a (somewhat redundant) set of reliability tests, tests that directly test common usages of the public API could be added. This could verify that we don't merge anything that changes the public API without also having to cut a new release.

**Comment by matthewfeickert** [comment]
cc @lukasheinrich for further comments given discussions on 2019-10-09

**Comment by kratsg** [comment]
> This could verify that we don't merge anything that changes the public API without also having to cut a new release.

This doesn't really make sense. You can merge whatever you want -- but you can't cut a new release without checking if the API is affected (and if it is, you just do a major/minor).

**Comment by lukasheinrich** [comment]
@kratsg that was exactly the idea.. if master has a diff with this test module it means we need a new release.. i just want to automate the  decision without manually keeping track whether we change the API or not

**Comment by kratsg** [comment]
> @kratsg that was exactly the idea.. if master has a diff with this test module it means we need a new release.. i just want to automate the decision without manually keeping track whether we change the API or not

Ahh, so it's just a test we allow to fail that we cannot fix/update until after we submit a new release -- or we fix it before a new release?

**Comment by matthewfeickert** [comment]
> Ahh, so it's just a test we allow to fail that we cannot fix/update until after we submit a new release -- or we fix it before a new release?

I'm not sure if this is a good answer, but I think it depends. We don't really have a release schedule, so I think this would be easier to answer if we did. If we're working through multiple PRs to try and work on a large change and we change the API in one of them, then presumably the project we're working on would be nice to have in an upcoming release. However, we might also have quite a few features added that we still want to distribute under the old API for people. So I think we would cut a new patch release from the pre-API change code (ex. `v1.1.1` → `v1.1.2`) to give a final release with the old API, and then once the feature we want is in make another minor/major release (ex. `v1.1.2` → `v1.2.0`) &mdash; depending on how big of an API change &mdash; which might be very soon after.
