### ISSUE TITLE
Use pathlib over os.path

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#614]
# Description

After Issue #469 is resolved, pyhf will be Python 3.6 or higher. At this point, it is possible to then use `pathlib` instead of `os.path` which is generally nice.

Examples and discussions of why this is preferred can be seen in Trey Hunner's post on the subject: [Why you should be using pathlib](https://treyhunner.com/2018/12/why-you-should-be-using-pathlib/)

**Comment by kanishk16** [comment]
I'm currently working on this issue and just wanted to know some preferences for the code practices: 

1. `Path(specdir).joinpath('{0:s}_{1:s}.xml'.format(resultprefix, channelspec['name'])` or
2. `Path(specdir) / '{0:s}_{1:s}.xml'.format(resultprefix, channelspec['name'])`

As the pathlib provides overloading of `/` to be used in place of `.joinpath()`

**Comment by kratsg** [comment]
I strongly prefer option 1. I would also encourage f-strings simultaneously:

`Path(specdir).joinpath(f'{resultprefix}_{channelspec["name"]}.xml')`

**Comment by matthewfeickert** [comment]
Yeah, now that pyhf is Python 3 only I think there is no harm in using f-strings wherever we can.

**Comment by kanishk16** [comment]
Some issues came into light while running the tests for the changes I made. As per [the docs](https://docs.python.org/3.7/library/pathlib.html), 
> Spurious slashes and single dots are collapsed, but double dots ('..') are not

This specifically leads to errors in cases where the path involves either a leading or trailing periods.

 ```  
    pyhf.readxml.uproot.open.assert_called_once_with(
         os.path.join("validation/xmlimport_input", "./data/example.root")
        )
E       AssertionError: Expected call: open('validation/xmlimport_input/./data/example.root')
E       Actual call: open('validation/xmlimport_input/data/example.root')
```

I believe the only workaround is to keep using `os.path.join` but then using 'pathlib' only for some scripts would not be preferred (would like to know if any other way that might have been missed).

**Comment by kratsg** [comment]
Those tests could be improved to use `pathlib` as well:

```
$ python
Python 3.7.3 (default, Mar 27 2019, 09:23:32) 
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathlib
>>> pathlib.Path("validation/xmlimport_input").joinpath("./data/example.root")
PosixPath('validation/xmlimport_input/data/example.root')
>>> import os
>>> os.path.join("validation/xmlimport_input", "./data/example.root")
'validation/xmlimport_input/./data/example.root'
>>> exit()
(pyhf) $ ls ~/pyhf/validation/xmlimport_input/./data/example.root
-rw-r--r-- 1 kratsg 5.0K Oct 16  2018 /Users/kratsg/pyhf/validation/xmlimport_input/./data/example.root
(pyhf) $ ls ~/pyhf/validation/xmlimport_input/data/example.root
-rw-r--r-- 1 kratsg 5.0K Oct 16  2018 /Users/kratsg/pyhf/validation/xmlimport_input/data/example.root
```

as you can see, it should work even better using `pathlib` everywhere.
