### ISSUE TITLE
MINUIT optimizer gives error: missing 1 required positional argument: 'par_bounds'

### ISSUE THREAD

**Issue by beojan** [scikit-hep/pyhf#619]
# Description

The MINUIT optimizer gives the error `missing 1 required positional argument: 'par_bounds'`

# Expected Behavior

The MINUIT optimizer performs the (un)constrained fit as requested.

# Actual Behavior

An error is printed:
```
TypeError: unconstrained_bestfit() missing 1 required positional argument: 'par_bounds'
```

# Steps to Reproduce

`pyhf` from git installed in a virtualenv with Python 3.7.4. 

Backend set with
```python
pyhf.set_backend(pyhf.tensor.numpy_backend(), pyhf.optimize.minuit_optimizer)
```

Then the fit is run:
```python
postfit_params = pyhf.optimizer.unconstrained_bestfit(
    pyhf.utils.loglambdav, w.data(m), m, prefit_params, bounds
)
```

# Checklist

- [ ] Run `git fetch` to get the most up to date version of `master`
- [ ] Searched through existing Issues to confirm this is not a duplicate issue
- [ ] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by kratsg** [comment]
You didn't create an optimizer object when you set backend:

```
pyhf.set_backend(pyhf.tensor.numpy_backend(), pyhf.optimize.minuit_optimizer())
```

**Comment by kratsg** [comment]
Going to close this. Reopen if it's still an issue.
