### ISSUE TITLE
Write proceedings for CHEP 2019 talk

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#658]
# Description

Information about CHEP proceedings can be found in [these closing slides](https://indico.cern.ch/event/773049/contributions/3589995/) on page 4, including a link to a template. The template is also attached there as [`epj-woc-latex.zip`](https://indico.cern.ch/event/773049/contributions/3589995/attachments/1940588/3217543/epj-woc-latex.zip). (Thanks for pointing these to me @alexander-held)

- The deadline for submitting your papers is **February 14, 2020**

Also a request from @pelmer:

> Please do write the proceedings and (also very important) do not forget to acknowledge support from the IRIS-HEP project (and any other grants supporting your work) in the Acknowledgements section of the paper. In addition, please note that you should publish the proceedings in the arXiv at the same time you submit them to CHEP. Please see https://iris-hep.org/docs/acknowledgements for some notes on these latter two items.

---

Also [CHEP 2019 group photo](http://www.chep2019.org/images/chep2019_group_photo_hires.jpg) :slightly_smiling_face:

**Comment by matthewfeickert** [comment]
This needs to get done by this Friday for internal review. If I take lead on this can @lukasheinrich and @kratsg review it?

**Comment by kratsg** [comment]
> This needs to get done by this Friday for internal review. If I take lead on this can @lukasheinrich and @kratsg review it?

ok

**Comment by matthewfeickert** [comment]
This is now being done over on GitLab: https://gitlab.cern.ch/feickert/chep-2019-proceedings/

**Comment by matthewfeickert** [comment]
This is resolved by [ATL-COM-SOFT-2020-020](https://cds.cern.ch/record/2706650).

**Comment by kratsg** [comment]
thanks a lot dude :)

**Comment by matthewfeickert** [comment]
>Dear Dr Matthew Feickert,
>
>We are pleased to inform you that we have received your manuscript. It has been registered under the Reference epjconf200196.
>We will inform you of the editorial decision as soon as possible.
>
>With best regards,
>The Editorial Team

and with that I think we are finished with our CHEP 2019 proceedings. Well done 'gents. :beers:

**Comment by kratsg** [comment]
We should add this to scikit-hep/pyhf.

**Comment by matthewfeickert** [comment]
> We should add this to scikit-hep/pyhf docs.

:100:% agree once we have a proper citation from them.

**Comment by matthewfeickert** [comment]
> > We should add this to scikit-hep/pyhf docs.
> 
> % agree once we have a proper citation from them.

We now do: [![DOI](https://zenodo.org/badge/DOI/10.1051/epjconf/202024506017.svg)](https://doi.org/10.1051/epjconf/202024506017)
