### ISSUE TITLE
Use strings of backend names for set_backend

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#671]
# Description

At the moment we set the tensor backend by passing an object:

```python
import pyhf
pyhf.set_backend(pyhf.tensor.pytorch_backend())
```

however, it would be nicer and easier for new users to just set the backend through a string

```python
import pyhf
pyhf.set_backend("pytorch")
```

There is the obvious catch on the fact that as long as TensorFlow v1 is used then the session needs to be managed. This will go away when TensorFlow v2 is adopted, but a somewhat inelegant solution that shouldn't affect anything is to add a kwarg of `_session` that defaults to `None`

```python
import pyhf
import tensorflow as tf
sess = tf.compat.v1.Session()
pyhf.set_backend("tensorflow", _session=sess)
```

@kratsg @lukasheinrich What are your thoughts on this? I currently have a branch that is passing CI with all of this implemented, so if you are in favor I can open a PR on it and we can go from there.

I don't have a solution to how one would also incorporate something similar for the optimizer choices at the moment as they can have args associated with themselves, so that still looks ugly

```python
import pyhf
pyhf.set_backend("numpy_minuit", pyhf.optimize.minuit_optimizer(verbose=True))
```

**Comment by kratsg** [comment]
The reason we do it this way is because anyone can make up their own backend and pass it through the `set_backend()` code.

**Comment by matthewfeickert** [comment]
> The reason we do it this way is because anyone can make up their own backend and pass it through the `set_backend()` code.

Sure. As from another chat I know that you are also in favor of the idea of allowing either string or objects to be valid inputs then perhaps a signature with something like

```python
def set_backend(backend, custom_optimizer=None, _session=None, custom_backend=False):
     ...
```

where `backend` can be either `str` or a pyhf tesnor backend object, and `custom_backend=True` must be passed if a user wants to use one they developed?
