### ISSUE TITLE
Python 3 base image for Docker image build

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#692]
# Description

We will be dropping Python 2.7 at the end of the year, but that also means that our current Docker image is going to fail in the build as the base image of `alectolytic/scipy` is Python 2.7. So we will need to find an Alpine image with Python 3 and SciPy before the end of December.

@lukasheinrich Do you know of one?

**Comment by lukasheinrich** [comment]
https://github.com/publysher/docker-alpine-scipy ?

**Comment by matthewfeickert** [comment]
> https://github.com/publysher/docker-alpine-scipy ?

It is too old, but I can submit a PR to them to get it more current.
