### ISSUE TITLE
Add visualization tests for contrib module

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#705]
# Description

First brought up in PR #694, we should have tests for the visualization code.

@lukasheinrich and @kratsg have already suggested the following leads:
- [Unit Testing Python data visualizations](https://towardsdatascience.com/unit-testing-python-data-visualizations-18e0250430)
- [Matplotlib: Writing an image comparison test](https://matplotlib.org/3.1.1/devel/testing.html#writing-an-image-comparison-test)

**Comment by lukasheinrich** [comment]
was eventually already added by #694
