### ISSUE TITLE
Add CI to tag Docker images for releases

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#716]
# Description

There should be a tagged Docker image for each release that is on PyPI to make it easy for a user to get any release they want in a Docker image. This can be achieved much more easily through CI on pyhf's end then trying to schedule this through the automated builds on Docker Hub (I think @lukasheinrich can probably confirm or deny this).

**Comment by matthewfeickert** [comment]
Actually, with just playing around with Docker Hub's build rules it seems that this could perhaps be easily dealt with using the Docker Hub automated builds. This can be tested with the next patch release.

![docker_build_rules](https://user-images.githubusercontent.com/5142394/71701122-4802c080-2d8d-11ea-81fa-d98eda34932e.png)

**Comment by matthewfeickert** [comment]
While just using the Docker Hub infrastructure to do this works, there is the small downside that different tags of the same release have different hashes. Ideally, the SHA for the `latest-stable` and the latest release version would be the same. But in the case of `v0.3.2`

```
$ docker images pyhf/pyhf
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
pyhf/pyhf           latest              c5271a804e64        2 minutes ago       380MB
pyhf/pyhf           v0.3.2              3367049f5eb6        6 minutes ago       380MB
pyhf/pyhf           latest-stable       9643d49c37b5        11 minutes ago      380MB
pyhf/pyhf           v0.3.1              f9dd90b3d86e        2 days ago          365MB
```

while it would have been nicer to see

```
$ docker images pyhf/pyhf
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
pyhf/pyhf           latest              c5271a804e64        11 minutes ago      380MB
pyhf/pyhf           v0.3.2              c5271a804e64        11 minutes ago      380MB
pyhf/pyhf           latest-stable       c5271a804e64        11 minutes ago      380MB
pyhf/pyhf           v0.3.1              f9dd90b3d86e        2 days ago          365MB
```

This is obviously a super small nitpick, but do people have thoughts on how to do this?

**Comment by matthewfeickert** [comment]
Maybe https://github.com/marketplace/actions/publish-docker-action could do it, but the as the [`static-tag-list`](https://github.com/marketplace/actions/publish-docker-action#static-tag-list) and [`auto-tag`](https://github.com/marketplace/actions/publish-docker-action#auto-tag) options conflict I'm not sure how to get `latest-stable` tagged off the same build.

**Comment by matthewfeickert** [comment]
Actually, https://github.com/marketplace/actions/publish-docker might be the best bet if they are willing to implement a `tags` options.

**Comment by kratsg** [comment]
> Actually, https://github.com/marketplace/actions/publish-docker might be the best bet if they are willing to implement a `tags` options.

We should wait for that to happen, perhaps... but... hrmm.. .How often are our docker images being used?

**Comment by matthewfeickert** [comment]
> > Actually, https://github.com/marketplace/actions/publish-docker might be the best bet if they are willing to implement a `tags` options.
> 
> We should wait for that to happen, perhaps... but... hrmm.. .How often are our docker images being used?

Well, I put them on CVMFS unpacked/sync so perhaps more now. Also, with the drop of Python 2 coming I wanted to make sure that we could clearly say "use this Docker image if you can't get Python 3 in your local runtime for whatever collection of painful reasons". I now have Docker Hub versioning them for us, but it would be nicer to have all the tags have the same build SHA.

**Comment by matthewfeickert** [comment]
This should now be doable: https://github.com/elgohr/Publish-Docker-Github-Action/issues/52#issuecomment-573843316
