### ISSUE TITLE
Have bumpversion GitHub bot edit old posts

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#725]
# Description

The bumpversion GitHub bot that is was added in PR #650 is really helpful, but it would be nice if it was re-triggered if it would edit its old post with new information, like the Codecov reporting bot does, rather then posting a new comment. This would just make things look nicer in the PR.

**Comment by kratsg** [comment]
> The bumpversion GitHub bot that is was added in PR #650 is really helpful, but it would be nice if it was re-triggered if it would edit its old post with new information, like the Codecov reporting bot does, rather then posting a new comment. This would just make things look nicer in the PR.

pretty impossible to do with GitHub CI actions logic.

**Comment by matthewfeickert** [comment]
> pretty impossible to do with GitHub CI actions logic.

I have no doubt is it hard/not doable with the current setup. My point is that there are bots that do it, so perhaps if this eventually becomes a GitHub Action on the Action store this could be figured out.
