### ISSUE TITLE
Update Available Optimizers in README to include JAX

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#729]
# Description

The table in the README:

Available Optimizers

| NumPy                    | Tensorflow                 | PyTorch                    |
| :----------------------- | :------------------------- | :------------------------- |
| SLSQP (`scipy.optimize`) | Newton's Method (autodiff) | Newton's Method (autodiff) |
| MINUIT (`iminuit`)       | .                          | .                          |

needs to include JAX after PR #377

**Comment by lukasheinrich** [comment]
the table is horribly out of date anyways we don't use hand-coded newton's method at all anymore

**Comment by matthewfeickert** [comment]
It would be good to maybe fix this _before_ PR #972 goes in and triggers the release of `v0.5.0`, as @kratsg and @lukasheinrich did a lot of nice work on the optimizers for this release.

**Comment by kratsg** [comment]
> It would be good to maybe fix this _before_ PR #972 goes in and triggers the release of `v0.5.0`, as @kratsg and @lukasheinrich did a lot of nice work on the optimizers for this release.

ok, let's update the README to simply list the backends in one column and the optimizers in another

| Backends                    | Optimizers                 |
| :----------------------- | :------------------------- |
| numpy (`numpy_backend`) | SciPy (`scipy_optimizer`) |
| tensorflow (`tensorflow_backend`) | Minuit (`minuit_optimizer`) |
| pytorch (`pytorch_backend`) |  |
| jax (`jax_backend`) | |
