### ISSUE TITLE
Add links to HEPData entries for publications using HistFactory JSON likelihoods

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#736]
# Description

Links should be added in the [Use and Citations](https://scikit-hep.org/pyhf/citations.html) page for publications that have published to HEPData open likelihoods using the JSON HistFactory schema. As of the end of 2019 there are two (from ATLAS):
- [Search for bottom-squark pair production with the ATLAS detector in final states containing Higgs bosons, _b_-jets and missing transverse momentum](https://www.hepdata.net/record/ins1748602)
- [Search for direct stau production in events with two hadronic τ-leptons in s√=13 TeV pp collisions with the ATLAS detector](https://www.hepdata.net/record/ins1765529)

and in 2020:

- [Search for chargino-neutralino production with mass splittings near the electroweak scale in three-lepton final states in s√ = 13 TeV pp collisions with the ATLAS detector](https://www.hepdata.net/record/ins1771533)

**Comment by matthewfeickert** [comment]
Maybe also the [ATLAS News](https://atlas.cern/updates/atlas-news/new-open-likelihoods) and [CERN News](https://home.cern/news/news/knowledge-sharing/new-open-release-allows-theorists-explore-lhc-data-new-way) pieces.

**Comment by kratsg** [comment]
> Maybe also the [ATLAS News](https://atlas.cern/updates/atlas-news/new-open-likelihoods) and [CERN News](https://home.cern/news/news/knowledge-sharing/new-open-release-allows-theorists-explore-lhc-data-new-way) pieces.

We should have a... "outreach" page that includes talks + news? And then a page that is just for listing analyses that have published likelihoods? Lots of bibtex files but that's ok :)

**Comment by matthewfeickert** [comment]
> We should have a... "outreach" page that includes talks + news? And then a page that is just for listing analyses that have published likelihoods? Lots of bibtex files but that's ok :)

I think this sounds great!

**Comment by matthewfeickert** [comment]
Also (for archive purposes) the [CERN Bulletin](http://bulletinserv.cern.ch/emails/archive/484/).
