### ISSUE TITLE
honor constant parameters

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/pyhf#739]
# Description

thanks to #653 all optimizers can handle arbitrary constant parameters. We should adapt our API to honor the "fixed: true" settings in the workspace.

**Comment by matthewfeickert** [comment]
Given disagreements that @kratsg found between the different backends for the ATLAS SUSY 3L eRJR analysis likelihoods we should escalate this.

**Comment by kratsg** [comment]
> ATLAS SUSY 3L eRJR analysis likelihoods

not public yet ;)

**Comment by alexander-held** [comment]
I think this one is done as of #1051.

**Comment by lukasheinrich** [comment]
that's right. Thanks @alexander-held for the remindinder.
