### ISSUE TITLE
AssertionError in pyhf/optimize/opt_scipy.py

### ISSUE THREAD

**Issue by jackaraz** [scikit-hep/pyhf#743]
Hi All

I'm trying to implement pyhf to MA5 but I'm getting an AssertionError which occurs specifically when Nsig >> Nobs. It is possible to say that in case of this error I set CLs = 0. but I can't be sure if this is the only case. As an example, I used the background file given in [this link](https://www.hepdata.net/record/resource/997020?view=true) (specifically region A bkgonly JSON file) and the signal is as follows;

`[{'path': '/channels/0/samples/0', 'value': {'modifiers': [{u'type': u'lumi', u'data': None, u'name': u'lumi'}, {u'type': u'normfactor', u'data': None, u'name': u'mu_SIG'}], 'data': [439.392019, 2112.461863, 1487.17302], 'name': 'MA5_signal'}, 'op': 'add'}, {'path': '/channels/1/samples/0', 'value': {'modifiers': [], 'data': [], 'name': 'MA5_signal'}, 'op': 'remove'}, {'path': '/channels/2/samples/0', 'value': {'modifiers': [], 'data': [], 'name': 'MA5_signal'}, 'op': 'remove'}]`

and I run pyhf as follows;

`workspace = pyhf.Workspace(background)`
`    model     = workspace.model(patches=[signal],`
`                                modifier_settings={`
`                                                    'normsys': {'interpcode': 'code4'},`
`                                                    'histosys': {'interpcode': 'code4p'}})`
`    CLs = pyhf.utils.hypotest(1.0, workspace.data(model), model, qtilde=qtilde)[0]`
`return 1.-CLs`

the full error that I'm getting is as follows;

> //anaconda2/lib/python2.7/site-packages/pyhf/utils.pyc in hypotest(poi_test, data, pdf, init_pars, par_bounds, qtilde, **kwargs)
>     281 
>     282     qmu_v = tensorlib.clip(
> --> 283         qmu(poi_test, data, pdf, init_pars, par_bounds), 0, max_value=None
>     284     )
>     285     sqrtqmu_v = tensorlib.sqrt(qmu_v)
> 
> //anaconda2/lib/python2.7/site-packages/pyhf/utils.pyc in qmu(mu, data, pdf, init_pars, par_bounds)
>     111     tensorlib, optimizer = get_backend()
>     112     mubhathat = optimizer.constrained_bestfit(
> --> 113         loglambdav, mu, data, pdf, init_pars, par_bounds
>     114     )
>     115     muhatbhat = optimizer.unconstrained_bestfit(
> 
> //anaconda2/lib/python2.7/site-packages/pyhf/optimize/opt_scipy.pyc in constrained_bestfit(self, objective, constrained_mu, data, pdf, init_pars, par_bounds)
>      41         )
>      42         try:
> ---> 43             assert result.success
>      44         except AssertionError:
>      45             log.error(result)
> 
> AssertionError: 

I'm not sure if it is safe to say

`try:`
`    CLs = ...`
`except AssertionError:`
`CLs = 0.`

Thanks

**Comment by jackaraz** [comment]
Solved! This problem has been answered in [this link](https://github.com/scikit-hep/pyhf/issues/620#issuecomment-564501334). Thanks!!

**Comment by matthewfeickert** [comment]
> Solved! This problem has been answered in [this link](https://github.com/scikit-hep/pyhf/issues/620#issuecomment-564501334). Thanks!!

Glad to know you got this resolved. Let us know if you have anymore questions!

**Comment by kratsg** [comment]
@jackaraz , can you post your fix in here as well? it seems like you hit a bounds issue, but it doesn't look like you're evaluating the POI outside of the default `[0,10]` bounds.

**Comment by jackaraz** [comment]
Hi, @kratsg I wrote the following wrapper:
[wrapper.txt](https://github.com/scikit-hep/pyhf/files/4093007/wrapper.txt)
