### ISSUE TITLE
Add additional Dockerfiles

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#746]
# Question

I've gone ahead and put the GPU enabled Docker images for the machine learning backends up on the Docker hub page (c.f. [tags with `cuda10.1-cudnn7-runtime-ubuntu18.04` in them](https://hub.docker.com/r/pyhf/pyhf/tags?page=1&name=cuda10.1-cudnn7-runtime-ubuntu18.04)). However, as can be seen, since they are based off of the (already quite large) NVIDIA CUDA images they are not even close to optimized for space (though I've tried to do my best at the moment with using multi-stage Docker builds combined with some smarter copying).

@lukasheinrich @kratsg I have all the Dockerfiles used to make these in a branch at the moment. Should I open a PR to add them in even though they images are unsatisfactorily large? This is my inclination but I thought I'd get your thoughts before asking you to review a PR full of Dockerfiles.

**Comment by kratsg** [comment]
> @lukasheinrich @kratsg I have all the Dockerfiles used to make these in a branch at the moment. Should I open a PR to add them in even though they images are unsatisfactorily large? This is my inclination but I thought I'd get your thoughts before asking you to review a PR full of Dockerfiles.

Let's reduce the size first before we start incorporating them into master. I'm ok with having a PR for now and GHA to explore the option.

**Comment by matthewfeickert** [comment]
> I'm ok with having a PR for now and GHA to explore the option.

The point of PR #748 was just to have them somewhere so that it would be easier to build them, so I'd like to have them get merged in once they are in a state where we're all happy with the quality of the `Dockerfile`s. I'm hesitant to include them in the CI for the moment a they take some time to build, but I could see working them into a future PR that only builds them as a specific check and then on PR merges. We'll see.

**Comment by matthewfeickert** [comment]
Generally related to our Docker images, @lukasheinrich has found [an article which recommend that people don’t use Alpine Linux for Python images](https://pythonspeed.com/articles/alpine-docker-python/). This might not apply to pyhf, but should have some followup associated with it.
