### ISSUE TITLE
parameters overrides in  are not combined in "pyhf combine"

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/pyhf#749]
# Description

In a closure test for `pyhf combine` I noticed that parameter section overrides in the workspace json can lead to a crash

here's a 2 bin - 1 channel json

https://gist.github.com/lukasheinrich/e6a9c49780e06d617f763c4d5496a205

```
curl https://gist.githubusercontent.com/lukasheinrich/e6a9c49780e06d617f763c4d5496a205/raw/a737eb4a04f627daeaad7d6acd5e54183ed5994f/combine_test_target.json|pyhf cls
{
    "CLs_exp": [
        0.07377754112073907,
        0.16776812083252346,
        0.3508132196480346,
        0.6260263084704382,
        0.8769621351034118
    ],
    "CLs_obs": 0.60635945662
```

Here are two workspaces, each carries one of the bins of the above one 

https://gist.github.com/lukasheinrich/925437eb40ffbf19e8b8f180b0d67924
https://gist.github.com/lukasheinrich/ecad7225503616360a96a35ea77e87a2

```
curl https://gist.githubusercontent.com/lukasheinrich/925437eb40ffbf19e8b8f180b0d67924/raw/417737735d6358139a50437fb3fccaf1423fbd00/combine_test_one.json|pyhf cls
{
    "CLs_exp": [
        0.14521985430105866,
        0.2715371244860493,
        0.4739897985534657,
        0.7271619041517813,
        0.9213903347174244
    ],
    "CLs_obs": 0.6553036139942451
}
```

```
curl https://gist.githubusercontent.com/lukasheinrich/ecad7225503616360a96a35ea77e87a2/raw/e70c93ae2464ad0bbbe5d931284db4fa8ef66164/combine_test_two.json|pyhf cls
{
    "CLs_exp": [
        0.10991489771691786,
        0.2230264429815649,
        0.4196899637032293,
        0.685255927920688,
        0.9041426586275007
    ],
    "CLs_obs": 0.5878244654561694
}
```

In principle combination is easy, however the "lumi" sepc in the "parameter sections" of both worksapces trips up `pyhf combine`

```
pyhf combine \
<(curl https://gist.githubusercontent.com/lukasheinrich/925437eb40ffbf19e8b8f180b0d67924/raw/417737735d6358139a50437fb3fccaf1423fbd00/combine_test_one.json) \
<(curl https://gist.githubusercontent.com/lukasheinrich/ecad7225503616360a96a35ea77e87a2/raw/e70c93ae2464ad0bbbe5d931284db4fa8ef66164/combine_test_two.json) | \
pyhf cls
pyhf.exceptions.InvalidModel: Multiple parameter configurations for lumi were found.
```

**Comment by lukasheinrich** [comment]
removing the `lumi` override in one of those makes the combine suceed

```
pyhf combine combine_test_one.json combine_test_two.json |pyhf cls 
{
    "CLs_exp": [
        0.07377747787827929,
        0.1677680175129932,
        0.35081308223858354,
        0.6260261825582223,
        0.8769620736144732
    ],
    "CLs_obs": 0.606359406098968
}
```

```
pyhf cls combine_test_target.json 
{
    "CLs_exp": [
        0.07377754112073907,
        0.16776812083252346,
        0.3508132196480346,
        0.6260263084704382,
        0.8769621351034118
    ],
    "CLs_obs": 0.6063594566205426
}
```

**Comment by kratsg** [comment]
Yep, this is one thing I've been working on ideas for to resolve it. One tricky factor is that I normally use `set()` to remove duplicates -- but in this case, I'm unable to simply because we're trying to compare dictionaries of things. I have some ideas in mind and can definitely put a fix soon :)

**Comment by kratsg** [comment]
See also #695.

**Comment by lukasheinrich** [comment]
can't we reuse `reduce_paramsets_requirements`. Seems like an equivalent problem.

https://github.com/scikit-hep/pyhf/blob/master/src/pyhf/parameters/utils.py#L4

**Comment by kratsg** [comment]
> can't we reuse `reduce_paramsets_requirements`. Seems like an equivalent problem.

roughly equivalent. i need to do some thinking to figure out a clean way to combine what i've done in #752 with that function.
