### ISSUE TITLE
Zenodo link broken

### ISSUE THREAD

**Issue by cranmer** [scikit-hep/pyhf#772]
# Description

the link points to DIANA/HEP and is broken (404)

https://zenodo.org/record/3334365#.XkrQ9y2ZNTY

# Expected Behavior

the link won't be broken

# Actual Behavior

the link is broken

# Steps to Reproduce

click on link

**Comment by matthewfeickert** [comment]
Closing this as this is already covered in Issue #255

**Comment by matthewfeickert** [comment]
@cranmer This is now fixed and [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3678702.svg)](https://doi.org/10.5281/zenodo.3678702) points to the Scikit-HEP version thanks to some information from Alexandros Ioannidis-Pantopikos at Zenodo.
