### ISSUE TITLE
Is 'parametrised' a typo in Introduction as well as in Likelihood page?

### ISSUE THREAD

**Issue by kanishk16** [scikit-hep/pyhf#803]
# Question
As the title suggests is `parametrised` a typo here (in intro.rst at line 30):
```
parametrised variations, both to express the effect of *free parameters*
```
as well as here (in likelihood.rst at line 18):
```
within each channel and their possible parametrised modifiers.
```

**Comment by kratsg** [comment]
British spelling is ok here. The following 4 are acceptable:

- parameterize
- parametrize
- parameterise
- parametrise
