### ISSUE TITLE
pyhf spec normalize

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/pyhf#805]
# Description

it might be nice to be able to normalize a pyhf spec

* sort samples alphabetically
* sort modifiers alphabetically

and similar things to ease e.g. comparisong with jsondiff and patch creation

assumptions

```
pyhf cls spec.json
pyhf spec normalize spec.json > normalized.json
pyhf cls normalized.json
```

should produce the same results

(based on discussions with @ntadej  @danikam @kratsg )

**Comment by matthewfeickert** [comment]
Issue #1033 might be something to keep in mind around the same time this get addressed.
