### ISSUE TITLE
Bug: scm versioning no longer being used during TestPyPI builds

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#832]
# Description

In PR #826, the [`checkout` GitHub Action](https://github.com/actions/checkout) was updated to stable release `v2`. However, [this broke the semantic versioning](https://github.com/scikit-hep/pyhf/runs/605413197#step:8:12) that is relied upon for the TestPyPI uploads to work. The repo seems to have lost understanding of what the version is as the wheel that is built is `pyhf-0.1.dev1-py2.py3-none-any.whl`, while the TestPyPI release just before that from PR #823 (still on [`actions/checkout@v1.2.0`](https://github.com/actions/checkout/releases/tag/v1.2.0)) correctly gave the version as `0.4.2.dev20`.

# Expected Behavior

Have the repo know its current release version so that it can use the scm dev release versioning.

# Actual Behavior

The repo doesn't know its current version state and defaults to version `0.1.dev1`.

# Steps to Reproduce

Run the Build and publish Python distro to (Test)PyPI CI workflow

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by matthewfeickert** [comment]
It is worth noting that @webknjaz is using [`actions/checkout@master`](https://github.com/sanitizers/octomachinery/blob/86fb9ea04801a93442c59e7f77288af0a2efee77/.github/workflows/publish-to-test-pypi.yml#L19) for octomachinery and it is working fine for TestPyPI, so this implies that there is something about how pyhf is currently setup that is an issue.

**Comment by matthewfeickert** [comment]
This appears to be the result of the [`fetch-depth` defaulting to 1 in `v2`](https://github.com/actions/checkout/tree/01aecccf739ca6ff86c0539fbc67a7a5007bbc81#usage) such that the default clone is

```
git clone --depth=1 https://github.com/scikit-hep/pyhf.git
```

while in `v1.2.0` the fetch depth would

> [defaults to no limit](https://github.com/actions/checkout/blob/50fbc622fc4ef5163becd7fab6573eac35f8462e/action.yml#L18).

It seems that `otctomachinery` might actually affected as well, as all of the [`depolyment` jobs for the last 7 months are broken](https://github.com/sanitizers/octomachinery/actions?query=event%3Adeployment). Though that is longer than `v1.2.0`, so maybe not for the same reason.

**Comment by kratsg** [comment]
you need to grab tags too: 

https://github.com/actions/checkout/tree/01aecccf739ca6ff86c0539fbc67a7a5007bbc81#fetch-all-tags

**Comment by matthewfeickert** [comment]
> you need to grab tags too:
> 
> https://github.com/actions/checkout/tree/01aecccf739ca6ff86c0539fbc67a7a5007bbc81#fetch-all-tags

Yeah, I realize that now. I had tried that first without increasing the clone depth and then removed them when I ran with fetch depth of 0. The combination of

```yaml
- uses: actions/checkout@v2
  with:
    fetch-depth: 0
# Fetch all tags
- run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
```

 [works](https://github.com/scikit-hep/pyhf/runs/606052117?check_suite_focus=true#step:8:7).

**Comment by webknjaz** [comment]
> It seems that `otctomachinery` might actually affected as well

Yeah, actually that one still uploads via Travis CI. And your solution to fetch more is correct. You could also use something like `git fetch --unshallow` depending on your case. It should be enough to fetch only some amount of commits as long as one of them is tagged. So this'd not be visible if you were to release often.

**Comment by matthewfeickert** [comment]
> You could also use something like `git fetch --unshallow` depending on your case.

Yup! This works too

```yaml
- uses: actions/checkout@v2
  # Get history and tags for dev versioning to work
- run: |
    git fetch --prune --unshallow
    git fetch --depth=1 origin +refs/tags/*:refs/tags/*
```
