### ISSUE TITLE
Simplify Workspace::_get_measurement()

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/pyhf#836]
# Description

At the moment, some of the functionality of `get_measurement()` on the `Workspace` is likely a bit too smart/magic. This should be trimmed/cleaned up to be simpler and less complex. This came out of some changes in #813 which reveal that we're passing in unused keyword arguments into `_ModelConfig` (namely: `measurement_name`).

**Comment by matthewfeickert** [comment]
@kratsg Do you want this to go into patch release `v0.4.2`? Or can that go in `v0.5.0`?

**Comment by kanishk16** [comment]
When is the patch going to release, tentatively? If we have some time then I could possibly work on this.

**Comment by kratsg** [comment]
This week. I'll be working on it, since i've assigned it to myself.
