### ISSUE TITLE
Update PyPI keywords and classifies in setup.py

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#861]
# Description

As JAX is now a supported backend then it should additionally be added to the [list of keywords in `setup.py`](https://github.com/scikit-hep/pyhf/blob/917bd5127c1da023b279c076bb41614fbb859487/setup.py#L85). Additionally, the [classifies](https://packaging.python.org/guides/distributing-packages-using-setuptools/#classifiers) should be updated as well to include a `Development Status`, `License`, `Intended Audience`, and `Topic`.

**Comment by matthewfeickert** [comment]
Working from the [full list of PyPI recognized classifiers](https://pypi.org/classifiers/):

**Development Status**

As far as `Development Status` goes, we are not at a `v1.0.0` release so we could be a `Development Status :: 4 - Beta` but at the same time `pyhf` is definitely being used so I would lean towards it being put under `Development Status :: 5 - Production/Stable`.

**Intended Audience**

`Intended Audience :: Science/Research`

**Topic**

- `Topic :: Scientific/Engineering`
- `Topic :: Scientific/Engineering :: Physics`

**Comment by kratsg** [comment]
Not sure we want to call pyhf "stable". Until we hit v1.0.0 I'm inclined to avoid that.

**Comment by matthewfeickert** [comment]
> want to call pyhf "stable". Until we hit v1.0.0 I'm inclined to avoid that.

I changed my mind as well and went back to "beta" in the PR.
