### ISSUE TITLE
Investigate switching from pyflakes to flake8

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#863]
# Description

After a [strange incident](https://github.com/scikit-hep/pyhf/pull/862#issuecomment-625642362) with [`pyflakes`](https://github.com/PyCQA/pyflakes) and the branch name(?) it seems quite hard to figure out how to ignore certain paths if needed with `pyflakes`. It might be worth checking out [`flake8`](https://pypi.org/project/flake8/) instead.

@alexander-held is using `flake8` for [`cabinetry`](https://github.com/alexander-held/cabinetry) so he might have thoughts here.

**Comment by matthewfeickert** [comment]
@kratsg [had mentioned](https://github.com/scikit-hep/pyhf/pull/862#issuecomment-625842486)

> > Why is it looking under `.git/` at all?
> 
> probably recursive with no exclusions. We could tell pyflakes to ignore `.git` manually.

How can we do this with `pyflakes`? There is no command line flag to ignore.

**Comment by alexander-held** [comment]
I don't know about the `pyflakes`/`flake8` differences, but `flake8` comes with a `--exclude` option. The reason I use `flake8` is that it was in the template workflow, nothing deeper than that.

**Comment by matthewfeickert** [comment]
Having just looked at this for a few other projects (like `pylhe`) `pyhf` is currently failing the following `flake8` checks:
`W293`, `W503`, `W605`, `E203`, `E266`, `E231`, `E302`, `E402`, `E501`, `E713`, `E722`

so this would be a cleaning project that would probably take a bit of time.

**Comment by alexander-held** [comment]
Was surprised to see some of them come up, but there might be explanations, see e.g. https://github.com/psf/black/issues/315. I like the black line length of 88 is more than the 79 from PEP-8, you can use `--max-line-length` with `flake8`.

**Comment by matthewfeickert** [comment]
> I like the black line length of 88 is more than the 79 from PEP-8, you can use `--max-line-length` with `flake8`.

I was, but Black only enforces that for _code_ while `flake8` enforces that for _everything_. So our docstrings along with some very long string literals from URLs are what is setting that off.

**Comment by kratsg** [comment]
not sure if flake8 is meant to be checking docstrings?

**Comment by matthewfeickert** [comment]
> not sure if flake8 is meant to be checking docstrings?

No, not its indented use. I'm not sure how to tell it to only check lines of files that are code though (or if that is even possible).

**Comment by matthewfeickert** [comment]
As pointed out in PR #1047, using [`flake8` will also pickup invalid escape sequences](https://github.com/scikit-hep/pyhf/pull/1047#issuecomment-680698931). So along with taking care of some things in Issue #1021 this is good to note.
