### ISSUE TITLE
User-defined log formatting

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/pyhf#865]
# Description

`pyhf` uses `logging` for outputs, and calls `logging.basicConfig()` in a few places.
This has the effect of preventing the user to set their desired logging behavior after `pyhf` import.
While calling this a bug might be a bit of a stretch, I think it might be unintentional since `pyhf` does not apply any logging formatting as far as I can tell.

# Expected Behavior

I expect no calls to `logging.basicConfig()` within `pyhf` to leave the formatting fully up to the user, no matter whether they want to set it before or after importing `pyhf`.

# Actual Behavior

User-defined `logging` formatting only works before importing `pyhf`.

# Steps to Reproduce

importing `pyhf` before formatting:
```
import logging
import pyhf
print(pyhf.__version__)
logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)
log.info("message")
```
output:
```
0.4.1
```
and when applying formatting before input, the expected behavior:
```
import logging
logging.basicConfig(level=logging.INFO)
import pyhf
print(pyhf.__version__)
log = logging.getLogger(__name__)
log.info("message")
```
output:
```
0.4.1
INFO:__main__:message
``` 

# Checklist

- [ ] Run `git fetch` to get the most up to date version of `master`
  - no, but checked code on master to confirm that the relevant part is unchanged
- [X] Searched through existing Issues to confirm this is not a duplicate issue
- [X] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by matthewfeickert** [comment]
Thanks for reporting this @alexander-held. I think this is something that would be reasonable for us to look into, maybe for a quick `v0.5.1` patch release once we finish shepherding `v0.5.0` out.

**Comment by lukasheinrich** [comment]
`logging.basicConfig` should only be called in `commandline.py`

**Comment by matthewfeickert** [comment]
@alexander-held as @lukasheinrich took at look at this and was super speedy about this it will go into the next patch release `v0.4.2` which should be out soon (O(<1 week)). You and I have talked about how to install dev versions of `pyhf` though so as soon as PR #866 is in you can start using it in the interim.

**Comment by alexander-held** [comment]
Thanks a lot for taking care of this!
