### ISSUE TITLE
Move metadata from setup.py to setup.cfg

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#872]
# Description

@henryiii has documented on the [Scikit-HEP packaging information page](https://scikit-hep.org/developer/packaging#setup-configuration-medium-priority) how one can move from having PyPI metadata be stored in `setup.py` to `setup.cfg`. We've known about this for sometime but haven't taken the time to do it yet, but it is probably worth doing.

@henryiii Can you comment on how to deal with `project_urls`?

https://github.com/scikit-hep/pyhf/blob/3e1f157119dbcb4d8db8ffd8c98e16a2d12d0239/setup.py#L82-L86

**Comment by matthewfeickert** [comment]
> Can you comment on how to deal with project_urls?

There is a very nice example of how to do this in the [gwcelery `setup.cfg` file](https://git.ligo.org/emfollow/gwcelery/-/blob/46374fad07099fcc38cc6e620c6c7fc7afc736b2/setup.cfg)

**Comment by henryiii** [comment]
Nice, thanks, was just looking for an example of this. :)
