### ISSUE TITLE
Add CodeMeta JSON-LD Context File

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#891]
# Description

As part of an IRIS-HEP initiative to improve the citation quality/ease for all software it has been recommended by @danielskatz that projects:
- Track authors/contributors to software as it is developed
- Create a citation metadata file in the software repo and keep it up to date
- Link Github and Zenodo to get DOIs for major releases
- In the README and docs clearly says how to cite the software

`pyhf` already does all of this, as:
- [x] There is an [`AUTHORS` file](https://github.com/scikit-hep/pyhf/blob/31d34a0edd91593d75181cc3ad71563a52600793/AUTHORS) as well as a [listing of the authors in the docs](https://scikit-hep.org/pyhf/index.html#authors)
- [x] There is a [`.zenodo.json`](https://github.com/scikit-hep/pyhf/blob/2b0a1e2ba41a2aa1233511524e3aa78e696ead34/.zenodo.json) that formats Zenodo with the correct metadata and adds the ORCID of the authors
- [x] There is a Zenodo DOI that is kept in sync with our release schedule (almost) fully automatically (almost as it requires 1 button click). [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1169739.svg)](https://doi.org/10.5281/zenodo.1169739)
- [x] There is a Citation section in both the [`README`](https://github.com/scikit-hep/pyhf/blob/2b0a1e2ba41a2aa1233511524e3aa78e696ead34/README.rst#citation) and the [docs webpage](https://scikit-hep.org/pyhf/citations.html) with the preferred citation

It has been pointed out though that we should also look into adding a [CodeMeta Project JSON-LD Context File](https://codemeta.github.io/jsonld/) as with it

> zenodo will read [it] and will be basically the same as [schema.org](http://schema.org/) so that this will help google index software, and tools be able to use the metadata file in [softwareheritage.org](http://softwareheritage.org/) to automatically build a citation for a particular commit.

(cc @gordonwatts as this might be of interest)

**Comment by matthewfeickert** [comment]
As an example, the [`parsl` library has a `codemeta.json` file](https://github.com/Parsl/parsl/blob/master/codemeta.json).

**Comment by danielskatz** [comment]
tools to generate CodeMeta files are in https://codemeta.github.io/tools/

**Comment by matthewfeickert** [comment]
While it doesn't look to be very actively developed, it should be possible to add a GHA workflow to use [`codemetapy`](https://github.com/proycon/codemetapy) to automatically update the `codemeta.json` on release merges in the same way that we run `bumpversion`.
