### ISSUE TITLE
report floating point precision of backends

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/pyhf#907]
# Description

tensor backends should have an easy way to report the floating point precisino
of their tensors (when using float tensors) 

This was raised by @nikoladze  in #902

**Comment by matthewfeickert** [comment]
@lukasheinrich Given the discussion there I'm assuming you're thinking of an API like

```python
tensorlib.float_precision  # float32
tensorlib.int_precision  # int32
```

or were you thinking 

```python
tensorlib.tensor_precision  # (float32, int32)
```
?
