### ISSUE TITLE
Publish wheels for Mac using cibuildwheel

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#908]
# Description

@henryiii has written a post on Scikit-HEP that details how to use [GitHub Actions for Binary Wheels](https://scikit-hep.org/developer/gha_wheels) using the [`cibuildwheel`](https://cibuildwheel.readthedocs.io/en/stable/) he wrote. As `pyhf` is pure Python there is a lower need to create wheels for macOS, but it might still be of interest in the future.

**Comment by henryiii** [comment]
A Python wheel is universal - it is just as much "for" macOS as it is for Linux (or Windows, for that matter). The only reason to break up a wheel is due to compiled parts. If there are no compiled parts, there is no reason to publish any binary wheels, in fact it is detrimental.

**Comment by matthewfeickert** [comment]
> there is no reason to publish any binary wheels, in fact it is detrimental.

Can you elaborate on this? It would seem that most small Python libraries then are doing the wrong thing.

**Comment by henryiii** [comment]
Can you give an example of one?

**Comment by matthewfeickert** [comment]
> The only reason to break up a wheel is due to compiled parts. If there are no compiled parts, there is no reason to publish any binary wheels, in fact it is detrimental.

Ah, I was making a mistake between "[built](https://packaging.python.org/glossary/#term-built-distribution)" and "[binary](https://packaging.python.org/glossary/#term-binary-distribution)" wheels. I think given what I now understand then

> A Python wheel is universal 

makes more sense as from the [PyPA "Wheel vs Egg" page](https://packaging.python.org/discussions/wheel-vs-egg/)

> [Wheel](https://packaging.python.org/glossary/#term-wheel) archives do not include .pyc files. Therefore, when the distribution only contains Python files (i.e. no compiled extensions), and is compatible with Python 2 and 3, it’s possible for a wheel to be “universal”, similar to an [sdist](https://packaging.python.org/glossary/#term-source-distribution-or-sdist).

So it seems that in our publishing CI

https://github.com/scikit-hep/pyhf/blob/cb4d37ba89e2aa9b43f6db3e168841b97d7079e6/.github/workflows/publish-package.yml#L32-L34

it should probably say "Build a built wheel and a sdist" instead (also I guess we should probably be running [`python3 -m pep517.check`](https://github.com/pypa/pep517/tree/82a303d0cdb5de1e48f30b90ee299a8e0cbfad3b) for good measure).

**Comment by henryiii** [comment]
I would just say "built a wheel". Yes, there may be some confusion. Wheels do not include .pyc files - those get compiled when the wheel is _installed_ (unlike an egg, which only compiled the pyc's when running, IIRC). Don't bother with eggs, those are obsolete.

I would run any checks you can run - twine check is a good one (but might be identical to the pep517 check, I'm not sure).

**Comment by matthewfeickert** [comment]
> I would just say "built a wheel".

:+1: I'll adjust this in a PR.

> Don't bother with eggs, those are obsolete.

We don't, but that's the page the came up in search with a helpful description of a wheel related thing I was trying to understand.

> I would run any checks you can run - twine check is a good one

Yup. We already do.

https://github.com/scikit-hep/pyhf/blob/cb4d37ba89e2aa9b43f6db3e168841b97d7079e6/.github/workflows/publish-package.yml#L64-L65

**Comment by webknjaz** [comment]
> Yup. We already do.

FTR the publish GHA now runs that too.

**Comment by matthewfeickert** [comment]
> FTR the publish GHA now runs that too.

Thank you for making that GHA _so_ wonderful!

**Comment by matthewfeickert** [comment]
Given that there has been some followup discussion on Twitter on all of this, I'll link @webknjaz's [very good Tweet](https://twitter.com/webKnjaZ/status/1277686654644498442) that points to the discussion of '[What's the deal with "purelib" vs. "platlib"?](https://www.python.org/dev/peps/pep-0427/#what-s-the-deal-with-purelib-vs-platlib)' in PEP 427.

**Comment by henryiii** [comment]
* All wheels are "built" wheels -> All wheels are "built" distributions. They *do not* run setup.py, but just move files into locations.
* All wheels are binary distributions: I don't think this is true, at least it's quite confusing. A wheel without compiled extensions is made up of text files only - on install, it precompiles `.pyc` files, but that's not part of the wheel itself.

Wheels are really just zip files. Extra them and look inside.

**Comment by webknjaz** [comment]
> * All wheels are binary distributions: I don't think this is true, at least it's quite confusing. A wheel without compiled extensions is made up of text files only - on install, it precompiles `.pyc` files, but that's not part of the wheel itself.
> 
> Wheels are really just zip files. Extra them and look inside.

I pointed out on twitter that most tools use "binary" in their UI to say "it's a wheel, not sdist". [`pep517.build` has `--binary`](https://pypi.org/project/pep517/) but the back-end will actually decide whether the result will be a platlib or a purelib, the only guarantee is that it'll be a zip archive (wheel). [`pip install` also has `--no-binary`/`--only-binary`/`--prefer-binary`](https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-no-binary) that _only_ control sdist vs non-sdist preferences.

**Comment by henryiii** [comment]
How about:

* All wheels are considered binary distributions, even if they don't contain compiled extensions and are universally applicable.

**Comment by webknjaz** [comment]
@henryiii yeah, I mean... It's correct but also depends on whose terminology is used.
