### ISSUE TITLE
Add distribution on Conda-forge

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#923]
# Description

As a SciPy 2020 fun challenge, and since @bdice is a willing expert in packaging things for [Conda-forge](https://conda-forge.org/), it would be nice to see if we could also start distributing `pyhf` on Conda-forge, and then integrate releasing into CI as well.

**Comment by bdice** [comment]
Hi! Happy to help. 👍 Will follow up offline.

**Comment by matthewfeickert** [comment]
Thanks @chrisburr for merging and thanks @bdice for the help!

**Comment by matthewfeickert** [comment]
Feedstock is up now: https://github.com/conda-forge/pyhf-feedstock
