### ISSUE TITLE
implement autodiff + iminuit

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/pyhf#949]
# Description

As @HDembinski correctly points out iminuit can consume custom gradients, which of course we can provide by using autodiff. 

In our scipy optimizers (using SLSQP) we have one version with gradients 

https://github.com/scikit-hep/pyhf/blob/0f99cc488156e0826a27f55abc946d537a8922af/src/pyhf/optimize/autodiff.py#L33-L35

(which uses gradients from TF, jax, torch, or whatever)

but also without 

https://github.com/scikit-hep/pyhf/blob/0f99cc488156e0826a27f55abc946d537a8922af/src/pyhf/optimize/opt_scipy.py#L37-L45

for iminuit we currently don't pass gradients

https://github.com/scikit-hep/pyhf/blob/master/src/pyhf/optimize/opt_minuit.py

but we could (and also proovide an abstract interface so that we can use it w/ all autodiff backends.

This provides us in the end with a matrix

```
      | scipy w/ grad | scipy w/o grad | minuit w/ grad | iminuit w/o grad
numpy |       no              yes              no                yes
jax   |       yes             yes              yes               yes
TF    |       yes             yes              yes               yes
torch |       yes             yes              yes               yes

````

using the `minimize()` API in iminuit maybe we can even streamline this.

**Comment by lukasheinrich** [comment]
https://nbviewer.jupyter.org/github/scikit-hep/iminuit/blob/master/tutorial/automatic_differentiation.ipynb

**Comment by lukasheinrich** [comment]
@HDembinski does iminuit's interface also support the `jac=True` syntax?

**Comment by HDembinski** [comment]
https://github.com/scikit-hep/iminuit/blob/22f6ed7146c1d1f3274309656d8c04461dde5ba3/src/iminuit/_minimize.py#L91

**Comment by HDembinski** [comment]
I think I can add support `jac=True`, not sure why I didn't do it...

**Comment by HDembinski** [comment]
I think you can just as easily switch from `jac=True` to `jac=callable`, then it works with scipy and Minuit.

**Comment by kratsg** [comment]
Also adding this in here: https://github.com/scikit-hep/iminuit/blob/develop/tutorial/automatic_differentiation.ipynb

**Comment by kratsg** [comment]
#754 is duplicate.
