### ISSUE TITLE
Documentation: meaning of value for return_fitted_val=True

### ISSUE THREAD

**Issue by cranmer** [scikit-hep/pyhf#957]
# Description

In this code snippet from the documentation 

```python
>>> pyhf.infer.mle.fixed_poi_fit(test_poi, data, model, return_fitted_val=True)
(array([1.        , 0.97224597, 0.87553894]), array([28.92218013]))
```

it isn't clear what the meaning of `array([28.92218013])` is. Is it likelihood, log likelihood, -log likelihood, -2 log likelihood?
It is the latter, but that is not clear.

Applies to 

https://scikit-hep.org/pyhf/_generated/pyhf.infer.mle.fixed_poi_fit.html
or
https://scikit-hep.org/pyhf/_generated/pyhf.infer.mle.fit.html

## Is your feature request related to a problem? Please describe.

I wasn't sure, so I had to try a few things to figure it out.

### Describe the solution you'd like

Add a note to the documentation for the convention.

### Describe alternatives you've considered

banging my head against the wall.

# Relevant Issues and Pull Requests

**Comment by cranmer** [comment]
Another note... it's not obvious what the return order will be when both return_fitted and return_tail_prob are both true

**Comment by kratsg** [comment]
> Another note... it's not obvious what the return order will be when both return_fitted and return_tail_prob are both true

Sorry, I'm not understanding as nothing in our code has both of those configurations at the same time. `return_tail_probs` is for hypotest, which relies on the `AsymptoticCalculators` which consumes the fitted value -- while `return_fitted_val` is for the optimizer API we have (e.g. `opt.minimize`).
