### ISSUE TITLE
bug: pyhf has unstable rerturn types  to pyhf.infer.mle.fit

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/pyhf#964]
# Description

pyhf seems to weirdly have inconsistent return types when fitting

```
import pyhf

model = pyhf.simplemodels.hepdata_like([10.],[100.],[10.])
data  = [110.] + model.config.auxdata

r = pyhf.infer.mle.fit(
    [110,100],
    model,
    init_pars = model.config.suggested_init(),
    par_bounds=model.config.suggested_bounds(),
    return_fitted_val = True
)

print(r[1])

r = pyhf.infer.mle.fit([110,101],
    model,
    init_pars = model.config.suggested_init(),
    par_bounds=model.config.suggested_bounds(),
    return_fitted_val = True
)

print(r[1])
```

prints

```
12.984586493051552
[12.99452032]
```

in one instance the fitted value is a float in another it's a 1-element tensor

**Comment by lukasheinrich** [comment]
perhaps rerlated to #954

**Comment by kratsg** [comment]
#951 will fix this to some extent.

**Comment by matthewfeickert** [comment]
> #951 will fix this to some extent.

Can you elaborate a bit more on that here? This is also affecting PR #972.

**Comment by matthewfeickert** [comment]
@lukasheinrich Running the above code on `master` after merging PR #951 produces the following output:

```python
[12.98458649]
[12.99452032]
```

so given that there is a consistent return structure I think this Issue can get closed.
