### ISSUE TITLE
CLsb options

### ISSUE THREAD

**Issue by cranmer** [scikit-hep/pyhf#965]
# Description

The Brazil band plot and the  `pyhf.infer.hypotest` API is very tailored to CLs. It’s not clear how to get expected bands for CL_sb (standard frequentist limits) or CL_b (for expected significance / discovery). Would be nice to have an option for the standard CLsb limits and to make which is being used explicit in the API.

Probably having an option like `use_CLs=True` as a default would be sufficient. Alternatively, `upper_limit_type="CLs"` could work.

## Is your feature request related to a problem? Please describe.

The astro community uses 90% CLsb upper limits mainly.

# Relevant Issues and Pull Requests

This is also relevant for the test inversion / interval API #953  

# Additional context
I also am not a huge fan of the bad physics jargon of justing “CL” instead of p-value, but that’s a different issue.

**Comment by cranmer** [comment]
closing as this issue is also picked up in #966

**Comment by matthewfeickert** [comment]
I'll actually reopen this, so that we can track the PRs that close it.
