### ISSUE TITLE
docs: Enable chronological ordering of talks and tutorials on website

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#969]
# Description

At the moment, the [docs webpage](https://scikit-hep.org/pyhf/outreach.html) does not order the talks and tutorials given in reverse chronological order. This makes it hard for someone new to find the most recent and relevant information on the page. If the page can be rendered in reverse chronological order that would be very useful.

**Comment by kratsg** [comment]
Surprisingly non-trivial: https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#custom-formatting-sorting-and-labelling

Not enough documentation so one has to dig through source code or just trial-and-error.
