### ISSUE TITLE
Continuous Poisson for pytorch/tensorflow backends

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/pyhf#971]
# Description

Reporting on behalf of @cranmer. At first glance, it looks like jax is written with the continuous poisson distribution (https://github.com/scikit-hep/pyhf/blob/a32a2c444c99e6bd3538cac821ea0b027699c937/src/pyhf/tensor/jax_backend.py#L304) as well as numpy (https://github.com/scikit-hep/pyhf/blob/a32a2c444c99e6bd3538cac821ea0b027699c937/src/pyhf/tensor/numpy_backend.py#L293) while

- tensorflow (https://github.com/scikit-hep/pyhf/blob/a32a2c444c99e6bd3538cac821ea0b027699c937/src/pyhf/tensor/tensorflow_backend.py#L366)
- pytorch (https://github.com/scikit-hep/pyhf/blob/a32a2c444c99e6bd3538cac821ea0b027699c937/src/pyhf/tensor/pytorch_backend.py#L277)

are not.

# Expected Behavior

All backends were written to use the continuous poisson distribution.

# Actual Behavior

Only numpy and jax use continuous poisson distributions.

# Steps to Reproduce

I looked at our code with my eyes.

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by kratsg** [comment]
Need to add unit tests to check for this functionality explicitly.

**Comment by cranmer** [comment]
When I checked the behavior of pytorch with non integer value of `n`, I got a smooth curve. So That code may implicitly have the continuous  `n` behavior that is needed. But I didn't check the value explicitly (though it did go through the integer values, which I assume are correct). 
https://github.com/scikit-hep/pyhf/blob/a32a2c444c99e6bd3538cac821ea0b027699c937/src/pyhf/tensor/pytorch_backend.py#L277

+1 for a unit test that uses non-integer values of `n`

**Comment by matthewfeickert** [comment]
We can add unit tests, but I think we're good no?

```python
import numpy as np
import pyhf
import matplotlib.pyplot as plt


def visualize(n_values, backend_poissons, backends):
    plt.rcParams.update({"font.size": 14})

    fig, ax = plt.subplots()
    fig.set_size_inches(7, 5)

    for backend in backends:
        ax.plot(n_values, backend_poissons[backend], label=rf"{backend}, $\lambda=1$")

    ax.set_xlabel("n")
    ax.set_ylabel(r"$\mathrm{Pois}(n|\lambda)$")
    ax.legend(loc="best")
    fig.savefig("continuous_poisson_comparison.png")

    fig, ax = plt.subplots()
    fig.set_size_inches(7, 5)

    for backend in backends:
        ax.plot(
            n_values,
            backend_poissons[backend] / backend_poissons["numpy"],
            label=f"{backend}",
        )

    epsilon = 2e-6
    ax.set_ylim(1.0 - epsilon, 1.0 + epsilon)
    ax.set_xlabel("n")
    ax.set_ylabel(r"backend result / NumPy")
    ax.legend(loc="best")
    fig.savefig("relative_difference.png")


def main():
    backends = ["numpy", "tensorflow", "pytorch", "jax"]
    n_values = np.arange(0.5, 5.1, 0.1)
    lambda_value = 1.0

    backend_poissons = {}

    for backend in backends:
        pyhf.set_backend(backend)
        _values = pyhf.tensorlib.poisson(
            pyhf.tensorlib.astensor(n_values), pyhf.tensorlib.astensor(lambda_value)
        )
        backend_poissons[backend] = np.array(pyhf.tensorlib.tolist(_values))

    visualize(n_values, backend_poissons, backends)


if __name__ == '__main__':
    main()
```

**continuous_poisson_comparison.png**:

![continuous_poisson_comparison](https://user-images.githubusercontent.com/5142394/94500671-8cf53f80-01c5-11eb-8330-8222889d67fa.png)

**relative_difference.png**:
![relative_difference](https://user-images.githubusercontent.com/5142394/94500676-8ff03000-01c5-11eb-834e-f9d6e58e9074.png)

**Comment by cranmer** [comment]
Looks good. If we wanted a unit test, maybe check against the implementations against some validated reference for some non-integer n. The validated (hardcoded) reference could come from the current numpy implementation since they all agree. But this would pick up on any future changes.

**Comment by matthewfeickert** [comment]
> The validated (hardcoded) reference could come from the current numpy implementation since they all agree. But this would pick up on any future changes.

Yup. This is what PR #1084 did. :+1:
