### ISSUE TITLE
Instantiation of Minuit from arrays

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/pyhf#977]
# Question

Currently the opt_minuit backend initializes `Minuit` with lots of keyword arguments that need to be constructed first:
https://github.com/scikit-hep/pyhf/blob/c429268e8f1b19e2d6e938f1ff35cddcc5ce29cf/src/pyhf/optimize/opt_minuit.py#L34-L55

There is an alternative available, which allows to use arrays to set the relevant values: [from_array_func](https://iminuit.readthedocs.io/en/stable/reference.html#iminuit.Minuit.from_array_func).

@kratsg suggested there might be interest to use it in `pyhf`. An example that uses `from_array_func` can be found [here](https://github.com/alexander-held/cabinetry/blob/061a2de19adb762e1f9fd31840e3ce8bfae822f4/src/cabinetry/fit.py#L95-L119).

# Relevant Issues and Pull Requests

none

**Comment by matthewfeickert** [comment]
@alexander-held All the optimizers are about to get radically overhauled in PR #951. That being said, I don't think it currently is setup to use `from_array_func`.
