### ISSUE TITLE
Top-Level Python API methods don't have docstrings rendered in docs

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#984]
# Description

The top level Python API methods pages on the docs website doesn't contain any of the rendered docstrings. For example, the `pyhf.set_backend()` API has examples (and it rather important for new users)

https://github.com/scikit-hep/pyhf/blob/e55eea408d7c28e3109338de96252119ac63f87a/src/pyhf/__init__.py#L42-L52

but the docs website doesn't show any of this

![not_rendered](https://user-images.githubusercontent.com/5142394/88368070-def79000-cd52-11ea-9f0e-5acbb4d45c6b.png)

# Expected Behavior

Have the docstrings be rendered in the docs 

# Actual Behavior

c.f. above

# Steps to Reproduce

Build the docs

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by kratsg** [comment]
This is broken due to the fact that we put a decorator on it. We just need to use `functools.wraps` and that should fix this.
