### ISSUE TITLE
Correlation matrix

### ISSUE THREAD

**Issue by cmerlass** [scikit-hep/pyhf#990]
Hi!
It would be nice to have the possibility to produce a correlation matrix between the systematics, together with the other diagnostic plots (pulls, impacts, etc...). It is often requested in approval stages and helps in understanding the fit results.
Is it already implemented somewhere? I couldn't find it...

Cheers,
Claudia

**Comment by kratsg** [comment]
Closing this in favor of #929. It's in the works. See #988 for a first implementation.

You can already access the underlying minuit implementation with v0.5.0 via

```python
...
result, result_obj = pyhf.infer.mle.fit(...., return_result_obj=True)
minuit_instance = result_obj.minuit
```

This won't be supported by scipy right now.
